// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package skillmetricsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateDay = `-- name: AggregateDay :one

WITH ex AS (
    SELECT
        execution_time_ms,
        (status = 'completed'
            AND output IS NOT NULL AND output <> ''
            AND execution_time_ms > 0 AND execution_time_ms < 60000) AS is_success,
        (status = 'failed'
            OR (status = 'completed'
                AND (output IS NULL OR output = '' OR execution_time_ms >= 60000))) AS is_failure
    FROM skill_executions
    WHERE skill_id = $1
      AND (created_at AT TIME ZONE 'UTC')::date = $2::date
),
counted AS (
    SELECT
        COUNT(*) FILTER (WHERE is_success OR is_failure)::int        AS invocations_count,
        COUNT(*) FILTER (WHERE is_success)::int                      AS success_count,
        COUNT(*) FILTER (WHERE is_failure)::int                      AS failure_count,
        AVG(execution_time_ms) FILTER (WHERE is_success OR is_failure) AS avg_ms,
        percentile_cont(0.95) WITHIN GROUP (
            ORDER BY execution_time_ms
        ) FILTER (WHERE is_success OR is_failure)                    AS p95_ms
    FROM ex
)
SELECT
    invocations_count,
    success_count,
    failure_count,
    CASE
        WHEN (success_count + failure_count) = 0 THEN NULL
        ELSE ROUND(success_count::numeric * 100
                   / (success_count + failure_count), 2)
    END::numeric(5,2)                                                AS success_rate,
    (CASE WHEN avg_ms IS NULL THEN NULL ELSE ROUND(avg_ms) END)::numeric AS avg_duration_ms,
    (CASE
        WHEN invocations_count < 10 THEN NULL
        WHEN p95_ms IS NULL THEN NULL
        ELSE ROUND(p95_ms)
    END)::numeric                                                   AS p95_duration_ms,
    0::int                                                           AS unique_callers_count
FROM counted
`

type AggregateDayParams struct {
	SkillID uuid.UUID   `json:"skill_id"`
	Day     pgtype.Date `json:"day"`
}

type AggregateDayRow struct {
	InvocationsCount   int32          `json:"invocations_count"`
	SuccessCount       int32          `json:"success_count"`
	FailureCount       int32          `json:"failure_count"`
	SuccessRate        pgtype.Numeric `json:"success_rate"`
	AvgDurationMs      pgtype.Numeric `json:"avg_duration_ms"`
	P95DurationMs      pgtype.Numeric `json:"p95_duration_ms"`
	UniqueCallersCount int32          `json:"unique_callers_count"`
}

// HU-52.2 — skill success rate tracking.
//
// DEFINICION DE EXITO (conservadora, identica en todas las queries):
//
//	status='completed' AND output IS NOT NULL AND output <> ''
//	AND execution_time_ms > 0 AND execution_time_ms < 60000
//
// DEFINICION DE FALLO:
//
//	status='failed'
//	OR (status='completed' AND (output IS NULL OR output='' OR execution_time_ms >= 60000))
//
// Las invocaciones 'pending'/'running' NO cuentan como exito ni fallo (en vuelo).
//
// skill_executions NO tiene columna de caller (created_by removido/inexistente,
// ver mig 000080 + 000142): unique_callers_count se computa como 0 hasta que
// exista esa columna. La query lo deja explicito.
// Computa los agregados de UN dia (UTC) para UN skill desde skill_executions.
// p95 solo se computa si hay >= 10 invocaciones contables (data suficiente),
// si no devuelve NULL. success_rate = success / (success+failure) * 100; NULL si
// no hubo invocaciones contables (evita 0% espurio). avg sobre exitos+fallos.
func (q *Queries) AggregateDay(ctx context.Context, arg AggregateDayParams) (AggregateDayRow, error) {
	row := q.db.QueryRow(ctx, aggregateDay, arg.SkillID, arg.Day)
	var i AggregateDayRow
	err := row.Scan(
		&i.InvocationsCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.SuccessRate,
		&i.AvgDurationMs,
		&i.P95DurationMs,
		&i.UniqueCallersCount,
	)
	return i, err
}

const cleanupDaily = `-- name: CleanupDaily :execrows
DELETE FROM skill_metrics_daily
WHERE day < (CURRENT_DATE - make_interval(days => $1::int))::date
`

// Retencion daily: borra filas mas viejas que N dias.
func (q *Queries) CleanupDaily(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupDaily, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupWeekly = `-- name: CleanupWeekly :execrows
DELETE FROM skill_metrics_weekly
WHERE week_start < (CURRENT_DATE - make_interval(days => $1::int))::date
`

// Retencion weekly: borra filas mas viejas que N dias.
func (q *Queries) CleanupWeekly(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupWeekly, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDailyByDay = `-- name: GetDailyByDay :many
SELECT skill_id, day, invocations_count, success_count, failure_count,
       success_rate::float8 AS success_rate,
       avg_duration_ms, p95_duration_ms, unique_callers_count,
       created_at, updated_at
FROM skill_metrics_daily
WHERE day = $1::date
ORDER BY success_rate ASC NULLS LAST, invocations_count DESC
`

type GetDailyByDayRow struct {
	SkillID            uuid.UUID   `json:"skill_id"`
	Day                pgtype.Date `json:"day"`
	InvocationsCount   int32       `json:"invocations_count"`
	SuccessCount       int32       `json:"success_count"`
	FailureCount       int32       `json:"failure_count"`
	SuccessRate        float64     `json:"success_rate"`
	AvgDurationMs      *int32      `json:"avg_duration_ms"`
	P95DurationMs      *int32      `json:"p95_duration_ms"`
	UniqueCallersCount int32       `json:"unique_callers_count"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

// Todas las metricas de un dia (todos los skills), peor success_rate primero.
func (q *Queries) GetDailyByDay(ctx context.Context, day pgtype.Date) ([]GetDailyByDayRow, error) {
	rows, err := q.db.Query(ctx, getDailyByDay, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyByDayRow
	for rows.Next() {
		var i GetDailyByDayRow
		if err := rows.Scan(
			&i.SkillID,
			&i.Day,
			&i.InvocationsCount,
			&i.SuccessCount,
			&i.FailureCount,
			&i.SuccessRate,
			&i.AvgDurationMs,
			&i.P95DurationMs,
			&i.UniqueCallersCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyBySkill = `-- name: GetDailyBySkill :many
SELECT skill_id, day, invocations_count, success_count, failure_count,
       success_rate::float8 AS success_rate,
       avg_duration_ms, p95_duration_ms, unique_callers_count,
       created_at, updated_at
FROM skill_metrics_daily
WHERE skill_id = $1
  AND day >= (CURRENT_DATE - make_interval(days => $2::int))::date
ORDER BY day DESC
`

type GetDailyBySkillParams struct {
	SkillID uuid.UUID `json:"skill_id"`
	Days    int32     `json:"days"`
}

type GetDailyBySkillRow struct {
	SkillID            uuid.UUID   `json:"skill_id"`
	Day                pgtype.Date `json:"day"`
	InvocationsCount   int32       `json:"invocations_count"`
	SuccessCount       int32       `json:"success_count"`
	FailureCount       int32       `json:"failure_count"`
	SuccessRate        float64     `json:"success_rate"`
	AvgDurationMs      *int32      `json:"avg_duration_ms"`
	P95DurationMs      *int32      `json:"p95_duration_ms"`
	UniqueCallersCount int32       `json:"unique_callers_count"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

// Series diarias de un skill, ultimos N dias, mas reciente primero.
func (q *Queries) GetDailyBySkill(ctx context.Context, arg GetDailyBySkillParams) ([]GetDailyBySkillRow, error) {
	rows, err := q.db.Query(ctx, getDailyBySkill, arg.SkillID, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyBySkillRow
	for rows.Next() {
		var i GetDailyBySkillRow
		if err := rows.Scan(
			&i.SkillID,
			&i.Day,
			&i.InvocationsCount,
			&i.SuccessCount,
			&i.FailureCount,
			&i.SuccessRate,
			&i.AvgDurationMs,
			&i.P95DurationMs,
			&i.UniqueCallersCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAlertFire = `-- name: InsertAlertFire :exec
INSERT INTO usage_alert_fires (alert_id, metric, threshold, observed_value, payload)
VALUES (
    $1,
    $2::text,
    $3::float8,
    $4::float8,
    $5
)
`

type InsertAlertFireParams struct {
	AlertID       uuid.UUID `json:"alert_id"`
	Metric        string    `json:"metric"`
	Threshold     float64   `json:"threshold"`
	ObservedValue float64   `json:"observed_value"`
	Payload       []byte    `json:"payload"`
}

// Registra un disparo de alerta (no crea la config, solo el fire).
func (q *Queries) InsertAlertFire(ctx context.Context, arg InsertAlertFireParams) error {
	_, err := q.db.Exec(ctx, insertAlertFire,
		arg.AlertID,
		arg.Metric,
		arg.Threshold,
		arg.ObservedValue,
		arg.Payload,
	)
	return err
}

const listActiveAlertsByMetric = `-- name: ListActiveAlertsByMetric :many
SELECT id, metric, threshold::float8 AS threshold, cooldown_secs, last_fired_at
FROM usage_alerts
WHERE active = TRUE
  AND metric = $1::text
`

type ListActiveAlertsByMetricRow struct {
	ID           uuid.UUID          `json:"id"`
	Metric       string             `json:"metric"`
	Threshold    float64            `json:"threshold"`
	CooldownSecs int32              `json:"cooldown_secs"`
	LastFiredAt  pgtype.Timestamptz `json:"last_fired_at"`
}

// Hook de alertas: usage_alerts activas que matchean el metric dado
// (ej 'skill_success_rate'). Si no hay ninguna, el hook NO crea nada.
func (q *Queries) ListActiveAlertsByMetric(ctx context.Context, metric string) ([]ListActiveAlertsByMetricRow, error) {
	rows, err := q.db.Query(ctx, listActiveAlertsByMetric, metric)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAlertsByMetricRow
	for rows.Next() {
		var i ListActiveAlertsByMetricRow
		if err := rows.Scan(
			&i.ID,
			&i.Metric,
			&i.Threshold,
			&i.CooldownSecs,
			&i.LastFiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSkillIDs = `-- name: ListActiveSkillIDs :many
SELECT id
FROM skills
WHERE deleted_at IS NULL
ORDER BY id
`

// Skills vivos (no soft-deleted): el aggregator itera sobre estos cada pasada.
func (q *Queries) ListActiveSkillIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveSkillIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowRateStreaks = `-- name: ListLowRateStreaks :many
WITH ranked AS (
    SELECT skill_id, day, success_rate,
           ROW_NUMBER() OVER (PARTITION BY skill_id ORDER BY day DESC) AS rn
    FROM skill_metrics_daily
    WHERE success_rate IS NOT NULL
)
SELECT skill_id,
       AVG(success_rate)::float8 AS avg_success_rate,
       MIN(day)::date            AS streak_start,
       MAX(day)::date            AS streak_end
FROM ranked
WHERE rn <= 3
GROUP BY skill_id
HAVING COUNT(*) = 3
   AND MAX(success_rate) < $1::numeric
`

type ListLowRateStreaksRow struct {
	SkillID        uuid.UUID   `json:"skill_id"`
	AvgSuccessRate float64     `json:"avg_success_rate"`
	StreakStart    pgtype.Date `json:"streak_start"`
	StreakEnd      pgtype.Date `json:"streak_end"`
}

// Skills cuyos ULTIMOS 3 dias consecutivos (con datos) tienen success_rate < 70.
// Usado por el hook de alertas. Mira solo los 3 dias mas recientes con metricas
// por skill; si los 3 estan por debajo del umbral, el skill califica.
func (q *Queries) ListLowRateStreaks(ctx context.Context, threshold pgtype.Numeric) ([]ListLowRateStreaksRow, error) {
	rows, err := q.db.Query(ctx, listLowRateStreaks, threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLowRateStreaksRow
	for rows.Next() {
		var i ListLowRateStreaksRow
		if err := rows.Scan(
			&i.SkillID,
			&i.AvgSuccessRate,
			&i.StreakStart,
			&i.StreakEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlowest = `-- name: ListSlowest :many
SELECT skill_id,
       MAX(p95_duration_ms)::int       AS p95_duration_ms,
       SUM(invocations_count)::bigint  AS invocations_count
FROM skill_metrics_daily
WHERE day >= (CURRENT_DATE - make_interval(days => $1::int))::date
  AND p95_duration_ms IS NOT NULL
GROUP BY skill_id
ORDER BY p95_duration_ms DESC
LIMIT $2::int
`

type ListSlowestParams struct {
	Days        int32 `json:"days"`
	ResultLimit int32 `json:"result_limit"`
}

type ListSlowestRow struct {
	SkillID          uuid.UUID `json:"skill_id"`
	P95DurationMs    int32     `json:"p95_duration_ms"`
	InvocationsCount int64     `json:"invocations_count"`
}

// Peor p95 en la ventana de N dias (MAX de los p95 diarios disponibles).
func (q *Queries) ListSlowest(ctx context.Context, arg ListSlowestParams) ([]ListSlowestRow, error) {
	rows, err := q.db.Query(ctx, listSlowest, arg.Days, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSlowestRow
	for rows.Next() {
		var i ListSlowestRow
		if err := rows.Scan(&i.SkillID, &i.P95DurationMs, &i.InvocationsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopFailed = `-- name: ListTopFailed :many
SELECT skill_id,
       SUM(invocations_count)::bigint AS invocations_count,
       SUM(success_count)::bigint     AS success_count,
       SUM(failure_count)::bigint     AS failure_count,
       CASE
           WHEN SUM(success_count) + SUM(failure_count) = 0 THEN NULL
           ELSE ROUND(SUM(success_count)::numeric * 100
                      / (SUM(success_count) + SUM(failure_count)), 2)
       END::float8 AS success_rate
FROM skill_metrics_daily
WHERE day >= (CURRENT_DATE - make_interval(days => $1::int))::date
GROUP BY skill_id
HAVING SUM(success_count) + SUM(failure_count) > 0
ORDER BY success_rate ASC NULLS LAST, invocations_count DESC
LIMIT $2::int
`

type ListTopFailedParams struct {
	Days        int32 `json:"days"`
	ResultLimit int32 `json:"result_limit"`
}

type ListTopFailedRow struct {
	SkillID          uuid.UUID `json:"skill_id"`
	InvocationsCount int64     `json:"invocations_count"`
	SuccessCount     int64     `json:"success_count"`
	FailureCount     int64     `json:"failure_count"`
	SuccessRate      float64   `json:"success_rate"`
}

// Peores success_rate agregados en la ventana de N dias (solo skills con
// invocaciones reales). Pondera por invocaciones, no por dia.
func (q *Queries) ListTopFailed(ctx context.Context, arg ListTopFailedParams) ([]ListTopFailedRow, error) {
	rows, err := q.db.Query(ctx, listTopFailed, arg.Days, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopFailedRow
	for rows.Next() {
		var i ListTopFailedRow
		if err := rows.Scan(
			&i.SkillID,
			&i.InvocationsCount,
			&i.SuccessCount,
			&i.FailureCount,
			&i.SuccessRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupWeek = `-- name: RollupWeek :exec
INSERT INTO skill_metrics_weekly (
    skill_id, week_start, invocations_count, success_count, failure_count,
    success_rate, avg_duration_ms, p95_duration_ms, unique_callers_count, updated_at
)
SELECT
    skill_id,
    $1::date AS week_start,
    SUM(invocations_count)::int  AS invocations_count,
    SUM(success_count)::int      AS success_count,
    SUM(failure_count)::int      AS failure_count,
    CASE
        WHEN SUM(success_count) + SUM(failure_count) = 0 THEN NULL
        ELSE ROUND(SUM(success_count)::numeric * 100
                   / (SUM(success_count) + SUM(failure_count)), 2)
    END::numeric(5,2)            AS success_rate,
    CASE
        WHEN SUM(invocations_count) = 0 THEN NULL
        ELSE ROUND(
            SUM(avg_duration_ms::numeric * invocations_count)
            FILTER (WHERE avg_duration_ms IS NOT NULL)
            / NULLIF(SUM(invocations_count)
                FILTER (WHERE avg_duration_ms IS NOT NULL), 0)
        )::int
    END                          AS avg_duration_ms,
    MAX(p95_duration_ms)::int    AS p95_duration_ms,
    MAX(unique_callers_count)::int AS unique_callers_count
FROM skill_metrics_daily
WHERE day >= $1::date
  AND day <  ($1::date + INTERVAL '7 days')
GROUP BY skill_id
ON CONFLICT (skill_id, week_start) DO UPDATE
SET invocations_count    = EXCLUDED.invocations_count,
    success_count        = EXCLUDED.success_count,
    failure_count        = EXCLUDED.failure_count,
    success_rate         = EXCLUDED.success_rate,
    avg_duration_ms      = EXCLUDED.avg_duration_ms,
    p95_duration_ms      = EXCLUDED.p95_duration_ms,
    unique_callers_count = EXCLUDED.unique_callers_count,
    updated_at           = NOW()
`

// Consolida las diarias de la semana de sqlc.arg('week_start') en weekly.
// success_rate ponderado por invocaciones; avg ponderado; p95 = MAX de p95
// diarios (aproximacion conservadora). Idempotente por PK (skill_id, week_start).
func (q *Queries) RollupWeek(ctx context.Context, weekStart pgtype.Date) error {
	_, err := q.db.Exec(ctx, rollupWeek, weekStart)
	return err
}

const touchAlertFired = `-- name: TouchAlertFired :exec
UPDATE usage_alerts
SET last_fired_at = NOW(), fire_count = fire_count + 1
WHERE id = $1
`

func (q *Queries) TouchAlertFired(ctx context.Context, alertID uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAlertFired, alertID)
	return err
}

const upsertDaily = `-- name: UpsertDaily :exec
INSERT INTO skill_metrics_daily (
    skill_id, day, invocations_count, success_count, failure_count,
    success_rate, avg_duration_ms, p95_duration_ms, unique_callers_count, updated_at
) VALUES (
    $1, $2,
    $3, $4, $5,
    $6, $7, $8,
    $9, NOW()
)
ON CONFLICT (skill_id, day) DO UPDATE
SET invocations_count    = $3,
    success_count        = $4,
    failure_count        = $5,
    success_rate         = $6,
    avg_duration_ms      = $7,
    p95_duration_ms      = $8,
    unique_callers_count = $9,
    updated_at           = NOW()
`

type UpsertDailyParams struct {
	SkillID            uuid.UUID      `json:"skill_id"`
	Day                pgtype.Date    `json:"day"`
	InvocationsCount   int32          `json:"invocations_count"`
	SuccessCount       int32          `json:"success_count"`
	FailureCount       int32          `json:"failure_count"`
	SuccessRate        pgtype.Numeric `json:"success_rate"`
	AvgDurationMs      *int32         `json:"avg_duration_ms"`
	P95DurationMs      *int32         `json:"p95_duration_ms"`
	UniqueCallersCount int32          `json:"unique_callers_count"`
}

// Persiste (idempotente por PK) el agregado diario de un skill.
func (q *Queries) UpsertDaily(ctx context.Context, arg UpsertDailyParams) error {
	_, err := q.db.Exec(ctx, upsertDaily,
		arg.SkillID,
		arg.Day,
		arg.InvocationsCount,
		arg.SuccessCount,
		arg.FailureCount,
		arg.SuccessRate,
		arg.AvgDurationMs,
		arg.P95DurationMs,
		arg.UniqueCallersCount,
	)
	return err
}
