






ALTER TABLE users ADD COLUMN IF NOT EXISTS is_erased BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS erased_at TIMESTAMPTZ;



CREATE INDEX IF NOT EXISTS users_is_erased_idx ON users(is_erased)
  WHERE is_erased = TRUE;
