






BEGIN;

CREATE TABLE IF NOT EXISTS system_state (
  key VARCHAR(100) PRIMARY KEY,
  value JSONB NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON system_state TO app_user;
DO $g$ BEGIN
  EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON system_state TO app_admin';
EXCEPTION WHEN OTHERS THEN NULL;
END $g$;
DO $g$ BEGIN
  EXECUTE 'GRANT SELECT ON system_state TO app_readonly';
EXCEPTION WHEN OTHERS THEN NULL;
END $g$;



ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMIT;
