// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package projectrepodb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearProjectDefault = `-- name: ClearProjectDefault :exec
UPDATE project_repositories
SET is_default = false
WHERE project_id = $1 AND id <> $2 AND is_default = true
`

type ClearProjectDefaultParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) ClearProjectDefault(ctx context.Context, arg ClearProjectDefaultParams) error {
	_, err := q.db.Exec(ctx, clearProjectDefault, arg.ProjectID, arg.ID)
	return err
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT id, project_id, name, url,
  COALESCE(branch_default, '')::text AS branch_default,
  COALESCE(kind, '')::text AS kind,
  is_default,
  COALESCE(workflow, '')::text AS workflow,
  COALESCE(notes, '')::text AS notes,
  COALESCE(root_path, '')::text AS root_path,
  created_at, updated_at, deleted_at
FROM project_repositories
WHERE id = $1 AND deleted_at IS NULL
`

type GetRepoByIDRow struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	Name          string             `json:"name"`
	Url           string             `json:"url"`
	BranchDefault string             `json:"branch_default"`
	Kind          string             `json:"kind"`
	IsDefault     bool               `json:"is_default"`
	Workflow      string             `json:"workflow"`
	Notes         string             `json:"notes"`
	RootPath      string             `json:"root_path"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetRepoByID(ctx context.Context, id uuid.UUID) (GetRepoByIDRow, error) {
	row := q.db.QueryRow(ctx, getRepoByID, id)
	var i GetRepoByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Url,
		&i.BranchDefault,
		&i.Kind,
		&i.IsDefault,
		&i.Workflow,
		&i.Notes,
		&i.RootPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRepoByName = `-- name: GetRepoByName :one
SELECT id, project_id, name, url,
  COALESCE(branch_default, '')::text AS branch_default,
  COALESCE(kind, '')::text AS kind,
  is_default,
  COALESCE(workflow, '')::text AS workflow,
  COALESCE(notes, '')::text AS notes,
  COALESCE(root_path, '')::text AS root_path,
  created_at, updated_at, deleted_at
FROM project_repositories
WHERE project_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetRepoByNameParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
}

type GetRepoByNameRow struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	Name          string             `json:"name"`
	Url           string             `json:"url"`
	BranchDefault string             `json:"branch_default"`
	Kind          string             `json:"kind"`
	IsDefault     bool               `json:"is_default"`
	Workflow      string             `json:"workflow"`
	Notes         string             `json:"notes"`
	RootPath      string             `json:"root_path"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetRepoByName(ctx context.Context, arg GetRepoByNameParams) (GetRepoByNameRow, error) {
	row := q.db.QueryRow(ctx, getRepoByName, arg.ProjectID, arg.Name)
	var i GetRepoByNameRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Url,
		&i.BranchDefault,
		&i.Kind,
		&i.IsDefault,
		&i.Workflow,
		&i.Notes,
		&i.RootPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRepoProjectID = `-- name: GetRepoProjectID :one
SELECT project_id FROM project_repositories
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRepoProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRepoProjectID, id)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const insertRepo = `-- name: InsertRepo :one
INSERT INTO project_repositories
  (project_id, name, url, branch_default, kind, is_default, workflow, notes, root_path)
VALUES (
  $1,
  $2,
  $3,
  NULLIF($4::text, ''),
  NULLIF($5::text, ''),
  $6,
  NULLIF($7::text, ''),
  NULLIF($8::text, ''),
  NULLIF($9::text, '')
)
RETURNING id, project_id, name, url,
  COALESCE(branch_default, '')::text AS branch_default,
  COALESCE(kind, '')::text AS kind,
  is_default,
  COALESCE(workflow, '')::text AS workflow,
  COALESCE(notes, '')::text AS notes,
  COALESCE(root_path, '')::text AS root_path,
  created_at, updated_at, deleted_at
`

type InsertRepoParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	Name          string    `json:"name"`
	Url           string    `json:"url"`
	BranchDefault string    `json:"branch_default"`
	Kind          string    `json:"kind"`
	IsDefault     bool      `json:"is_default"`
	Workflow      string    `json:"workflow"`
	Notes         string    `json:"notes"`
	RootPath      string    `json:"root_path"`
}

type InsertRepoRow struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	Name          string             `json:"name"`
	Url           string             `json:"url"`
	BranchDefault string             `json:"branch_default"`
	Kind          string             `json:"kind"`
	IsDefault     bool               `json:"is_default"`
	Workflow      string             `json:"workflow"`
	Notes         string             `json:"notes"`
	RootPath      string             `json:"root_path"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertRepo(ctx context.Context, arg InsertRepoParams) (InsertRepoRow, error) {
	row := q.db.QueryRow(ctx, insertRepo,
		arg.ProjectID,
		arg.Name,
		arg.Url,
		arg.BranchDefault,
		arg.Kind,
		arg.IsDefault,
		arg.Workflow,
		arg.Notes,
		arg.RootPath,
	)
	var i InsertRepoRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Url,
		&i.BranchDefault,
		&i.Kind,
		&i.IsDefault,
		&i.Workflow,
		&i.Notes,
		&i.RootPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listReposByProject = `-- name: ListReposByProject :many
SELECT id, project_id, name, url,
  COALESCE(branch_default, '')::text AS branch_default,
  COALESCE(kind, '')::text AS kind,
  is_default,
  COALESCE(workflow, '')::text AS workflow,
  COALESCE(notes, '')::text AS notes,
  COALESCE(root_path, '')::text AS root_path,
  created_at, updated_at, deleted_at
FROM project_repositories
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY is_default DESC, name ASC
`

type ListReposByProjectRow struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	Name          string             `json:"name"`
	Url           string             `json:"url"`
	BranchDefault string             `json:"branch_default"`
	Kind          string             `json:"kind"`
	IsDefault     bool               `json:"is_default"`
	Workflow      string             `json:"workflow"`
	Notes         string             `json:"notes"`
	RootPath      string             `json:"root_path"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListReposByProject(ctx context.Context, projectID uuid.UUID) ([]ListReposByProjectRow, error) {
	rows, err := q.db.Query(ctx, listReposByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReposByProjectRow
	for rows.Next() {
		var i ListReposByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Url,
			&i.BranchDefault,
			&i.Kind,
			&i.IsDefault,
			&i.Workflow,
			&i.Notes,
			&i.RootPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepoAsDefault = `-- name: SetRepoAsDefault :one
UPDATE project_repositories
SET is_default = true
WHERE id = $1
RETURNING id, project_id, name, url,
  COALESCE(branch_default, '')::text AS branch_default,
  COALESCE(kind, '')::text AS kind,
  is_default,
  COALESCE(workflow, '')::text AS workflow,
  COALESCE(notes, '')::text AS notes,
  COALESCE(root_path, '')::text AS root_path,
  created_at, updated_at, deleted_at
`

type SetRepoAsDefaultRow struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	Name          string             `json:"name"`
	Url           string             `json:"url"`
	BranchDefault string             `json:"branch_default"`
	Kind          string             `json:"kind"`
	IsDefault     bool               `json:"is_default"`
	Workflow      string             `json:"workflow"`
	Notes         string             `json:"notes"`
	RootPath      string             `json:"root_path"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) SetRepoAsDefault(ctx context.Context, id uuid.UUID) (SetRepoAsDefaultRow, error) {
	row := q.db.QueryRow(ctx, setRepoAsDefault, id)
	var i SetRepoAsDefaultRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Url,
		&i.BranchDefault,
		&i.Kind,
		&i.IsDefault,
		&i.Workflow,
		&i.Notes,
		&i.RootPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteRepo = `-- name: SoftDeleteRepo :execrows
UPDATE project_repositories
SET deleted_at = NOW(), is_default = false
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRepo(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteRepo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRepo = `-- name: UpdateRepo :one
UPDATE project_repositories
SET
  url            = CASE WHEN $1::text            IS NOT NULL THEN $1::text            ELSE url            END,
  branch_default = CASE WHEN $2::text IS NOT NULL THEN NULLIF($2::text, '') ELSE branch_default END,
  kind           = CASE WHEN $3::text           IS NOT NULL THEN NULLIF($3::text, '')           ELSE kind           END,
  workflow       = CASE WHEN $4::text       IS NOT NULL THEN NULLIF($4::text, '')       ELSE workflow       END,
  notes          = CASE WHEN $5::text          IS NOT NULL THEN NULLIF($5::text, '')          ELSE notes          END,
  root_path      = CASE WHEN $6::text      IS NOT NULL THEN NULLIF($6::text, '')      ELSE root_path      END
WHERE id = $7 AND deleted_at IS NULL
RETURNING id, project_id, name, url,
  COALESCE(branch_default, '')::text AS branch_default,
  COALESCE(kind, '')::text AS kind,
  is_default,
  COALESCE(workflow, '')::text AS workflow,
  COALESCE(notes, '')::text AS notes,
  COALESCE(root_path, '')::text AS root_path,
  created_at, updated_at, deleted_at
`

type UpdateRepoParams struct {
	Url           *string   `json:"url"`
	BranchDefault *string   `json:"branch_default"`
	Kind          *string   `json:"kind"`
	Workflow      *string   `json:"workflow"`
	Notes         *string   `json:"notes"`
	RootPath      *string   `json:"root_path"`
	ID            uuid.UUID `json:"id"`
}

type UpdateRepoRow struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	Name          string             `json:"name"`
	Url           string             `json:"url"`
	BranchDefault string             `json:"branch_default"`
	Kind          string             `json:"kind"`
	IsDefault     bool               `json:"is_default"`
	Workflow      string             `json:"workflow"`
	Notes         string             `json:"notes"`
	RootPath      string             `json:"root_path"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateRepo(ctx context.Context, arg UpdateRepoParams) (UpdateRepoRow, error) {
	row := q.db.QueryRow(ctx, updateRepo,
		arg.Url,
		arg.BranchDefault,
		arg.Kind,
		arg.Workflow,
		arg.Notes,
		arg.RootPath,
		arg.ID,
	)
	var i UpdateRepoRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Url,
		&i.BranchDefault,
		&i.Kind,
		&i.IsDefault,
		&i.Workflow,
		&i.Notes,
		&i.RootPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
