// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package attachmentdb

import (
	"context"

	"github.com/google/uuid"
)

const cleanupOrphans = `-- name: CleanupOrphans :many
DELETE FROM file_attachments fa
WHERE NOT EXISTS (SELECT 1 FROM issues WHERE id = fa.entity_id AND entity_type = 'user_story')
  AND NOT EXISTS (SELECT 1 FROM sdd_requirements WHERE id = fa.entity_id AND entity_type = 'requirement')
RETURNING s3_key
`

func (q *Queries) CleanupOrphans(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, cleanupOrphans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var s3_key string
		if err := rows.Scan(&s3_key); err != nil {
			return nil, err
		}
		items = append(items, s3_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAttachment = `-- name: DeleteAttachment :one
DELETE FROM file_attachments WHERE id = $1
RETURNING s3_key
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, deleteAttachment, id)
	var s3_key string
	err := row.Scan(&s3_key)
	return s3_key, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, entity_type, entity_id, filename, s3_key, size_bytes, mime_type, created_by, created_at, organization_id
FROM file_attachments
WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (FileAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i FileAttachment
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Filename,
		&i.S3Key,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO file_attachments (
    entity_type, entity_id, filename, s3_key, size_bytes, mime_type, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, entity_type, entity_id, filename, s3_key, size_bytes, mime_type, created_by, created_at, organization_id
`

type InsertAttachmentParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Filename   string    `json:"filename"`
	S3Key      string    `json:"s3_key"`
	SizeBytes  int64     `json:"size_bytes"`
	MimeType   string    `json:"mime_type"`
	CreatedBy  *string   `json:"created_by"`
}

// organization_id se autofill por DEFAULT current_org_id() (RLS, DOMAINSERV-112).
func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (FileAttachment, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.EntityType,
		arg.EntityID,
		arg.Filename,
		arg.S3Key,
		arg.SizeBytes,
		arg.MimeType,
		arg.CreatedBy,
	)
	var i FileAttachment
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Filename,
		&i.S3Key,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const listByEntity = `-- name: ListByEntity :many
SELECT id, entity_type, entity_id, filename, s3_key, size_bytes, mime_type, created_by, created_at, organization_id
FROM file_attachments
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
`

type ListByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) ListByEntity(ctx context.Context, arg ListByEntityParams) ([]FileAttachment, error) {
	rows, err := q.db.Query(ctx, listByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileAttachment
	for rows.Next() {
		var i FileAttachment
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Filename,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteEntity = `-- name: PromoteEntity :execrows
UPDATE file_attachments
SET entity_type = $1, entity_id = $2
WHERE entity_type = $3 AND entity_id = $4
`

type PromoteEntityParams struct {
	ToType   string    `json:"to_type"`
	ToID     uuid.UUID `json:"to_id"`
	FromType string    `json:"from_type"`
	FromID   uuid.UUID `json:"from_id"`
}

func (q *Queries) PromoteEntity(ctx context.Context, arg PromoteEntityParams) (int64, error) {
	result, err := q.db.Exec(ctx, promoteEntity,
		arg.ToType,
		arg.ToID,
		arg.FromType,
		arg.FromID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
