// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package usagealertsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteAlert = `-- name: DeleteAlert :execrows
DELETE FROM usage_alerts WHERE id = $1
`

func (q *Queries) DeleteAlert(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAlert, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAlert = `-- name: GetAlert :one
SELECT id, name, metric, threshold::float8 AS threshold, condition, channel,
       recipients, cooldown_secs, active, last_fired_at, fire_count,
       created_at, updated_at
FROM usage_alerts
WHERE id = $1
`

type GetAlertRow struct {
	ID           uuid.UUID  `json:"id"`
	Name         string     `json:"name"`
	Metric       string     `json:"metric"`
	Threshold    float64    `json:"threshold"`
	Condition    string     `json:"condition"`
	Channel      string     `json:"channel"`
	Recipients   []string   `json:"recipients"`
	CooldownSecs int32      `json:"cooldown_secs"`
	Active       bool       `json:"active"`
	LastFiredAt  *time.Time `json:"last_fired_at"`
	FireCount    int32      `json:"fire_count"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

func (q *Queries) GetAlert(ctx context.Context, id uuid.UUID) (GetAlertRow, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i GetAlertRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metric,
		&i.Threshold,
		&i.Condition,
		&i.Channel,
		&i.Recipients,
		&i.CooldownSecs,
		&i.Active,
		&i.LastFiredAt,
		&i.FireCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAlert = `-- name: InsertAlert :one
INSERT INTO usage_alerts
    (name, metric, threshold, condition, channel, recipients, cooldown_secs)
VALUES ($1, $2, $7::float8, $3, $4, $5, $6)
RETURNING id, created_at, updated_at
`

type InsertAlertParams struct {
	Name         string   `json:"name"`
	Metric       string   `json:"metric"`
	Condition    string   `json:"condition"`
	Channel      string   `json:"channel"`
	Recipients   []string `json:"recipients"`
	CooldownSecs int32    `json:"cooldown_secs"`
	Threshold    float64  `json:"threshold"`
}

type InsertAlertRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) (InsertAlertRow, error) {
	row := q.db.QueryRow(ctx, insertAlert,
		arg.Name,
		arg.Metric,
		arg.Condition,
		arg.Channel,
		arg.Recipients,
		arg.CooldownSecs,
		arg.Threshold,
	)
	var i InsertAlertRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertAlertFire = `-- name: InsertAlertFire :exec
INSERT INTO usage_alert_fires
    (alert_id, metric, threshold, observed_value, payload)
VALUES ($1, $2, $4::float8, $5::float8, $3)
`

type InsertAlertFireParams struct {
	AlertID       uuid.UUID `json:"alert_id"`
	Metric        string    `json:"metric"`
	Payload       []byte    `json:"payload"`
	Threshold     float64   `json:"threshold"`
	ObservedValue float64   `json:"observed_value"`
}

func (q *Queries) InsertAlertFire(ctx context.Context, arg InsertAlertFireParams) error {
	_, err := q.db.Exec(ctx, insertAlertFire,
		arg.AlertID,
		arg.Metric,
		arg.Payload,
		arg.Threshold,
		arg.ObservedValue,
	)
	return err
}

const listActiveAlertsByMetrics = `-- name: ListActiveAlertsByMetrics :many
SELECT id, name, metric, threshold::float8 AS threshold, condition, channel,
       recipients, cooldown_secs, active, last_fired_at, fire_count,
       created_at, updated_at
FROM usage_alerts
WHERE active = TRUE
  AND metric = ANY($1::text[])
`

type ListActiveAlertsByMetricsRow struct {
	ID           uuid.UUID  `json:"id"`
	Name         string     `json:"name"`
	Metric       string     `json:"metric"`
	Threshold    float64    `json:"threshold"`
	Condition    string     `json:"condition"`
	Channel      string     `json:"channel"`
	Recipients   []string   `json:"recipients"`
	CooldownSecs int32      `json:"cooldown_secs"`
	Active       bool       `json:"active"`
	LastFiredAt  *time.Time `json:"last_fired_at"`
	FireCount    int32      `json:"fire_count"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

func (q *Queries) ListActiveAlertsByMetrics(ctx context.Context, dollar_1 []string) ([]ListActiveAlertsByMetricsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAlertsByMetrics, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAlertsByMetricsRow
	for rows.Next() {
		var i ListActiveAlertsByMetricsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Metric,
			&i.Threshold,
			&i.Condition,
			&i.Channel,
			&i.Recipients,
			&i.CooldownSecs,
			&i.Active,
			&i.LastFiredAt,
			&i.FireCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertFires = `-- name: ListAlertFires :many
SELECT f.id, f.alert_id, f.metric, f.threshold::float8 AS threshold,
       f.observed_value::float8 AS observed_value, f.payload, f.fired_at
FROM usage_alert_fires f
JOIN usage_alerts a ON a.id = f.alert_id
WHERE f.alert_id = $1
ORDER BY f.fired_at DESC
LIMIT $2
`

type ListAlertFiresParams struct {
	AlertID uuid.UUID `json:"alert_id"`
	Limit   int32     `json:"limit"`
}

type ListAlertFiresRow struct {
	ID            uuid.UUID `json:"id"`
	AlertID       uuid.UUID `json:"alert_id"`
	Metric        string    `json:"metric"`
	Threshold     float64   `json:"threshold"`
	ObservedValue float64   `json:"observed_value"`
	Payload       []byte    `json:"payload"`
	FiredAt       time.Time `json:"fired_at"`
}

func (q *Queries) ListAlertFires(ctx context.Context, arg ListAlertFiresParams) ([]ListAlertFiresRow, error) {
	rows, err := q.db.Query(ctx, listAlertFires, arg.AlertID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertFiresRow
	for rows.Next() {
		var i ListAlertFiresRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.Metric,
			&i.Threshold,
			&i.ObservedValue,
			&i.Payload,
			&i.FiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, name, metric, threshold::float8 AS threshold, condition, channel,
       recipients, cooldown_secs, active, last_fired_at, fire_count,
       created_at, updated_at
FROM usage_alerts
ORDER BY created_at DESC
`

type ListAlertsRow struct {
	ID           uuid.UUID  `json:"id"`
	Name         string     `json:"name"`
	Metric       string     `json:"metric"`
	Threshold    float64    `json:"threshold"`
	Condition    string     `json:"condition"`
	Channel      string     `json:"channel"`
	Recipients   []string   `json:"recipients"`
	CooldownSecs int32      `json:"cooldown_secs"`
	Active       bool       `json:"active"`
	LastFiredAt  *time.Time `json:"last_fired_at"`
	FireCount    int32      `json:"fire_count"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

func (q *Queries) ListAlerts(ctx context.Context) ([]ListAlertsRow, error) {
	rows, err := q.db.Query(ctx, listAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertsRow
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Metric,
			&i.Threshold,
			&i.Condition,
			&i.Channel,
			&i.Recipients,
			&i.CooldownSecs,
			&i.Active,
			&i.LastFiredAt,
			&i.FireCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAlertActive = `-- name: SetAlertActive :execrows
UPDATE usage_alerts SET active = $2 WHERE id = $1
`

type SetAlertActiveParams struct {
	ID     uuid.UUID `json:"id"`
	Active bool      `json:"active"`
}

func (q *Queries) SetAlertActive(ctx context.Context, arg SetAlertActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAlertActive, arg.ID, arg.Active)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAlertFired = `-- name: TouchAlertFired :exec
UPDATE usage_alerts
SET last_fired_at = NOW(), fire_count = fire_count + 1
WHERE id = $1
`

func (q *Queries) TouchAlertFired(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAlertFired, id)
	return err
}

const updateAlert = `-- name: UpdateAlert :one
UPDATE usage_alerts SET
    name          = COALESCE($2, name),
    metric        = COALESCE($3, metric),
    threshold     = COALESCE($4::float8, threshold),
    condition     = COALESCE($5, condition),
    channel       = COALESCE($6, channel),
    recipients    = COALESCE($7::text[], recipients),
    cooldown_secs = COALESCE($8, cooldown_secs),
    updated_at    = NOW()
WHERE id = $1
RETURNING id, name, metric, threshold::float8 AS threshold, condition, channel,
          recipients, cooldown_secs, active, last_fired_at, fire_count,
          created_at, updated_at
`

type UpdateAlertParams struct {
	ID           uuid.UUID `json:"id"`
	Name         *string   `json:"name"`
	Metric       *string   `json:"metric"`
	Threshold    *float64  `json:"threshold"`
	Condition    *string   `json:"condition"`
	Channel      *string   `json:"channel"`
	Recipients   []string  `json:"recipients"`
	CooldownSecs *int32    `json:"cooldown_secs"`
}

type UpdateAlertRow struct {
	ID           uuid.UUID  `json:"id"`
	Name         string     `json:"name"`
	Metric       string     `json:"metric"`
	Threshold    float64    `json:"threshold"`
	Condition    string     `json:"condition"`
	Channel      string     `json:"channel"`
	Recipients   []string   `json:"recipients"`
	CooldownSecs int32      `json:"cooldown_secs"`
	Active       bool       `json:"active"`
	LastFiredAt  *time.Time `json:"last_fired_at"`
	FireCount    int32      `json:"fire_count"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

func (q *Queries) UpdateAlert(ctx context.Context, arg UpdateAlertParams) (UpdateAlertRow, error) {
	row := q.db.QueryRow(ctx, updateAlert,
		arg.ID,
		arg.Name,
		arg.Metric,
		arg.Threshold,
		arg.Condition,
		arg.Channel,
		arg.Recipients,
		arg.CooldownSecs,
	)
	var i UpdateAlertRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metric,
		&i.Threshold,
		&i.Condition,
		&i.Channel,
		&i.Recipients,
		&i.CooldownSecs,
		&i.Active,
		&i.LastFiredAt,
		&i.FireCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
