// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package capturedpromptdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeTurn = `-- name: CompleteTurn :one
UPDATE prompt_captured
SET response_chars = $1,
    estimated_tokens_out = $2,
    model = COALESCE(NULLIF($3, ''), model),
    turn_completed_at = NOW()
WHERE id = $4
RETURNING id, user_id, project_id, content,
          COALESCE(client_kind,'')::text AS client_kind,
          COALESCE(model,'')::text AS model,
          char_count, response_chars, estimated_tokens_in, estimated_tokens_out,
          captured_at, turn_completed_at
`

type CompleteTurnParams struct {
	ResponseChars      int32       `json:"response_chars"`
	EstimatedTokensOut int32       `json:"estimated_tokens_out"`
	Model              interface{} `json:"model"`
	ID                 uuid.UUID   `json:"id"`
}

type CompleteTurnRow struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	ProjectID          *uuid.UUID         `json:"project_id"`
	Content            string             `json:"content"`
	ClientKind         string             `json:"client_kind"`
	Model              string             `json:"model"`
	CharCount          int32              `json:"char_count"`
	ResponseChars      int32              `json:"response_chars"`
	EstimatedTokensIn  int32              `json:"estimated_tokens_in"`
	EstimatedTokensOut int32              `json:"estimated_tokens_out"`
	CapturedAt         time.Time          `json:"captured_at"`
	TurnCompletedAt    pgtype.Timestamptz `json:"turn_completed_at"`
}

func (q *Queries) CompleteTurn(ctx context.Context, arg CompleteTurnParams) (CompleteTurnRow, error) {
	row := q.db.QueryRow(ctx, completeTurn,
		arg.ResponseChars,
		arg.EstimatedTokensOut,
		arg.Model,
		arg.ID,
	)
	var i CompleteTurnRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Content,
		&i.ClientKind,
		&i.Model,
		&i.CharCount,
		&i.ResponseChars,
		&i.EstimatedTokensIn,
		&i.EstimatedTokensOut,
		&i.CapturedAt,
		&i.TurnCompletedAt,
	)
	return i, err
}

const countPrompts = `-- name: CountPrompts :one
SELECT COUNT(*) FROM prompt_captured
WHERE ($1::uuid IS NULL OR project_id = $1::uuid)
  AND ($2::uuid IS NULL OR user_id = $2::uuid)
`

type CountPromptsParams struct {
	ProjectID *uuid.UUID `json:"project_id"`
	UserID    *uuid.UUID `json:"user_id"`
}

func (q *Queries) CountPrompts(ctx context.Context, arg CountPromptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPrompts, arg.ProjectID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPrompt = `-- name: GetPrompt :one
SELECT id, user_id, project_id, content,
       COALESCE(client_kind,'')::text AS client_kind,
       COALESCE(model,'')::text AS model,
       char_count, response_chars, estimated_tokens_in, estimated_tokens_out,
       captured_at, turn_completed_at
FROM prompt_captured WHERE id = $1
`

type GetPromptRow struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	ProjectID          *uuid.UUID         `json:"project_id"`
	Content            string             `json:"content"`
	ClientKind         string             `json:"client_kind"`
	Model              string             `json:"model"`
	CharCount          int32              `json:"char_count"`
	ResponseChars      int32              `json:"response_chars"`
	EstimatedTokensIn  int32              `json:"estimated_tokens_in"`
	EstimatedTokensOut int32              `json:"estimated_tokens_out"`
	CapturedAt         time.Time          `json:"captured_at"`
	TurnCompletedAt    pgtype.Timestamptz `json:"turn_completed_at"`
}

func (q *Queries) GetPrompt(ctx context.Context, id uuid.UUID) (GetPromptRow, error) {
	row := q.db.QueryRow(ctx, getPrompt, id)
	var i GetPromptRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Content,
		&i.ClientKind,
		&i.Model,
		&i.CharCount,
		&i.ResponseChars,
		&i.EstimatedTokensIn,
		&i.EstimatedTokensOut,
		&i.CapturedAt,
		&i.TurnCompletedAt,
	)
	return i, err
}

const insertPrompt = `-- name: InsertPrompt :one
INSERT INTO prompt_captured (user_id, project_id, content, client_kind, model, char_count, estimated_tokens_in)
VALUES ($1, $2, $3,
        NULLIF($4, ''), NULLIF($5, ''),
        $6, $7)
RETURNING id, user_id, project_id, content,
          COALESCE(client_kind,'')::text AS client_kind,
          COALESCE(model,'')::text AS model,
          char_count, response_chars, estimated_tokens_in, estimated_tokens_out,
          captured_at, turn_completed_at
`

type InsertPromptParams struct {
	UserID            uuid.UUID   `json:"user_id"`
	ProjectID         *uuid.UUID  `json:"project_id"`
	Content           string      `json:"content"`
	ClientKind        interface{} `json:"client_kind"`
	Model             interface{} `json:"model"`
	CharCount         int32       `json:"char_count"`
	EstimatedTokensIn int32       `json:"estimated_tokens_in"`
}

type InsertPromptRow struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	ProjectID          *uuid.UUID         `json:"project_id"`
	Content            string             `json:"content"`
	ClientKind         string             `json:"client_kind"`
	Model              string             `json:"model"`
	CharCount          int32              `json:"char_count"`
	ResponseChars      int32              `json:"response_chars"`
	EstimatedTokensIn  int32              `json:"estimated_tokens_in"`
	EstimatedTokensOut int32              `json:"estimated_tokens_out"`
	CapturedAt         time.Time          `json:"captured_at"`
	TurnCompletedAt    pgtype.Timestamptz `json:"turn_completed_at"`
}

func (q *Queries) InsertPrompt(ctx context.Context, arg InsertPromptParams) (InsertPromptRow, error) {
	row := q.db.QueryRow(ctx, insertPrompt,
		arg.UserID,
		arg.ProjectID,
		arg.Content,
		arg.ClientKind,
		arg.Model,
		arg.CharCount,
		arg.EstimatedTokensIn,
	)
	var i InsertPromptRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Content,
		&i.ClientKind,
		&i.Model,
		&i.CharCount,
		&i.ResponseChars,
		&i.EstimatedTokensIn,
		&i.EstimatedTokensOut,
		&i.CapturedAt,
		&i.TurnCompletedAt,
	)
	return i, err
}

const listPrompts = `-- name: ListPrompts :many
SELECT id, user_id, project_id, content,
       COALESCE(client_kind,'')::text AS client_kind,
       COALESCE(model,'')::text AS model,
       char_count, response_chars, estimated_tokens_in, estimated_tokens_out,
       captured_at, turn_completed_at
FROM prompt_captured
WHERE ($1::uuid IS NULL OR project_id = $1::uuid)
  AND ($2::uuid IS NULL OR user_id = $2::uuid)
ORDER BY captured_at DESC
LIMIT $4::int
OFFSET $3::int
`

type ListPromptsParams struct {
	ProjectID    *uuid.UUID `json:"project_id"`
	UserID       *uuid.UUID `json:"user_id"`
	ResultOffset int32      `json:"result_offset"`
	ResultLimit  int32      `json:"result_limit"`
}

type ListPromptsRow struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	ProjectID          *uuid.UUID         `json:"project_id"`
	Content            string             `json:"content"`
	ClientKind         string             `json:"client_kind"`
	Model              string             `json:"model"`
	CharCount          int32              `json:"char_count"`
	ResponseChars      int32              `json:"response_chars"`
	EstimatedTokensIn  int32              `json:"estimated_tokens_in"`
	EstimatedTokensOut int32              `json:"estimated_tokens_out"`
	CapturedAt         time.Time          `json:"captured_at"`
	TurnCompletedAt    pgtype.Timestamptz `json:"turn_completed_at"`
}

func (q *Queries) ListPrompts(ctx context.Context, arg ListPromptsParams) ([]ListPromptsRow, error) {
	rows, err := q.db.Query(ctx, listPrompts,
		arg.ProjectID,
		arg.UserID,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromptsRow
	for rows.Next() {
		var i ListPromptsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Content,
			&i.ClientKind,
			&i.Model,
			&i.CharCount,
			&i.ResponseChars,
			&i.EstimatedTokensIn,
			&i.EstimatedTokensOut,
			&i.CapturedAt,
			&i.TurnCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeByProject = `-- name: SummarizeByProject :one
SELECT COUNT(*)::int AS turns,
       COALESCE(SUM(estimated_tokens_in),0)::bigint AS estimated_tokens_in,
       COALESCE(SUM(estimated_tokens_out),0)::bigint AS estimated_tokens_out,
       COALESCE(SUM(char_count + response_chars),0)::bigint AS total_chars
FROM prompt_captured WHERE project_id = $1
`

type SummarizeByProjectRow struct {
	Turns              int32 `json:"turns"`
	EstimatedTokensIn  int64 `json:"estimated_tokens_in"`
	EstimatedTokensOut int64 `json:"estimated_tokens_out"`
	TotalChars         int64 `json:"total_chars"`
}

func (q *Queries) SummarizeByProject(ctx context.Context, projectID *uuid.UUID) (SummarizeByProjectRow, error) {
	row := q.db.QueryRow(ctx, summarizeByProject, projectID)
	var i SummarizeByProjectRow
	err := row.Scan(
		&i.Turns,
		&i.EstimatedTokensIn,
		&i.EstimatedTokensOut,
		&i.TotalChars,
	)
	return i, err
}
