// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package ticketdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkLinkExternalByID = `-- name: BulkLinkExternalByID :execrows
UPDATE project_tickets
SET external_provider    = $1,
    external_id          = NULLIF($2::text, ''),
    external_url         = NULLIF($3::text, ''),
    external_synced_at   = NOW()
WHERE id = $4 AND deleted_at IS NULL
`

type BulkLinkExternalByIDParams struct {
	ExternalProvider *string   `json:"external_provider"`
	ExternalID       string    `json:"external_id"`
	ExternalUrl      string    `json:"external_url"`
	ID               uuid.UUID `json:"id"`
}

func (q *Queries) BulkLinkExternalByID(ctx context.Context, arg BulkLinkExternalByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkLinkExternalByID,
		arg.ExternalProvider,
		arg.ExternalID,
		arg.ExternalUrl,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimTicket = `-- name: ClaimTicket :one
UPDATE project_tickets
SET locked_by    = $1,
    locked_until = NOW() + ($2::int * INTERVAL '1 minute'),
    version      = version + 1
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, project_id, client_id, key, number,
  title, COALESCE(description_md, '') AS description_md,
  issue_type, status, priority,
  assignee_id, reporter_id, labels,
  COALESCE(external_provider, '') AS external_provider,
  COALESCE(external_id, '') AS external_id,
  COALESCE(external_url, '') AS external_url,
  external_synced_at,
  parent_id, linked_issue_id, estimated_hours, actual_hours,
  due_date, started_at, completed_at,
  locked_by, locked_until, version,
  created_at, updated_at, deleted_at
`

type ClaimTicketParams struct {
	LockedBy   *uuid.UUID `json:"locked_by"`
	TtlMinutes int32      `json:"ttl_minutes"`
	ID         uuid.UUID  `json:"id"`
}

type ClaimTicketRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	ClientID         *uuid.UUID         `json:"client_id"`
	Key              string             `json:"key"`
	Number           int32              `json:"number"`
	Title            string             `json:"title"`
	DescriptionMd    string             `json:"description_md"`
	IssueType        string             `json:"issue_type"`
	Status           string             `json:"status"`
	Priority         string             `json:"priority"`
	AssigneeID       *uuid.UUID         `json:"assignee_id"`
	ReporterID       uuid.UUID          `json:"reporter_id"`
	Labels           []string           `json:"labels"`
	ExternalProvider string             `json:"external_provider"`
	ExternalID       string             `json:"external_id"`
	ExternalUrl      string             `json:"external_url"`
	ExternalSyncedAt pgtype.Timestamptz `json:"external_synced_at"`
	ParentID         *uuid.UUID         `json:"parent_id"`
	LinkedIssueID    *uuid.UUID         `json:"linked_issue_id"`
	EstimatedHours   pgtype.Numeric     `json:"estimated_hours"`
	ActualHours      pgtype.Numeric     `json:"actual_hours"`
	DueDate          pgtype.Date        `json:"due_date"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	LockedBy         *uuid.UUID         `json:"locked_by"`
	LockedUntil      pgtype.Timestamptz `json:"locked_until"`
	Version          int32              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ClaimTicket(ctx context.Context, arg ClaimTicketParams) (ClaimTicketRow, error) {
	row := q.db.QueryRow(ctx, claimTicket, arg.LockedBy, arg.TtlMinutes, arg.ID)
	var i ClaimTicketRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Key,
		&i.Number,
		&i.Title,
		&i.DescriptionMd,
		&i.IssueType,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Labels,
		&i.ExternalProvider,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ExternalSyncedAt,
		&i.ParentID,
		&i.LinkedIssueID,
		&i.EstimatedHours,
		&i.ActualHours,
		&i.DueDate,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findTicketByExternal = `-- name: FindTicketByExternal :one
SELECT id, project_id, client_id, key, number,
  title, COALESCE(description_md, '') AS description_md,
  issue_type, status, priority,
  assignee_id, reporter_id, labels,
  COALESCE(external_provider, '') AS external_provider,
  COALESCE(external_id, '') AS external_id,
  COALESCE(external_url, '') AS external_url,
  external_synced_at,
  parent_id, linked_issue_id, estimated_hours, actual_hours,
  due_date, started_at, completed_at,
  locked_by, locked_until, version,
  created_at, updated_at, deleted_at
FROM project_tickets
WHERE external_provider = $1
  AND external_id = $2
  AND deleted_at IS NULL
LIMIT 1
`

type FindTicketByExternalParams struct {
	ExternalProvider *string `json:"external_provider"`
	ExternalID       *string `json:"external_id"`
}

type FindTicketByExternalRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	ClientID         *uuid.UUID         `json:"client_id"`
	Key              string             `json:"key"`
	Number           int32              `json:"number"`
	Title            string             `json:"title"`
	DescriptionMd    string             `json:"description_md"`
	IssueType        string             `json:"issue_type"`
	Status           string             `json:"status"`
	Priority         string             `json:"priority"`
	AssigneeID       *uuid.UUID         `json:"assignee_id"`
	ReporterID       uuid.UUID          `json:"reporter_id"`
	Labels           []string           `json:"labels"`
	ExternalProvider string             `json:"external_provider"`
	ExternalID       string             `json:"external_id"`
	ExternalUrl      string             `json:"external_url"`
	ExternalSyncedAt pgtype.Timestamptz `json:"external_synced_at"`
	ParentID         *uuid.UUID         `json:"parent_id"`
	LinkedIssueID    *uuid.UUID         `json:"linked_issue_id"`
	EstimatedHours   pgtype.Numeric     `json:"estimated_hours"`
	ActualHours      pgtype.Numeric     `json:"actual_hours"`
	DueDate          pgtype.Date        `json:"due_date"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	LockedBy         *uuid.UUID         `json:"locked_by"`
	LockedUntil      pgtype.Timestamptz `json:"locked_until"`
	Version          int32              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) FindTicketByExternal(ctx context.Context, arg FindTicketByExternalParams) (FindTicketByExternalRow, error) {
	row := q.db.QueryRow(ctx, findTicketByExternal, arg.ExternalProvider, arg.ExternalID)
	var i FindTicketByExternalRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Key,
		&i.Number,
		&i.Title,
		&i.DescriptionMd,
		&i.IssueType,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Labels,
		&i.ExternalProvider,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ExternalSyncedAt,
		&i.ParentID,
		&i.LinkedIssueID,
		&i.EstimatedHours,
		&i.ActualHours,
		&i.DueDate,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, project_id, client_id, key, number,
  title, COALESCE(description_md, '') AS description_md,
  issue_type, status, priority,
  assignee_id, reporter_id, labels,
  COALESCE(external_provider, '') AS external_provider,
  COALESCE(external_id, '') AS external_id,
  COALESCE(external_url, '') AS external_url,
  external_synced_at,
  parent_id, linked_issue_id, estimated_hours, actual_hours,
  due_date, started_at, completed_at,
  locked_by, locked_until, version,
  created_at, updated_at, deleted_at
FROM project_tickets
WHERE id = $1 AND deleted_at IS NULL
`

type GetTicketByIDRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	ClientID         *uuid.UUID         `json:"client_id"`
	Key              string             `json:"key"`
	Number           int32              `json:"number"`
	Title            string             `json:"title"`
	DescriptionMd    string             `json:"description_md"`
	IssueType        string             `json:"issue_type"`
	Status           string             `json:"status"`
	Priority         string             `json:"priority"`
	AssigneeID       *uuid.UUID         `json:"assignee_id"`
	ReporterID       uuid.UUID          `json:"reporter_id"`
	Labels           []string           `json:"labels"`
	ExternalProvider string             `json:"external_provider"`
	ExternalID       string             `json:"external_id"`
	ExternalUrl      string             `json:"external_url"`
	ExternalSyncedAt pgtype.Timestamptz `json:"external_synced_at"`
	ParentID         *uuid.UUID         `json:"parent_id"`
	LinkedIssueID    *uuid.UUID         `json:"linked_issue_id"`
	EstimatedHours   pgtype.Numeric     `json:"estimated_hours"`
	ActualHours      pgtype.Numeric     `json:"actual_hours"`
	DueDate          pgtype.Date        `json:"due_date"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	LockedBy         *uuid.UUID         `json:"locked_by"`
	LockedUntil      pgtype.Timestamptz `json:"locked_until"`
	Version          int32              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetTicketByID(ctx context.Context, id uuid.UUID) (GetTicketByIDRow, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i GetTicketByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Key,
		&i.Number,
		&i.Title,
		&i.DescriptionMd,
		&i.IssueType,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Labels,
		&i.ExternalProvider,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ExternalSyncedAt,
		&i.ParentID,
		&i.LinkedIssueID,
		&i.EstimatedHours,
		&i.ActualHours,
		&i.DueDate,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTicketByKey = `-- name: GetTicketByKey :one
SELECT id, project_id, client_id, key, number,
  title, COALESCE(description_md, '') AS description_md,
  issue_type, status, priority,
  assignee_id, reporter_id, labels,
  COALESCE(external_provider, '') AS external_provider,
  COALESCE(external_id, '') AS external_id,
  COALESCE(external_url, '') AS external_url,
  external_synced_at,
  parent_id, linked_issue_id, estimated_hours, actual_hours,
  due_date, started_at, completed_at,
  locked_by, locked_until, version,
  created_at, updated_at, deleted_at
FROM project_tickets
WHERE project_id = $1
  AND key = $2
  AND deleted_at IS NULL
`

type GetTicketByKeyParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Key       string    `json:"key"`
}

type GetTicketByKeyRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	ClientID         *uuid.UUID         `json:"client_id"`
	Key              string             `json:"key"`
	Number           int32              `json:"number"`
	Title            string             `json:"title"`
	DescriptionMd    string             `json:"description_md"`
	IssueType        string             `json:"issue_type"`
	Status           string             `json:"status"`
	Priority         string             `json:"priority"`
	AssigneeID       *uuid.UUID         `json:"assignee_id"`
	ReporterID       uuid.UUID          `json:"reporter_id"`
	Labels           []string           `json:"labels"`
	ExternalProvider string             `json:"external_provider"`
	ExternalID       string             `json:"external_id"`
	ExternalUrl      string             `json:"external_url"`
	ExternalSyncedAt pgtype.Timestamptz `json:"external_synced_at"`
	ParentID         *uuid.UUID         `json:"parent_id"`
	LinkedIssueID    *uuid.UUID         `json:"linked_issue_id"`
	EstimatedHours   pgtype.Numeric     `json:"estimated_hours"`
	ActualHours      pgtype.Numeric     `json:"actual_hours"`
	DueDate          pgtype.Date        `json:"due_date"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	LockedBy         *uuid.UUID         `json:"locked_by"`
	LockedUntil      pgtype.Timestamptz `json:"locked_until"`
	Version          int32              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetTicketByKey(ctx context.Context, arg GetTicketByKeyParams) (GetTicketByKeyRow, error) {
	row := q.db.QueryRow(ctx, getTicketByKey, arg.ProjectID, arg.Key)
	var i GetTicketByKeyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Key,
		&i.Number,
		&i.Title,
		&i.DescriptionMd,
		&i.IssueType,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Labels,
		&i.ExternalProvider,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ExternalSyncedAt,
		&i.ParentID,
		&i.LinkedIssueID,
		&i.EstimatedHours,
		&i.ActualHours,
		&i.DueDate,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTicketIDByKey = `-- name: GetTicketIDByKey :one
SELECT id FROM project_tickets
WHERE project_id = $1
  AND key = $2
  AND deleted_at IS NULL
`

type GetTicketIDByKeyParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Key       string    `json:"key"`
}

func (q *Queries) GetTicketIDByKey(ctx context.Context, arg GetTicketIDByKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTicketIDByKey, arg.ProjectID, arg.Key)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertComment = `-- name: InsertComment :one
INSERT INTO project_ticket_comments (ticket_id, author_id, body_md)
VALUES ($1, $2, $3)
RETURNING id, ticket_id, author_id, body_md,
  COALESCE(external_id, '') AS external_id,
  created_at, updated_at, deleted_at
`

type InsertCommentParams struct {
	TicketID uuid.UUID `json:"ticket_id"`
	AuthorID uuid.UUID `json:"author_id"`
	BodyMd   string    `json:"body_md"`
}

type InsertCommentRow struct {
	ID         uuid.UUID          `json:"id"`
	TicketID   uuid.UUID          `json:"ticket_id"`
	AuthorID   uuid.UUID          `json:"author_id"`
	BodyMd     string             `json:"body_md"`
	ExternalID string             `json:"external_id"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (InsertCommentRow, error) {
	row := q.db.QueryRow(ctx, insertComment, arg.TicketID, arg.AuthorID, arg.BodyMd)
	var i InsertCommentRow
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorID,
		&i.BodyMd,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertStatusHistory = `-- name: InsertStatusHistory :exec
INSERT INTO project_ticket_status_history
  (ticket_id, from_status, to_status, changed_by, note)
VALUES ($1, $2, $3, $4, $5)
`

type InsertStatusHistoryParams struct {
	TicketID   uuid.UUID `json:"ticket_id"`
	FromStatus *string   `json:"from_status"`
	ToStatus   string    `json:"to_status"`
	ChangedBy  uuid.UUID `json:"changed_by"`
	Note       *string   `json:"note"`
}

func (q *Queries) InsertStatusHistory(ctx context.Context, arg InsertStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, insertStatusHistory,
		arg.TicketID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedBy,
		arg.Note,
	)
	return err
}

const insertTicket = `-- name: InsertTicket :one
INSERT INTO project_tickets
  (project_id, client_id, key, number,
   title, description_md, issue_type, priority,
   assignee_id, reporter_id, labels, parent_id,
   estimated_hours, due_date,
   external_provider, external_id, external_url, external_synced_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  NULLIF($6::text, ''),
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  NULLIF($15::text, ''),
  NULLIF($16::text, ''),
  NULLIF($17::text, ''),
  $18
)
RETURNING id, project_id, client_id, key, number,
  title, COALESCE(description_md, '') AS description_md,
  issue_type, status, priority,
  assignee_id, reporter_id, labels,
  COALESCE(external_provider, '') AS external_provider,
  COALESCE(external_id, '') AS external_id,
  COALESCE(external_url, '') AS external_url,
  external_synced_at,
  parent_id, linked_issue_id, estimated_hours, actual_hours,
  due_date, started_at, completed_at,
  locked_by, locked_until, version,
  created_at, updated_at, deleted_at
`

type InsertTicketParams struct {
	ProjectID        uuid.UUID          `json:"project_id"`
	ClientID         *uuid.UUID         `json:"client_id"`
	Key              string             `json:"key"`
	Number           int32              `json:"number"`
	Title            string             `json:"title"`
	DescriptionMd    string             `json:"description_md"`
	IssueType        string             `json:"issue_type"`
	Priority         string             `json:"priority"`
	AssigneeID       *uuid.UUID         `json:"assignee_id"`
	ReporterID       uuid.UUID          `json:"reporter_id"`
	Labels           []string           `json:"labels"`
	ParentID         *uuid.UUID         `json:"parent_id"`
	EstimatedHours   pgtype.Numeric     `json:"estimated_hours"`
	DueDate          pgtype.Date        `json:"due_date"`
	ExternalProvider string             `json:"external_provider"`
	ExternalID       string             `json:"external_id"`
	ExternalUrl      string             `json:"external_url"`
	ExternalSyncedAt pgtype.Timestamptz `json:"external_synced_at"`
}

type InsertTicketRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	ClientID         *uuid.UUID         `json:"client_id"`
	Key              string             `json:"key"`
	Number           int32              `json:"number"`
	Title            string             `json:"title"`
	DescriptionMd    string             `json:"description_md"`
	IssueType        string             `json:"issue_type"`
	Status           string             `json:"status"`
	Priority         string             `json:"priority"`
	AssigneeID       *uuid.UUID         `json:"assignee_id"`
	ReporterID       uuid.UUID          `json:"reporter_id"`
	Labels           []string           `json:"labels"`
	ExternalProvider string             `json:"external_provider"`
	ExternalID       string             `json:"external_id"`
	ExternalUrl      string             `json:"external_url"`
	ExternalSyncedAt pgtype.Timestamptz `json:"external_synced_at"`
	ParentID         *uuid.UUID         `json:"parent_id"`
	LinkedIssueID    *uuid.UUID         `json:"linked_issue_id"`
	EstimatedHours   pgtype.Numeric     `json:"estimated_hours"`
	ActualHours      pgtype.Numeric     `json:"actual_hours"`
	DueDate          pgtype.Date        `json:"due_date"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	LockedBy         *uuid.UUID         `json:"locked_by"`
	LockedUntil      pgtype.Timestamptz `json:"locked_until"`
	Version          int32              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) (InsertTicketRow, error) {
	row := q.db.QueryRow(ctx, insertTicket,
		arg.ProjectID,
		arg.ClientID,
		arg.Key,
		arg.Number,
		arg.Title,
		arg.DescriptionMd,
		arg.IssueType,
		arg.Priority,
		arg.AssigneeID,
		arg.ReporterID,
		arg.Labels,
		arg.ParentID,
		arg.EstimatedHours,
		arg.DueDate,
		arg.ExternalProvider,
		arg.ExternalID,
		arg.ExternalUrl,
		arg.ExternalSyncedAt,
	)
	var i InsertTicketRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Key,
		&i.Number,
		&i.Title,
		&i.DescriptionMd,
		&i.IssueType,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Labels,
		&i.ExternalProvider,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ExternalSyncedAt,
		&i.ParentID,
		&i.LinkedIssueID,
		&i.EstimatedHours,
		&i.ActualHours,
		&i.DueDate,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const linkTicketExternal = `-- name: LinkTicketExternal :one
UPDATE project_tickets
SET external_provider    = NULLIF($1::text, ''),
    external_id          = NULLIF($2::text, ''),
    external_url         = NULLIF($3::text, ''),
    external_synced_at   = NOW()
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, project_id, client_id, key, number,
  title, COALESCE(description_md, '') AS description_md,
  issue_type, status, priority,
  assignee_id, reporter_id, labels,
  COALESCE(external_provider, '') AS external_provider,
  COALESCE(external_id, '') AS external_id,
  COALESCE(external_url, '') AS external_url,
  external_synced_at,
  parent_id, linked_issue_id, estimated_hours, actual_hours,
  due_date, started_at, completed_at,
  locked_by, locked_until, version,
  created_at, updated_at, deleted_at
`

type LinkTicketExternalParams struct {
	ExternalProvider string    `json:"external_provider"`
	ExternalID       string    `json:"external_id"`
	ExternalUrl      string    `json:"external_url"`
	ID               uuid.UUID `json:"id"`
}

type LinkTicketExternalRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	ClientID         *uuid.UUID         `json:"client_id"`
	Key              string             `json:"key"`
	Number           int32              `json:"number"`
	Title            string             `json:"title"`
	DescriptionMd    string             `json:"description_md"`
	IssueType        string             `json:"issue_type"`
	Status           string             `json:"status"`
	Priority         string             `json:"priority"`
	AssigneeID       *uuid.UUID         `json:"assignee_id"`
	ReporterID       uuid.UUID          `json:"reporter_id"`
	Labels           []string           `json:"labels"`
	ExternalProvider string             `json:"external_provider"`
	ExternalID       string             `json:"external_id"`
	ExternalUrl      string             `json:"external_url"`
	ExternalSyncedAt pgtype.Timestamptz `json:"external_synced_at"`
	ParentID         *uuid.UUID         `json:"parent_id"`
	LinkedIssueID    *uuid.UUID         `json:"linked_issue_id"`
	EstimatedHours   pgtype.Numeric     `json:"estimated_hours"`
	ActualHours      pgtype.Numeric     `json:"actual_hours"`
	DueDate          pgtype.Date        `json:"due_date"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	LockedBy         *uuid.UUID         `json:"locked_by"`
	LockedUntil      pgtype.Timestamptz `json:"locked_until"`
	Version          int32              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) LinkTicketExternal(ctx context.Context, arg LinkTicketExternalParams) (LinkTicketExternalRow, error) {
	row := q.db.QueryRow(ctx, linkTicketExternal,
		arg.ExternalProvider,
		arg.ExternalID,
		arg.ExternalUrl,
		arg.ID,
	)
	var i LinkTicketExternalRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Key,
		&i.Number,
		&i.Title,
		&i.DescriptionMd,
		&i.IssueType,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Labels,
		&i.ExternalProvider,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ExternalSyncedAt,
		&i.ParentID,
		&i.LinkedIssueID,
		&i.EstimatedHours,
		&i.ActualHours,
		&i.DueDate,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const linkTicketIssue = `-- name: LinkTicketIssue :one
UPDATE project_tickets
SET linked_issue_id = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, project_id, client_id, key, number,
  title, COALESCE(description_md, '') AS description_md,
  issue_type, status, priority,
  assignee_id, reporter_id, labels,
  COALESCE(external_provider, '') AS external_provider,
  COALESCE(external_id, '') AS external_id,
  COALESCE(external_url, '') AS external_url,
  external_synced_at,
  parent_id, linked_issue_id, estimated_hours, actual_hours,
  due_date, started_at, completed_at,
  locked_by, locked_until, version,
  created_at, updated_at, deleted_at
`

type LinkTicketIssueParams struct {
	LinkedIssueID *uuid.UUID `json:"linked_issue_id"`
	ID            uuid.UUID  `json:"id"`
}

type LinkTicketIssueRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	ClientID         *uuid.UUID         `json:"client_id"`
	Key              string             `json:"key"`
	Number           int32              `json:"number"`
	Title            string             `json:"title"`
	DescriptionMd    string             `json:"description_md"`
	IssueType        string             `json:"issue_type"`
	Status           string             `json:"status"`
	Priority         string             `json:"priority"`
	AssigneeID       *uuid.UUID         `json:"assignee_id"`
	ReporterID       uuid.UUID          `json:"reporter_id"`
	Labels           []string           `json:"labels"`
	ExternalProvider string             `json:"external_provider"`
	ExternalID       string             `json:"external_id"`
	ExternalUrl      string             `json:"external_url"`
	ExternalSyncedAt pgtype.Timestamptz `json:"external_synced_at"`
	ParentID         *uuid.UUID         `json:"parent_id"`
	LinkedIssueID    *uuid.UUID         `json:"linked_issue_id"`
	EstimatedHours   pgtype.Numeric     `json:"estimated_hours"`
	ActualHours      pgtype.Numeric     `json:"actual_hours"`
	DueDate          pgtype.Date        `json:"due_date"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	LockedBy         *uuid.UUID         `json:"locked_by"`
	LockedUntil      pgtype.Timestamptz `json:"locked_until"`
	Version          int32              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) LinkTicketIssue(ctx context.Context, arg LinkTicketIssueParams) (LinkTicketIssueRow, error) {
	row := q.db.QueryRow(ctx, linkTicketIssue, arg.LinkedIssueID, arg.ID)
	var i LinkTicketIssueRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Key,
		&i.Number,
		&i.Title,
		&i.DescriptionMd,
		&i.IssueType,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Labels,
		&i.ExternalProvider,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ExternalSyncedAt,
		&i.ParentID,
		&i.LinkedIssueID,
		&i.EstimatedHours,
		&i.ActualHours,
		&i.DueDate,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT id, ticket_id, author_id, body_md,
  COALESCE(external_id, '') AS external_id,
  created_at, updated_at, deleted_at
FROM project_ticket_comments
WHERE ticket_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListCommentsRow struct {
	ID         uuid.UUID          `json:"id"`
	TicketID   uuid.UUID          `json:"ticket_id"`
	AuthorID   uuid.UUID          `json:"author_id"`
	BodyMd     string             `json:"body_md"`
	ExternalID string             `json:"external_id"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListComments(ctx context.Context, ticketID uuid.UUID) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.AuthorID,
			&i.BodyMd,
			&i.ExternalID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusHistory = `-- name: ListStatusHistory :many
SELECT id, ticket_id,
  COALESCE(from_status, '') AS from_status,
  to_status, changed_by,
  COALESCE(note, '') AS note,
  changed_at
FROM project_ticket_status_history
WHERE ticket_id = $1
ORDER BY changed_at ASC
`

type ListStatusHistoryRow struct {
	ID         uuid.UUID `json:"id"`
	TicketID   uuid.UUID `json:"ticket_id"`
	FromStatus string    `json:"from_status"`
	ToStatus   string    `json:"to_status"`
	ChangedBy  uuid.UUID `json:"changed_by"`
	Note       string    `json:"note"`
	ChangedAt  time.Time `json:"changed_at"`
}

func (q *Queries) ListStatusHistory(ctx context.Context, ticketID uuid.UUID) ([]ListStatusHistoryRow, error) {
	rows, err := q.db.Query(ctx, listStatusHistory, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatusHistoryRow
	for rows.Next() {
		var i ListStatusHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedBy,
			&i.Note,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTicket = `-- name: ReleaseTicket :one
UPDATE project_tickets
SET locked_by    = NULL,
    locked_until = NULL,
    version      = version + 1
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, client_id, key, number,
  title, COALESCE(description_md, '') AS description_md,
  issue_type, status, priority,
  assignee_id, reporter_id, labels,
  COALESCE(external_provider, '') AS external_provider,
  COALESCE(external_id, '') AS external_id,
  COALESCE(external_url, '') AS external_url,
  external_synced_at,
  parent_id, linked_issue_id, estimated_hours, actual_hours,
  due_date, started_at, completed_at,
  locked_by, locked_until, version,
  created_at, updated_at, deleted_at
`

type ReleaseTicketRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	ClientID         *uuid.UUID         `json:"client_id"`
	Key              string             `json:"key"`
	Number           int32              `json:"number"`
	Title            string             `json:"title"`
	DescriptionMd    string             `json:"description_md"`
	IssueType        string             `json:"issue_type"`
	Status           string             `json:"status"`
	Priority         string             `json:"priority"`
	AssigneeID       *uuid.UUID         `json:"assignee_id"`
	ReporterID       uuid.UUID          `json:"reporter_id"`
	Labels           []string           `json:"labels"`
	ExternalProvider string             `json:"external_provider"`
	ExternalID       string             `json:"external_id"`
	ExternalUrl      string             `json:"external_url"`
	ExternalSyncedAt pgtype.Timestamptz `json:"external_synced_at"`
	ParentID         *uuid.UUID         `json:"parent_id"`
	LinkedIssueID    *uuid.UUID         `json:"linked_issue_id"`
	EstimatedHours   pgtype.Numeric     `json:"estimated_hours"`
	ActualHours      pgtype.Numeric     `json:"actual_hours"`
	DueDate          pgtype.Date        `json:"due_date"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	LockedBy         *uuid.UUID         `json:"locked_by"`
	LockedUntil      pgtype.Timestamptz `json:"locked_until"`
	Version          int32              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ReleaseTicket(ctx context.Context, id uuid.UUID) (ReleaseTicketRow, error) {
	row := q.db.QueryRow(ctx, releaseTicket, id)
	var i ReleaseTicketRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Key,
		&i.Number,
		&i.Title,
		&i.DescriptionMd,
		&i.IssueType,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Labels,
		&i.ExternalProvider,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.ExternalSyncedAt,
		&i.ParentID,
		&i.LinkedIssueID,
		&i.EstimatedHours,
		&i.ActualHours,
		&i.DueDate,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteTicket = `-- name: SoftDeleteTicket :execrows
UPDATE project_tickets
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTicket(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTicket, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ticketNextNumber = `-- name: TicketNextNumber :one
SELECT COALESCE(MAX(number), 0) + 1
FROM project_tickets
WHERE project_id = $1
`

func (q *Queries) TicketNextNumber(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, ticketNextNumber, projectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const unlinkTicketExternal = `-- name: UnlinkTicketExternal :execrows
UPDATE project_tickets
SET external_provider = NULL, external_id = NULL,
    external_url = NULL, external_synced_at = NULL
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UnlinkTicketExternal(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkTicketExternal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
