// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package skillsuggestionsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const judgeListActiveSkills = `-- name: JudgeListActiveSkills :many

SELECT s.id, s.slug, s.name,
       COALESCE(s.description, '')::text AS description,
       COALESCE(s.content, '')::text     AS content,
       s.seed_managed
FROM skills s
WHERE s.deleted_at IS NULL
  AND s.superseded_by IS NULL
  AND s.proposed = false
ORDER BY s.created_at ASC
LIMIT $2::int OFFSET $1::int
`

type JudgeListActiveSkillsParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

type JudgeListActiveSkillsRow struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Content     string    `json:"content"`
	SeedManaged bool      `json:"seed_managed"`
}

// ============================================================
// Lectura para el JUDGE/CRON (HU-52.3). Solo SELECT: el cron arma el contexto
// (skill + senales 30d + similares lexicos) y pide sugerencias al LLM; NUNCA muta
// skills (el Apply, accion humana, hace eso). Self-contained: agrega
// skill_metrics_daily + skill_feedback + skill_executions en SQL para no acoplar
// el cron a los services de metrics/feedback (cada uno usa su propia clave).
// ============================================================
// Skills candidatos a auditar: vivos (deleted_at IS NULL), no superseded
// (superseded_by IS NULL) y visibles (proposed=false). Devuelve lo minimo que el
// judge necesita para razonar. Paginado para acotar el batch (rate_limit).
func (q *Queries) JudgeListActiveSkills(ctx context.Context, arg JudgeListActiveSkillsParams) ([]JudgeListActiveSkillsRow, error) {
	rows, err := q.db.Query(ctx, judgeListActiveSkills, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JudgeListActiveSkillsRow
	for rows.Next() {
		var i JudgeListActiveSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Content,
			&i.SeedManaged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const judgeSimilarSkills = `-- name: JudgeSimilarSkills :many
SELECT s.slug, s.name,
       ts_rank(s.description_tsv, q)::float8 AS score
FROM skills s, plainto_tsquery('spanish', $1) AS q
WHERE s.deleted_at IS NULL
  AND s.proposed = false
  AND s.id <> $2
  AND s.description_tsv @@ q
ORDER BY score DESC
LIMIT $3::int
`

type JudgeSimilarSkillsParams struct {
	QueryText   string    `json:"query_text"`
	SelfID      uuid.UUID `json:"self_id"`
	ResultLimit int32     `json:"result_limit"`
}

type JudgeSimilarSkillsRow struct {
	Slug  string  `json:"slug"`
	Name  string  `json:"name"`
	Score float64 `json:"score"`
}

// Top-N skills similares (similitud LEXICA via description_tsv, SIN embeddings) al
// texto de busqueda (name + description del skill objetivo), excluyendo el propio
// skill. Reusa el index GIN skills_description_tsv_idx. proposed=false / vivos.
func (q *Queries) JudgeSimilarSkills(ctx context.Context, arg JudgeSimilarSkillsParams) ([]JudgeSimilarSkillsRow, error) {
	rows, err := q.db.Query(ctx, judgeSimilarSkills, arg.QueryText, arg.SelfID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JudgeSimilarSkillsRow
	for rows.Next() {
		var i JudgeSimilarSkillsRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const judgeSkillSignals = `-- name: JudgeSkillSignals :one
WITH m AS (
    SELECT
        COALESCE(SUM(invocations_count), 0)::bigint AS invocations,
        COALESCE(SUM(failure_count), 0)::bigint     AS failures,
        COALESCE(SUM(avg_duration_ms::bigint * invocations_count), 0)::bigint AS dur_weighted
    FROM skill_metrics_daily
    WHERE skill_metrics_daily.skill_id = $1
      AND day >= (CURRENT_DATE - 30)
), f AS (
    SELECT COUNT(*)::bigint AS negatives
    FROM skill_feedback
    WHERE skill_slug = $2
      AND rating = -1
      AND created_at >= (NOW() - INTERVAL '30 days')
), e AS (
    SELECT MAX(created_at) AS last_use
    FROM skill_executions
    WHERE skill_executions.skill_id = $3
      AND created_at >= (NOW() - INTERVAL '90 days')
)
SELECT
    m.invocations::bigint AS invocations_30d,
    m.failures::bigint    AS failures_30d,
    m.dur_weighted::bigint AS duration_weighted_30d,
    f.negatives::bigint   AS negative_feedback_30d,
    CASE
        WHEN e.last_use IS NULL THEN -1
        ELSE (CURRENT_DATE - e.last_use::date)
    END::int AS days_since_last_use
FROM m, f, e
`

type JudgeSkillSignalsParams struct {
	MetricsSkillID uuid.UUID `json:"metrics_skill_id"`
	SkillSlug      *string   `json:"skill_slug"`
	ExecSkillID    uuid.UUID `json:"exec_skill_id"`
}

type JudgeSkillSignalsRow struct {
	Invocations30d      int64 `json:"invocations_30d"`
	Failures30d         int64 `json:"failures_30d"`
	DurationWeighted30d int64 `json:"duration_weighted_30d"`
	NegativeFeedback30d int64 `json:"negative_feedback_30d"`
	DaysSinceLastUse    int32 `json:"days_since_last_use"`
}

// Senales agregadas de UN skill para el judge:
//   - invocations_per_day: invocaciones 30d / 30.
//   - failure_rate: % de fallos 30d (failure/invocations*100), 0 si sin datos.
//   - avg_duration_seconds: promedio ponderado de avg_duration_ms 30d / 1000.
//   - negative_feedback: votos -1 en skill_feedback 30d (por slug).
//   - days_since_last_use: dias desde la ultima skill_execution (en 90d). -1 si
//     no hubo ninguna en 90d (candidato a ARCHIVE).
//
// Todo se computa en una sola pasada con subselects acotados por ventana.
func (q *Queries) JudgeSkillSignals(ctx context.Context, arg JudgeSkillSignalsParams) (JudgeSkillSignalsRow, error) {
	row := q.db.QueryRow(ctx, judgeSkillSignals, arg.MetricsSkillID, arg.SkillSlug, arg.ExecSkillID)
	var i JudgeSkillSignalsRow
	err := row.Scan(
		&i.Invocations30d,
		&i.Failures30d,
		&i.DurationWeighted30d,
		&i.NegativeFeedback30d,
		&i.DaysSinceLastUse,
	)
	return i, err
}

const suggestionApprove = `-- name: SuggestionApprove :one
UPDATE skill_suggestions
SET status = 'approved', reviewed_by = $1, reviewed_at = NOW()
WHERE id = $2 AND status = 'pending'
RETURNING id, skill_slug, kind, payload, rationale, llm_model,
          llm_confidence::float8 AS llm_confidence, status, reviewed_by,
          reviewed_at, applied_at, applied_changes, created_at
`

type SuggestionApproveParams struct {
	ReviewedBy *uuid.UUID `json:"reviewed_by"`
	ID         uuid.UUID  `json:"id"`
}

type SuggestionApproveRow struct {
	ID             uuid.UUID          `json:"id"`
	SkillSlug      string             `json:"skill_slug"`
	Kind           string             `json:"kind"`
	Payload        []byte             `json:"payload"`
	Rationale      *string            `json:"rationale"`
	LlmModel       *string            `json:"llm_model"`
	LlmConfidence  float64            `json:"llm_confidence"`
	Status         string             `json:"status"`
	ReviewedBy     *uuid.UUID         `json:"reviewed_by"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt      pgtype.Timestamptz `json:"applied_at"`
	AppliedChanges []byte             `json:"applied_changes"`
	CreatedAt      time.Time          `json:"created_at"`
}

// Aprueba (pending -> approved). Guard optimista: solo si sigue pending. Si 0
// filas, ya fue revisada (concurrencia). reviewed_by/at = accion humana.
func (q *Queries) SuggestionApprove(ctx context.Context, arg SuggestionApproveParams) (SuggestionApproveRow, error) {
	row := q.db.QueryRow(ctx, suggestionApprove, arg.ReviewedBy, arg.ID)
	var i SuggestionApproveRow
	err := row.Scan(
		&i.ID,
		&i.SkillSlug,
		&i.Kind,
		&i.Payload,
		&i.Rationale,
		&i.LlmModel,
		&i.LlmConfidence,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.AppliedChanges,
		&i.CreatedAt,
	)
	return i, err
}

const suggestionCountPending = `-- name: SuggestionCountPending :one
SELECT COUNT(*)::bigint FROM skill_suggestions WHERE status = 'pending'
`

func (q *Queries) SuggestionCountPending(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, suggestionCountPending)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const suggestionCreate = `-- name: SuggestionCreate :one

INSERT INTO skill_suggestions (
    skill_slug, kind, payload, rationale, llm_model, llm_confidence, status
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    'pending'
)
ON CONFLICT (skill_slug, kind) WHERE status = 'pending' DO NOTHING
RETURNING id, skill_slug, kind, payload, rationale, llm_model,
          llm_confidence::float8 AS llm_confidence, status, reviewed_by,
          reviewed_at, applied_at, applied_changes, created_at
`

type SuggestionCreateParams struct {
	SkillSlug     string         `json:"skill_slug"`
	Kind          string         `json:"kind"`
	Payload       []byte         `json:"payload"`
	Rationale     *string        `json:"rationale"`
	LlmModel      *string        `json:"llm_model"`
	LlmConfidence pgtype.Numeric `json:"llm_confidence"`
}

type SuggestionCreateRow struct {
	ID             uuid.UUID          `json:"id"`
	SkillSlug      string             `json:"skill_slug"`
	Kind           string             `json:"kind"`
	Payload        []byte             `json:"payload"`
	Rationale      *string            `json:"rationale"`
	LlmModel       *string            `json:"llm_model"`
	LlmConfidence  float64            `json:"llm_confidence"`
	Status         string             `json:"status"`
	ReviewedBy     *uuid.UUID         `json:"reviewed_by"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt      pgtype.Timestamptz `json:"applied_at"`
	AppliedChanges []byte             `json:"applied_changes"`
	CreatedAt      time.Time          `json:"created_at"`
}

// HU-52.3 — skill_suggestions (LLM-as-judge + human-in-the-loop).
//
// El cron (judge) SOLO inserta pending (SuggestionCreate). El Apply muta skills
// y corre EXCLUSIVAMENTE por accion humana (approve -> apply). Todas las queries
// son self-contained de este paquete; las mutaciones de skills (linaje, soft
// delete, content) viven aca para que el Apply sea una sola transaccion (txctx).
// Inserta una sugerencia pending. ON CONFLICT contra el UNIQUE parcial
// (skill_slug, kind) WHERE status='pending' -> DO NOTHING (dedup). Si ya hay una
// pendiente identica, no devuelve fila (caller lo trata como "ya existe").
func (q *Queries) SuggestionCreate(ctx context.Context, arg SuggestionCreateParams) (SuggestionCreateRow, error) {
	row := q.db.QueryRow(ctx, suggestionCreate,
		arg.SkillSlug,
		arg.Kind,
		arg.Payload,
		arg.Rationale,
		arg.LlmModel,
		arg.LlmConfidence,
	)
	var i SuggestionCreateRow
	err := row.Scan(
		&i.ID,
		&i.SkillSlug,
		&i.Kind,
		&i.Payload,
		&i.Rationale,
		&i.LlmModel,
		&i.LlmConfidence,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.AppliedChanges,
		&i.CreatedAt,
	)
	return i, err
}

const suggestionGet = `-- name: SuggestionGet :one
SELECT id, skill_slug, kind, payload, rationale, llm_model,
       llm_confidence::float8 AS llm_confidence, status, reviewed_by,
       reviewed_at, applied_at, applied_changes, created_at
FROM skill_suggestions
WHERE id = $1
`

type SuggestionGetRow struct {
	ID             uuid.UUID          `json:"id"`
	SkillSlug      string             `json:"skill_slug"`
	Kind           string             `json:"kind"`
	Payload        []byte             `json:"payload"`
	Rationale      *string            `json:"rationale"`
	LlmModel       *string            `json:"llm_model"`
	LlmConfidence  float64            `json:"llm_confidence"`
	Status         string             `json:"status"`
	ReviewedBy     *uuid.UUID         `json:"reviewed_by"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt      pgtype.Timestamptz `json:"applied_at"`
	AppliedChanges []byte             `json:"applied_changes"`
	CreatedAt      time.Time          `json:"created_at"`
}

func (q *Queries) SuggestionGet(ctx context.Context, id uuid.UUID) (SuggestionGetRow, error) {
	row := q.db.QueryRow(ctx, suggestionGet, id)
	var i SuggestionGetRow
	err := row.Scan(
		&i.ID,
		&i.SkillSlug,
		&i.Kind,
		&i.Payload,
		&i.Rationale,
		&i.LlmModel,
		&i.LlmConfidence,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.AppliedChanges,
		&i.CreatedAt,
	)
	return i, err
}

const suggestionList = `-- name: SuggestionList :many
SELECT id, skill_slug, kind, payload, rationale, llm_model,
       llm_confidence::float8 AS llm_confidence, status, reviewed_by,
       reviewed_at, applied_at, applied_changes, created_at
FROM skill_suggestions
WHERE ($1::text = '' OR skill_slug = $1::text)
  AND ($2::text       = '' OR kind       = $2::text)
  AND ($3::text     = '' OR status     = $3::text)
ORDER BY created_at DESC
LIMIT $5::int OFFSET $4::int
`

type SuggestionListParams struct {
	SkillSlug    string `json:"skill_slug"`
	Kind         string `json:"kind"`
	Status       string `json:"status"`
	ResultOffset int32  `json:"result_offset"`
	ResultLimit  int32  `json:"result_limit"`
}

type SuggestionListRow struct {
	ID             uuid.UUID          `json:"id"`
	SkillSlug      string             `json:"skill_slug"`
	Kind           string             `json:"kind"`
	Payload        []byte             `json:"payload"`
	Rationale      *string            `json:"rationale"`
	LlmModel       *string            `json:"llm_model"`
	LlmConfidence  float64            `json:"llm_confidence"`
	Status         string             `json:"status"`
	ReviewedBy     *uuid.UUID         `json:"reviewed_by"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt      pgtype.Timestamptz `json:"applied_at"`
	AppliedChanges []byte             `json:"applied_changes"`
	CreatedAt      time.Time          `json:"created_at"`
}

// Lista con filtros opcionales (skill_slug, kind, status). Un filtro vacio
// (”) se ignora via el patron (arg = ” OR col = arg).
func (q *Queries) SuggestionList(ctx context.Context, arg SuggestionListParams) ([]SuggestionListRow, error) {
	rows, err := q.db.Query(ctx, suggestionList,
		arg.SkillSlug,
		arg.Kind,
		arg.Status,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestionListRow
	for rows.Next() {
		var i SuggestionListRow
		if err := rows.Scan(
			&i.ID,
			&i.SkillSlug,
			&i.Kind,
			&i.Payload,
			&i.Rationale,
			&i.LlmModel,
			&i.LlmConfidence,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.AppliedAt,
			&i.AppliedChanges,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestionMarkApplied = `-- name: SuggestionMarkApplied :one
UPDATE skill_suggestions
SET status = 'applied', applied_at = NOW(), applied_changes = $1
WHERE id = $2 AND status = 'approved' AND applied_at IS NULL
RETURNING id, skill_slug, kind, payload, rationale, llm_model,
          llm_confidence::float8 AS llm_confidence, status, reviewed_by,
          reviewed_at, applied_at, applied_changes, created_at
`

type SuggestionMarkAppliedParams struct {
	AppliedChanges []byte    `json:"applied_changes"`
	ID             uuid.UUID `json:"id"`
}

type SuggestionMarkAppliedRow struct {
	ID             uuid.UUID          `json:"id"`
	SkillSlug      string             `json:"skill_slug"`
	Kind           string             `json:"kind"`
	Payload        []byte             `json:"payload"`
	Rationale      *string            `json:"rationale"`
	LlmModel       *string            `json:"llm_model"`
	LlmConfidence  float64            `json:"llm_confidence"`
	Status         string             `json:"status"`
	ReviewedBy     *uuid.UUID         `json:"reviewed_by"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt      pgtype.Timestamptz `json:"applied_at"`
	AppliedChanges []byte             `json:"applied_changes"`
	CreatedAt      time.Time          `json:"created_at"`
}

// Cierra el Apply (approved -> applied). Guard optimista contra doble-apply:
// solo si status='approved' AND applied_at IS NULL. Si 0 filas, ya se aplico.
func (q *Queries) SuggestionMarkApplied(ctx context.Context, arg SuggestionMarkAppliedParams) (SuggestionMarkAppliedRow, error) {
	row := q.db.QueryRow(ctx, suggestionMarkApplied, arg.AppliedChanges, arg.ID)
	var i SuggestionMarkAppliedRow
	err := row.Scan(
		&i.ID,
		&i.SkillSlug,
		&i.Kind,
		&i.Payload,
		&i.Rationale,
		&i.LlmModel,
		&i.LlmConfidence,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.AppliedChanges,
		&i.CreatedAt,
	)
	return i, err
}

const suggestionReject = `-- name: SuggestionReject :one
UPDATE skill_suggestions
SET status = 'rejected', reviewed_by = $1, reviewed_at = NOW()
WHERE id = $2 AND status = 'pending'
RETURNING id, skill_slug, kind, payload, rationale, llm_model,
          llm_confidence::float8 AS llm_confidence, status, reviewed_by,
          reviewed_at, applied_at, applied_changes, created_at
`

type SuggestionRejectParams struct {
	ReviewedBy *uuid.UUID `json:"reviewed_by"`
	ID         uuid.UUID  `json:"id"`
}

type SuggestionRejectRow struct {
	ID             uuid.UUID          `json:"id"`
	SkillSlug      string             `json:"skill_slug"`
	Kind           string             `json:"kind"`
	Payload        []byte             `json:"payload"`
	Rationale      *string            `json:"rationale"`
	LlmModel       *string            `json:"llm_model"`
	LlmConfidence  float64            `json:"llm_confidence"`
	Status         string             `json:"status"`
	ReviewedBy     *uuid.UUID         `json:"reviewed_by"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt      pgtype.Timestamptz `json:"applied_at"`
	AppliedChanges []byte             `json:"applied_changes"`
	CreatedAt      time.Time          `json:"created_at"`
}

// Rechaza (pending -> rejected). Mismo guard optimista.
func (q *Queries) SuggestionReject(ctx context.Context, arg SuggestionRejectParams) (SuggestionRejectRow, error) {
	row := q.db.QueryRow(ctx, suggestionReject, arg.ReviewedBy, arg.ID)
	var i SuggestionRejectRow
	err := row.Scan(
		&i.ID,
		&i.SkillSlug,
		&i.Kind,
		&i.Payload,
		&i.Rationale,
		&i.LlmModel,
		&i.LlmConfidence,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.AppliedChanges,
		&i.CreatedAt,
	)
	return i, err
}

const suggestionSkillArchive = `-- name: SuggestionSkillArchive :execrows
UPDATE skills
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL AND seed_managed = false
`

// ARCHIVE: soft-delete (NUNCA DELETE fisico -> rompe metricas por FK CASCADE).
// Guard: jamas archivar seed_managed=true (regla dura). Devuelve filas afectadas.
func (q *Queries) SuggestionSkillArchive(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, suggestionSkillArchive, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suggestionSkillBySlug = `-- name: SuggestionSkillBySlug :one

SELECT id, slug, name, description, COALESCE(content,'')::text AS content,
       skill_type, seed_managed, deleted_at
FROM skills
WHERE slug = $1 AND deleted_at IS NULL
`

type SuggestionSkillBySlugRow struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Content     string             `json:"content"`
	SkillType   string             `json:"skill_type"`
	SeedManaged bool               `json:"seed_managed"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

// ============================================================
// Operaciones sobre skills usadas por el Apply (transaccionales via txctx).
// ============================================================
// Resuelve slug -> skill (vivo). El Apply lo usa para obtener el id/seed_managed
// del skill objetivo antes de mutarlo.
func (q *Queries) SuggestionSkillBySlug(ctx context.Context, slug string) (SuggestionSkillBySlugRow, error) {
	row := q.db.QueryRow(ctx, suggestionSkillBySlug, slug)
	var i SuggestionSkillBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.SkillType,
		&i.SeedManaged,
		&i.DeletedAt,
	)
	return i, err
}

const suggestionSkillCreateChild = `-- name: SuggestionSkillCreateChild :one
INSERT INTO skills (
    slug, name, description, skill_type, content,
    parent_skill_id, seed_managed, proposed
)
SELECT $1, $2, $3,
       parent.skill_type, $4,
       $5, false, false
FROM skills parent
WHERE parent.id = $5
RETURNING id, slug
`

type SuggestionSkillCreateChildParams struct {
	Slug          string     `json:"slug"`
	Name          string     `json:"name"`
	Description   *string    `json:"description"`
	Content       *string    `json:"content"`
	ParentSkillID *uuid.UUID `json:"parent_skill_id"`
}

type SuggestionSkillCreateChildRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

// SPLIT/MERGE: crea un skill nuevo (hijo o consolidado). parent_skill_id enlaza
// el linaje. proposed=false (visible). single-tenant: skills NO tiene
// organization_id (la dropeo la mig 000142 de todas las tablas), por eso no se inserta.
func (q *Queries) SuggestionSkillCreateChild(ctx context.Context, arg SuggestionSkillCreateChildParams) (SuggestionSkillCreateChildRow, error) {
	row := q.db.QueryRow(ctx, suggestionSkillCreateChild,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.ParentSkillID,
	)
	var i SuggestionSkillCreateChildRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const suggestionSkillMarkSplitParent = `-- name: SuggestionSkillMarkSplitParent :execrows
UPDATE skills
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL AND seed_managed = false
`

// SPLIT: tras crear los hijos, soft-delete el original (sus hijos lo referencian
// via parent_skill_id). seed_managed=true nunca se toca (guard).
func (q *Queries) SuggestionSkillMarkSplitParent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, suggestionSkillMarkSplitParent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suggestionSkillRefineContent = `-- name: SuggestionSkillRefineContent :execrows
UPDATE skills
SET content = $1, is_user_modified = true, updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type SuggestionSkillRefineContentParams struct {
	Content *string   `json:"content"`
	ID      uuid.UUID `json:"id"`
}

// REFINE: actualiza el content del skill (el snapshot/version lo crea el caller
// via VersionStore antes/despues, fuera de esta query, dentro de la misma tx).
func (q *Queries) SuggestionSkillRefineContent(ctx context.Context, arg SuggestionSkillRefineContentParams) (int64, error) {
	result, err := q.db.Exec(ctx, suggestionSkillRefineContent, arg.Content, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suggestionSkillSupersede = `-- name: SuggestionSkillSupersede :execrows
UPDATE skills
SET superseded_by = $1, deleted_at = NOW(), updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL AND seed_managed = false
`

type SuggestionSkillSupersedeParams struct {
	SupersededBy *uuid.UUID `json:"superseded_by"`
	ID           uuid.UUID  `json:"id"`
}

// MERGE: marca un skill original como superseded por el consolidado + soft-delete.
// Permite redirigir el slug viejo sin perder el linaje ni las metricas.
// Guard: jamas superseder seed_managed=true (consistente con ARCHIVE/SPLIT).
func (q *Queries) SuggestionSkillSupersede(ctx context.Context, arg SuggestionSkillSupersedeParams) (int64, error) {
	result, err := q.db.Exec(ctx, suggestionSkillSupersede, arg.SupersededBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
