// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package specdb

import (
	"time"

	"github.com/google/uuid"
)

type SddDesign struct {
	ID              uuid.UUID  `json:"id"`
	IssueID         uuid.UUID  `json:"issue_id"`
	ProposalID      *uuid.UUID `json:"proposal_id"`
	Version         int32      `json:"version"`
	Status          string     `json:"status"`
	ArchDecisions   string     `json:"arch_decisions"`
	Alternatives    *string    `json:"alternatives"`
	DataFlow        *string    `json:"data_flow"`
	TddPlan         *string    `json:"tdd_plan"`
	RisksMitigation *string    `json:"risks_mitigation"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type SddProposal struct {
	ID              uuid.UUID `json:"id"`
	IssueID         uuid.UUID `json:"issue_id"`
	Version         int32     `json:"version"`
	Status          string    `json:"status"`
	Intention       string    `json:"intention"`
	Scope           string    `json:"scope"`
	Approach        string    `json:"approach"`
	Risks           *string   `json:"risks"`
	TestingNotes    *string   `json:"testing_notes"`
	RejectionReason *string   `json:"rejection_reason"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
