// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package specdb

import (
	"context"

	"github.com/google/uuid"
)

const getDesignByID = `-- name: GetDesignByID :one
SELECT id, issue_id, proposal_id, version, status, arch_decisions, alternatives, data_flow, tdd_plan, risks_mitigation, created_at, updated_at
FROM sdd_designs WHERE id = $1
`

func (q *Queries) GetDesignByID(ctx context.Context, id uuid.UUID) (SddDesign, error) {
	row := q.db.QueryRow(ctx, getDesignByID, id)
	var i SddDesign
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProposalID,
		&i.Version,
		&i.Status,
		&i.ArchDecisions,
		&i.Alternatives,
		&i.DataFlow,
		&i.TddPlan,
		&i.RisksMitigation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestDesign = `-- name: GetLatestDesign :one
SELECT id, issue_id, proposal_id, version, status, arch_decisions, alternatives, data_flow, tdd_plan, risks_mitigation, created_at, updated_at
FROM sdd_designs WHERE issue_id = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetLatestDesign(ctx context.Context, issueID uuid.UUID) (SddDesign, error) {
	row := q.db.QueryRow(ctx, getLatestDesign, issueID)
	var i SddDesign
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProposalID,
		&i.Version,
		&i.Status,
		&i.ArchDecisions,
		&i.Alternatives,
		&i.DataFlow,
		&i.TddPlan,
		&i.RisksMitigation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestProposal = `-- name: GetLatestProposal :one
SELECT id, issue_id, version, status, intention, scope, approach, risks, testing_notes, rejection_reason, created_at, updated_at
FROM sdd_proposals WHERE issue_id = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetLatestProposal(ctx context.Context, issueID uuid.UUID) (SddProposal, error) {
	row := q.db.QueryRow(ctx, getLatestProposal, issueID)
	var i SddProposal
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Version,
		&i.Status,
		&i.Intention,
		&i.Scope,
		&i.Approach,
		&i.Risks,
		&i.TestingNotes,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProposalByID = `-- name: GetProposalByID :one
SELECT id, issue_id, version, status, intention, scope, approach, risks, testing_notes, rejection_reason, created_at, updated_at
FROM sdd_proposals WHERE id = $1
`

func (q *Queries) GetProposalByID(ctx context.Context, id uuid.UUID) (SddProposal, error) {
	row := q.db.QueryRow(ctx, getProposalByID, id)
	var i SddProposal
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Version,
		&i.Status,
		&i.Intention,
		&i.Scope,
		&i.Approach,
		&i.Risks,
		&i.TestingNotes,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProposalVersion = `-- name: GetProposalVersion :one
SELECT id, issue_id, version, status, intention, scope, approach, risks, testing_notes, rejection_reason, created_at, updated_at
FROM sdd_proposals WHERE issue_id = $1 AND version = $2
`

type GetProposalVersionParams struct {
	IssueID uuid.UUID `json:"issue_id"`
	Version int32     `json:"version"`
}

func (q *Queries) GetProposalVersion(ctx context.Context, arg GetProposalVersionParams) (SddProposal, error) {
	row := q.db.QueryRow(ctx, getProposalVersion, arg.IssueID, arg.Version)
	var i SddProposal
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Version,
		&i.Status,
		&i.Intention,
		&i.Scope,
		&i.Approach,
		&i.Risks,
		&i.TestingNotes,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDesign = `-- name: InsertDesign :one
INSERT INTO sdd_designs (issue_id, proposal_id, version, status, arch_decisions, alternatives, data_flow, tdd_plan, risks_mitigation)
VALUES ($1, $2, $3, 'draft', $4, $5, $6, $7, $8)
RETURNING id, issue_id, proposal_id, version, status, arch_decisions, alternatives, data_flow, tdd_plan, risks_mitigation, created_at, updated_at
`

type InsertDesignParams struct {
	IssueID         uuid.UUID  `json:"issue_id"`
	ProposalID      *uuid.UUID `json:"proposal_id"`
	Version         int32      `json:"version"`
	ArchDecisions   string     `json:"arch_decisions"`
	Alternatives    *string    `json:"alternatives"`
	DataFlow        *string    `json:"data_flow"`
	TddPlan         *string    `json:"tdd_plan"`
	RisksMitigation *string    `json:"risks_mitigation"`
}

func (q *Queries) InsertDesign(ctx context.Context, arg InsertDesignParams) (SddDesign, error) {
	row := q.db.QueryRow(ctx, insertDesign,
		arg.IssueID,
		arg.ProposalID,
		arg.Version,
		arg.ArchDecisions,
		arg.Alternatives,
		arg.DataFlow,
		arg.TddPlan,
		arg.RisksMitigation,
	)
	var i SddDesign
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProposalID,
		&i.Version,
		&i.Status,
		&i.ArchDecisions,
		&i.Alternatives,
		&i.DataFlow,
		&i.TddPlan,
		&i.RisksMitigation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProposal = `-- name: InsertProposal :one
INSERT INTO sdd_proposals (issue_id, version, status, intention, scope, approach, risks, testing_notes)
VALUES ($1, $2, 'draft', $3, $4, $5, $6, $7)
RETURNING id, issue_id, version, status, intention, scope, approach, risks, testing_notes, rejection_reason, created_at, updated_at
`

type InsertProposalParams struct {
	IssueID      uuid.UUID `json:"issue_id"`
	Version      int32     `json:"version"`
	Intention    string    `json:"intention"`
	Scope        string    `json:"scope"`
	Approach     string    `json:"approach"`
	Risks        *string   `json:"risks"`
	TestingNotes *string   `json:"testing_notes"`
}

func (q *Queries) InsertProposal(ctx context.Context, arg InsertProposalParams) (SddProposal, error) {
	row := q.db.QueryRow(ctx, insertProposal,
		arg.IssueID,
		arg.Version,
		arg.Intention,
		arg.Scope,
		arg.Approach,
		arg.Risks,
		arg.TestingNotes,
	)
	var i SddProposal
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Version,
		&i.Status,
		&i.Intention,
		&i.Scope,
		&i.Approach,
		&i.Risks,
		&i.TestingNotes,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const issueExists = `-- name: IssueExists :one
SELECT EXISTS(SELECT 1 FROM issues WHERE id = $1)
`

func (q *Queries) IssueExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, issueExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDesignsByIssue = `-- name: ListDesignsByIssue :many
SELECT id, issue_id, proposal_id, version, status, arch_decisions, alternatives, data_flow, tdd_plan, risks_mitigation, created_at, updated_at
FROM sdd_designs WHERE issue_id = $1 ORDER BY version DESC
`

func (q *Queries) ListDesignsByIssue(ctx context.Context, issueID uuid.UUID) ([]SddDesign, error) {
	rows, err := q.db.Query(ctx, listDesignsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SddDesign
	for rows.Next() {
		var i SddDesign
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.ProposalID,
			&i.Version,
			&i.Status,
			&i.ArchDecisions,
			&i.Alternatives,
			&i.DataFlow,
			&i.TddPlan,
			&i.RisksMitigation,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposalVersions = `-- name: ListProposalVersions :many
SELECT id, issue_id, version, status, intention, scope, approach, risks, testing_notes, rejection_reason, created_at, updated_at
FROM sdd_proposals WHERE issue_id = $1 ORDER BY version DESC
`

func (q *Queries) ListProposalVersions(ctx context.Context, issueID uuid.UUID) ([]SddProposal, error) {
	rows, err := q.db.Query(ctx, listProposalVersions, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SddProposal
	for rows.Next() {
		var i SddProposal
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Version,
			&i.Status,
			&i.Intention,
			&i.Scope,
			&i.Approach,
			&i.Risks,
			&i.TestingNotes,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxDesignVersion = `-- name: MaxDesignVersion :one
SELECT COALESCE(MAX(version), 0)::int FROM sdd_designs WHERE issue_id = $1
`

func (q *Queries) MaxDesignVersion(ctx context.Context, issueID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxDesignVersion, issueID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const maxProposalVersion = `-- name: MaxProposalVersion :one
SELECT COALESCE(MAX(version), 0)::int FROM sdd_proposals WHERE issue_id = $1
`

func (q *Queries) MaxProposalVersion(ctx context.Context, issueID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxProposalVersion, issueID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateDesignStatus = `-- name: UpdateDesignStatus :one
UPDATE sdd_designs SET status = $2, updated_at = NOW()
WHERE id = $1 AND status = $3
RETURNING id, issue_id, proposal_id, version, status, arch_decisions, alternatives, data_flow, tdd_plan, risks_mitigation, created_at, updated_at
`

type UpdateDesignStatusParams struct {
	ID             uuid.UUID `json:"id"`
	Status         string    `json:"status"`
	ExpectedStatus string    `json:"expected_status"`
}

// Guard optimista: exige el status leído para evitar transiciones concurrentes.
func (q *Queries) UpdateDesignStatus(ctx context.Context, arg UpdateDesignStatusParams) (SddDesign, error) {
	row := q.db.QueryRow(ctx, updateDesignStatus, arg.ID, arg.Status, arg.ExpectedStatus)
	var i SddDesign
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProposalID,
		&i.Version,
		&i.Status,
		&i.ArchDecisions,
		&i.Alternatives,
		&i.DataFlow,
		&i.TddPlan,
		&i.RisksMitigation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProposalStatus = `-- name: UpdateProposalStatus :one
UPDATE sdd_proposals SET status = $2, rejection_reason = $3, updated_at = NOW()
WHERE id = $1 AND status = $4
RETURNING id, issue_id, version, status, intention, scope, approach, risks, testing_notes, rejection_reason, created_at, updated_at
`

type UpdateProposalStatusParams struct {
	ID              uuid.UUID `json:"id"`
	Status          string    `json:"status"`
	RejectionReason *string   `json:"rejection_reason"`
	ExpectedStatus  string    `json:"expected_status"`
}

// Guard optimista: el UPDATE exige el status leído (expected_status) para que
// dos transiciones concurrentes no se pisen (la segunda no matchea → ErrNoRows).
func (q *Queries) UpdateProposalStatus(ctx context.Context, arg UpdateProposalStatusParams) (SddProposal, error) {
	row := q.db.QueryRow(ctx, updateProposalStatus,
		arg.ID,
		arg.Status,
		arg.RejectionReason,
		arg.ExpectedStatus,
	)
	var i SddProposal
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Version,
		&i.Status,
		&i.Intention,
		&i.Scope,
		&i.Approach,
		&i.Risks,
		&i.TestingNotes,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
