// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package intakedb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveIntake = `-- name: ApproveIntake :exec
UPDATE issue_intake_payloads
SET status = $1, reviewer_id = $2, reviewed_at = now(), updated_at = now()
WHERE id = $3
`

type ApproveIntakeParams struct {
	Status     string     `json:"status"`
	ReviewerID *uuid.UUID `json:"reviewer_id"`
	ID         uuid.UUID  `json:"id"`
}

func (q *Queries) ApproveIntake(ctx context.Context, arg ApproveIntakeParams) error {
	_, err := q.db.Exec(ctx, approveIntake, arg.Status, arg.ReviewerID, arg.ID)
	return err
}

const getIntake = `-- name: GetIntake :one
SELECT id, source, source_ref, submitted_by, raw_text, raw_payload,
       status, classified_type, classified_severity, classified_confidence,
       classification_reasoning, needs_clarification, proposed_title,
       proposed_description, proposed_req_slug, proposed_hu_draft,
       dedup_candidates, merge_action, reviewer_id, reviewed_at,
       rejection_reason, committed_req_id, committed_issue_id, failure_reason,
       created_at, updated_at
FROM issue_intake_payloads WHERE id = $1
`

type GetIntakeRow struct {
	ID                      uuid.UUID          `json:"id"`
	Source                  string             `json:"source"`
	SourceRef               *string            `json:"source_ref"`
	SubmittedBy             *string            `json:"submitted_by"`
	RawText                 string             `json:"raw_text"`
	RawPayload              []byte             `json:"raw_payload"`
	Status                  string             `json:"status"`
	ClassifiedType          *string            `json:"classified_type"`
	ClassifiedSeverity      *string            `json:"classified_severity"`
	ClassifiedConfidence    pgtype.Numeric     `json:"classified_confidence"`
	ClassificationReasoning *string            `json:"classification_reasoning"`
	NeedsClarification      bool               `json:"needs_clarification"`
	ProposedTitle           *string            `json:"proposed_title"`
	ProposedDescription     *string            `json:"proposed_description"`
	ProposedReqSlug         *string            `json:"proposed_req_slug"`
	ProposedHuDraft         []byte             `json:"proposed_hu_draft"`
	DedupCandidates         []byte             `json:"dedup_candidates"`
	MergeAction             *string            `json:"merge_action"`
	ReviewerID              *uuid.UUID         `json:"reviewer_id"`
	ReviewedAt              pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason         *string            `json:"rejection_reason"`
	CommittedReqID          *uuid.UUID         `json:"committed_req_id"`
	CommittedIssueID        *uuid.UUID         `json:"committed_issue_id"`
	FailureReason           *string            `json:"failure_reason"`
	CreatedAt               time.Time          `json:"created_at"`
	UpdatedAt               time.Time          `json:"updated_at"`
}

func (q *Queries) GetIntake(ctx context.Context, id uuid.UUID) (GetIntakeRow, error) {
	row := q.db.QueryRow(ctx, getIntake, id)
	var i GetIntakeRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceRef,
		&i.SubmittedBy,
		&i.RawText,
		&i.RawPayload,
		&i.Status,
		&i.ClassifiedType,
		&i.ClassifiedSeverity,
		&i.ClassifiedConfidence,
		&i.ClassificationReasoning,
		&i.NeedsClarification,
		&i.ProposedTitle,
		&i.ProposedDescription,
		&i.ProposedReqSlug,
		&i.ProposedHuDraft,
		&i.DedupCandidates,
		&i.MergeAction,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CommittedReqID,
		&i.CommittedIssueID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIntake = `-- name: InsertIntake :one
INSERT INTO issue_intake_payloads (
    source, source_ref, submitted_by, raw_text, raw_payload, project_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, source, source_ref, submitted_by, raw_text, raw_payload,
          status, classified_type, classified_severity, classified_confidence,
          classification_reasoning, needs_clarification, proposed_title,
          proposed_description, proposed_req_slug, proposed_hu_draft,
          dedup_candidates, merge_action, reviewer_id, reviewed_at,
          rejection_reason, committed_req_id, committed_issue_id, failure_reason,
          created_at, updated_at
`

type InsertIntakeParams struct {
	Source      string    `json:"source"`
	SourceRef   *string   `json:"source_ref"`
	SubmittedBy *string   `json:"submitted_by"`
	RawText     string    `json:"raw_text"`
	RawPayload  []byte    `json:"raw_payload"`
	ProjectID   uuid.UUID `json:"project_id"`
}

type InsertIntakeRow struct {
	ID                      uuid.UUID          `json:"id"`
	Source                  string             `json:"source"`
	SourceRef               *string            `json:"source_ref"`
	SubmittedBy             *string            `json:"submitted_by"`
	RawText                 string             `json:"raw_text"`
	RawPayload              []byte             `json:"raw_payload"`
	Status                  string             `json:"status"`
	ClassifiedType          *string            `json:"classified_type"`
	ClassifiedSeverity      *string            `json:"classified_severity"`
	ClassifiedConfidence    pgtype.Numeric     `json:"classified_confidence"`
	ClassificationReasoning *string            `json:"classification_reasoning"`
	NeedsClarification      bool               `json:"needs_clarification"`
	ProposedTitle           *string            `json:"proposed_title"`
	ProposedDescription     *string            `json:"proposed_description"`
	ProposedReqSlug         *string            `json:"proposed_req_slug"`
	ProposedHuDraft         []byte             `json:"proposed_hu_draft"`
	DedupCandidates         []byte             `json:"dedup_candidates"`
	MergeAction             *string            `json:"merge_action"`
	ReviewerID              *uuid.UUID         `json:"reviewer_id"`
	ReviewedAt              pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason         *string            `json:"rejection_reason"`
	CommittedReqID          *uuid.UUID         `json:"committed_req_id"`
	CommittedIssueID        *uuid.UUID         `json:"committed_issue_id"`
	FailureReason           *string            `json:"failure_reason"`
	CreatedAt               time.Time          `json:"created_at"`
	UpdatedAt               time.Time          `json:"updated_at"`
}

func (q *Queries) InsertIntake(ctx context.Context, arg InsertIntakeParams) (InsertIntakeRow, error) {
	row := q.db.QueryRow(ctx, insertIntake,
		arg.Source,
		arg.SourceRef,
		arg.SubmittedBy,
		arg.RawText,
		arg.RawPayload,
		arg.ProjectID,
	)
	var i InsertIntakeRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceRef,
		&i.SubmittedBy,
		&i.RawText,
		&i.RawPayload,
		&i.Status,
		&i.ClassifiedType,
		&i.ClassifiedSeverity,
		&i.ClassifiedConfidence,
		&i.ClassificationReasoning,
		&i.NeedsClarification,
		&i.ProposedTitle,
		&i.ProposedDescription,
		&i.ProposedReqSlug,
		&i.ProposedHuDraft,
		&i.DedupCandidates,
		&i.MergeAction,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CommittedReqID,
		&i.CommittedIssueID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkCommitted = `-- name: LinkCommitted :exec
UPDATE issue_intake_payloads
SET status = $1, committed_req_id = $2, committed_issue_id = $3, updated_at = now()
WHERE id = $4
`

type LinkCommittedParams struct {
	Status           string     `json:"status"`
	CommittedReqID   *uuid.UUID `json:"committed_req_id"`
	CommittedIssueID *uuid.UUID `json:"committed_issue_id"`
	ID               uuid.UUID  `json:"id"`
}

func (q *Queries) LinkCommitted(ctx context.Context, arg LinkCommittedParams) error {
	_, err := q.db.Exec(ctx, linkCommitted,
		arg.Status,
		arg.CommittedReqID,
		arg.CommittedIssueID,
		arg.ID,
	)
	return err
}

const listPendingIntakes = `-- name: ListPendingIntakes :many
SELECT id, source, source_ref, submitted_by, raw_text, raw_payload,
       status, classified_type, classified_severity, classified_confidence,
       classification_reasoning, needs_clarification, proposed_title,
       proposed_description, proposed_req_slug, proposed_hu_draft,
       dedup_candidates, merge_action, reviewer_id, reviewed_at,
       rejection_reason, committed_req_id, committed_issue_id, failure_reason,
       created_at, updated_at
FROM issue_intake_payloads
WHERE status NOT IN ('committed', 'rejected', 'failed')
ORDER BY created_at ASC LIMIT $1
`

type ListPendingIntakesRow struct {
	ID                      uuid.UUID          `json:"id"`
	Source                  string             `json:"source"`
	SourceRef               *string            `json:"source_ref"`
	SubmittedBy             *string            `json:"submitted_by"`
	RawText                 string             `json:"raw_text"`
	RawPayload              []byte             `json:"raw_payload"`
	Status                  string             `json:"status"`
	ClassifiedType          *string            `json:"classified_type"`
	ClassifiedSeverity      *string            `json:"classified_severity"`
	ClassifiedConfidence    pgtype.Numeric     `json:"classified_confidence"`
	ClassificationReasoning *string            `json:"classification_reasoning"`
	NeedsClarification      bool               `json:"needs_clarification"`
	ProposedTitle           *string            `json:"proposed_title"`
	ProposedDescription     *string            `json:"proposed_description"`
	ProposedReqSlug         *string            `json:"proposed_req_slug"`
	ProposedHuDraft         []byte             `json:"proposed_hu_draft"`
	DedupCandidates         []byte             `json:"dedup_candidates"`
	MergeAction             *string            `json:"merge_action"`
	ReviewerID              *uuid.UUID         `json:"reviewer_id"`
	ReviewedAt              pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason         *string            `json:"rejection_reason"`
	CommittedReqID          *uuid.UUID         `json:"committed_req_id"`
	CommittedIssueID        *uuid.UUID         `json:"committed_issue_id"`
	FailureReason           *string            `json:"failure_reason"`
	CreatedAt               time.Time          `json:"created_at"`
	UpdatedAt               time.Time          `json:"updated_at"`
}

func (q *Queries) ListPendingIntakes(ctx context.Context, limit int32) ([]ListPendingIntakesRow, error) {
	rows, err := q.db.Query(ctx, listPendingIntakes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingIntakesRow
	for rows.Next() {
		var i ListPendingIntakesRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceRef,
			&i.SubmittedBy,
			&i.RawText,
			&i.RawPayload,
			&i.Status,
			&i.ClassifiedType,
			&i.ClassifiedSeverity,
			&i.ClassifiedConfidence,
			&i.ClassificationReasoning,
			&i.NeedsClarification,
			&i.ProposedTitle,
			&i.ProposedDescription,
			&i.ProposedReqSlug,
			&i.ProposedHuDraft,
			&i.DedupCandidates,
			&i.MergeAction,
			&i.ReviewerID,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.CommittedReqID,
			&i.CommittedIssueID,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPendingReview = `-- name: MarkPendingReview :exec
UPDATE issue_intake_payloads
SET proposed_title = $1, proposed_description = $2, proposed_req_slug = $3,
    proposed_hu_draft = $4, dedup_candidates = $5, merge_action = $6,
    status = $7, updated_at = now()
WHERE id = $8
`

type MarkPendingReviewParams struct {
	ProposedTitle       *string   `json:"proposed_title"`
	ProposedDescription *string   `json:"proposed_description"`
	ProposedReqSlug     *string   `json:"proposed_req_slug"`
	ProposedHuDraft     []byte    `json:"proposed_hu_draft"`
	DedupCandidates     []byte    `json:"dedup_candidates"`
	MergeAction         *string   `json:"merge_action"`
	Status              string    `json:"status"`
	ID                  uuid.UUID `json:"id"`
}

func (q *Queries) MarkPendingReview(ctx context.Context, arg MarkPendingReviewParams) error {
	_, err := q.db.Exec(ctx, markPendingReview,
		arg.ProposedTitle,
		arg.ProposedDescription,
		arg.ProposedReqSlug,
		arg.ProposedHuDraft,
		arg.DedupCandidates,
		arg.MergeAction,
		arg.Status,
		arg.ID,
	)
	return err
}

const rejectIntake = `-- name: RejectIntake :exec
UPDATE issue_intake_payloads
SET status = $1, reviewer_id = $2, reviewed_at = now(),
    rejection_reason = $3, updated_at = now()
WHERE id = $4
`

type RejectIntakeParams struct {
	Status          string     `json:"status"`
	ReviewerID      *uuid.UUID `json:"reviewer_id"`
	RejectionReason *string    `json:"rejection_reason"`
	ID              uuid.UUID  `json:"id"`
}

func (q *Queries) RejectIntake(ctx context.Context, arg RejectIntakeParams) error {
	_, err := q.db.Exec(ctx, rejectIntake,
		arg.Status,
		arg.ReviewerID,
		arg.RejectionReason,
		arg.ID,
	)
	return err
}

const updateClassification = `-- name: UpdateClassification :exec
UPDATE issue_intake_payloads
SET classified_type = $1, classified_severity = $2, classified_confidence = $3,
    classification_reasoning = $4, needs_clarification = $5,
    status = $6, updated_at = now()
WHERE id = $7
`

type UpdateClassificationParams struct {
	ClassifiedType          *string        `json:"classified_type"`
	ClassifiedSeverity      *string        `json:"classified_severity"`
	ClassifiedConfidence    pgtype.Numeric `json:"classified_confidence"`
	ClassificationReasoning *string        `json:"classification_reasoning"`
	NeedsClarification      bool           `json:"needs_clarification"`
	Status                  string         `json:"status"`
	ID                      uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateClassification(ctx context.Context, arg UpdateClassificationParams) error {
	_, err := q.db.Exec(ctx, updateClassification,
		arg.ClassifiedType,
		arg.ClassifiedSeverity,
		arg.ClassifiedConfidence,
		arg.ClassificationReasoning,
		arg.NeedsClarification,
		arg.Status,
		arg.ID,
	)
	return err
}
