// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package workflowimportdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFileByProjectAndPath = `-- name: GetFileByProjectAndPath :one
SELECT id, project_id, source_tool, rel_path, original_content,
       content_hash, size_bytes, status, replaced_with, replaced_at,
       restored_at, created_at, updated_at
FROM project_imported_workflow_files
WHERE project_id = $1 AND rel_path = $2
`

type GetFileByProjectAndPathParams struct {
	ProjectID *uuid.UUID `json:"project_id"`
	RelPath   string     `json:"rel_path"`
}

type GetFileByProjectAndPathRow struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       *uuid.UUID         `json:"project_id"`
	SourceTool      string             `json:"source_tool"`
	RelPath         string             `json:"rel_path"`
	OriginalContent string             `json:"original_content"`
	ContentHash     string             `json:"content_hash"`
	SizeBytes       int64              `json:"size_bytes"`
	Status          string             `json:"status"`
	ReplacedWith    *string            `json:"replaced_with"`
	ReplacedAt      pgtype.Timestamptz `json:"replaced_at"`
	RestoredAt      pgtype.Timestamptz `json:"restored_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) GetFileByProjectAndPath(ctx context.Context, arg GetFileByProjectAndPathParams) (GetFileByProjectAndPathRow, error) {
	row := q.db.QueryRow(ctx, getFileByProjectAndPath, arg.ProjectID, arg.RelPath)
	var i GetFileByProjectAndPathRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceTool,
		&i.RelPath,
		&i.OriginalContent,
		&i.ContentHash,
		&i.SizeBytes,
		&i.Status,
		&i.ReplacedWith,
		&i.ReplacedAt,
		&i.RestoredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByRelPath = `-- name: GetFileByRelPath :one
SELECT id, source_tool, rel_path, original_content, status, replaced_at
FROM project_imported_workflow_files
WHERE ($1::uuid IS NULL AND project_id IS NULL OR project_id = $1::uuid)
  AND rel_path = $2
`

type GetFileByRelPathParams struct {
	ProjectID *uuid.UUID `json:"project_id"`
	RelPath   string     `json:"rel_path"`
}

type GetFileByRelPathRow struct {
	ID              uuid.UUID          `json:"id"`
	SourceTool      string             `json:"source_tool"`
	RelPath         string             `json:"rel_path"`
	OriginalContent string             `json:"original_content"`
	Status          string             `json:"status"`
	ReplacedAt      pgtype.Timestamptz `json:"replaced_at"`
}

func (q *Queries) GetFileByRelPath(ctx context.Context, arg GetFileByRelPathParams) (GetFileByRelPathRow, error) {
	row := q.db.QueryRow(ctx, getFileByRelPath, arg.ProjectID, arg.RelPath)
	var i GetFileByRelPathRow
	err := row.Scan(
		&i.ID,
		&i.SourceTool,
		&i.RelPath,
		&i.OriginalContent,
		&i.Status,
		&i.ReplacedAt,
	)
	return i, err
}

const listProjectFiles = `-- name: ListProjectFiles :many
SELECT id, project_id, source_tool, rel_path, original_content,
       content_hash, size_bytes, status, replaced_with, replaced_at,
       restored_at, created_at, updated_at
FROM project_imported_workflow_files
WHERE ($1::uuid IS NULL AND project_id IS NULL OR project_id = $1::uuid)
ORDER BY rel_path ASC
`

type ListProjectFilesRow struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       *uuid.UUID         `json:"project_id"`
	SourceTool      string             `json:"source_tool"`
	RelPath         string             `json:"rel_path"`
	OriginalContent string             `json:"original_content"`
	ContentHash     string             `json:"content_hash"`
	SizeBytes       int64              `json:"size_bytes"`
	Status          string             `json:"status"`
	ReplacedWith    *string            `json:"replaced_with"`
	ReplacedAt      pgtype.Timestamptz `json:"replaced_at"`
	RestoredAt      pgtype.Timestamptz `json:"restored_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) ListProjectFiles(ctx context.Context, projectID *uuid.UUID) ([]ListProjectFilesRow, error) {
	rows, err := q.db.Query(ctx, listProjectFiles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectFilesRow
	for rows.Next() {
		var i ListProjectFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceTool,
			&i.RelPath,
			&i.OriginalContent,
			&i.ContentHash,
			&i.SizeBytes,
			&i.Status,
			&i.ReplacedWith,
			&i.ReplacedAt,
			&i.RestoredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFileRestored = `-- name: SetFileRestored :exec
UPDATE project_imported_workflow_files
SET status = $1, restored_at = now(), updated_at = now()
WHERE id = $2
`

type SetFileRestoredParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SetFileRestored(ctx context.Context, arg SetFileRestoredParams) error {
	_, err := q.db.Exec(ctx, setFileRestored, arg.Status, arg.ID)
	return err
}

const upsertFile = `-- name: UpsertFile :one
INSERT INTO project_imported_workflow_files
  (project_id, source_tool, rel_path, original_content,
   content_hash, size_bytes, status, replaced_with, replaced_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        CASE WHEN $7 = 'replaced' THEN now() ELSE NULL END)
ON CONFLICT (project_id, rel_path) DO UPDATE
SET original_content = EXCLUDED.original_content,
    content_hash     = EXCLUDED.content_hash,
    size_bytes       = EXCLUDED.size_bytes,
    status           = EXCLUDED.status,
    replaced_with    = EXCLUDED.replaced_with,
    replaced_at      = EXCLUDED.replaced_at,
    updated_at       = now()
RETURNING id, project_id, source_tool, rel_path, original_content,
          content_hash, size_bytes, status, replaced_with, replaced_at,
          restored_at, created_at, updated_at
`

type UpsertFileParams struct {
	ProjectID       *uuid.UUID `json:"project_id"`
	SourceTool      string     `json:"source_tool"`
	RelPath         string     `json:"rel_path"`
	OriginalContent string     `json:"original_content"`
	ContentHash     string     `json:"content_hash"`
	SizeBytes       int64      `json:"size_bytes"`
	Status          string     `json:"status"`
	ReplacedWith    *string    `json:"replaced_with"`
}

type UpsertFileRow struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       *uuid.UUID         `json:"project_id"`
	SourceTool      string             `json:"source_tool"`
	RelPath         string             `json:"rel_path"`
	OriginalContent string             `json:"original_content"`
	ContentHash     string             `json:"content_hash"`
	SizeBytes       int64              `json:"size_bytes"`
	Status          string             `json:"status"`
	ReplacedWith    *string            `json:"replaced_with"`
	ReplacedAt      pgtype.Timestamptz `json:"replaced_at"`
	RestoredAt      pgtype.Timestamptz `json:"restored_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) (UpsertFileRow, error) {
	row := q.db.QueryRow(ctx, upsertFile,
		arg.ProjectID,
		arg.SourceTool,
		arg.RelPath,
		arg.OriginalContent,
		arg.ContentHash,
		arg.SizeBytes,
		arg.Status,
		arg.ReplacedWith,
	)
	var i UpsertFileRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceTool,
		&i.RelPath,
		&i.OriginalContent,
		&i.ContentHash,
		&i.SizeBytes,
		&i.Status,
		&i.ReplacedWith,
		&i.ReplacedAt,
		&i.RestoredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
