// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package feedbackdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateByDay = `-- name: AggregateByDay :many
SELECT COALESCE(skill_slug, '')::text AS skill_slug,
       (created_at AT TIME ZONE 'UTC')::date AS day,
       COUNT(*) FILTER (WHERE rating = 1)::int  AS count_up,
       COUNT(*) FILTER (WHERE rating = -1)::int AS count_down,
       MAX(created_at) AS last_feedback_at
FROM skill_feedback
WHERE created_at >= NOW() - make_interval(days => $1::int)
GROUP BY 1, 2
ORDER BY day DESC, skill_slug ASC
`

type AggregateByDayRow struct {
	SkillSlug      string      `json:"skill_slug"`
	Day            pgtype.Date `json:"day"`
	CountUp        int32       `json:"count_up"`
	CountDown      int32       `json:"count_down"`
	LastFeedbackAt interface{} `json:"last_feedback_at"`
}

// Agregados on-the-fly desde skill_feedback para los ultimos N dias.
// Usado por el handler GET y por el aggregator cron.
func (q *Queries) AggregateByDay(ctx context.Context, days int32) ([]AggregateByDayRow, error) {
	rows, err := q.db.Query(ctx, aggregateByDay, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateByDayRow
	for rows.Next() {
		var i AggregateByDayRow
		if err := rows.Scan(
			&i.SkillSlug,
			&i.Day,
			&i.CountUp,
			&i.CountDown,
			&i.LastFeedbackAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFeedbackBySkill = `-- name: CountFeedbackBySkill :one
SELECT COUNT(*)::bigint AS total
FROM skill_feedback
WHERE ($1::text = '' OR skill_slug = $1::text)
  AND ($2::smallint = 0 OR rating = $2::smallint)
`

type CountFeedbackBySkillParams struct {
	SkillSlug    string `json:"skill_slug"`
	RatingFilter int16  `json:"rating_filter"`
}

func (q *Queries) CountFeedbackBySkill(ctx context.Context, arg CountFeedbackBySkillParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFeedbackBySkill, arg.SkillSlug, arg.RatingFilter)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getFeedbackByMessage = `-- name: GetFeedbackByMessage :one
SELECT id, message_id,
       COALESCE(skill_slug, '')::text AS skill_slug,
       rating,
       COALESCE(comment, '')::text AS comment,
       COALESCE(user_email, '')::text AS user_email,
       created_at, updated_at
FROM skill_feedback
WHERE message_id = $1
`

type GetFeedbackByMessageRow struct {
	ID        uuid.UUID `json:"id"`
	MessageID int64     `json:"message_id"`
	SkillSlug string    `json:"skill_slug"`
	Rating    int16     `json:"rating"`
	Comment   string    `json:"comment"`
	UserEmail string    `json:"user_email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetFeedbackByMessage(ctx context.Context, messageID int64) (GetFeedbackByMessageRow, error) {
	row := q.db.QueryRow(ctx, getFeedbackByMessage, messageID)
	var i GetFeedbackByMessageRow
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.SkillSlug,
		&i.Rating,
		&i.Comment,
		&i.UserEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeedbackBySkill = `-- name: ListFeedbackBySkill :many
SELECT id, message_id,
       COALESCE(skill_slug, '')::text AS skill_slug,
       rating,
       COALESCE(comment, '')::text AS comment,
       COALESCE(user_email, '')::text AS user_email,
       created_at, updated_at
FROM skill_feedback
WHERE ($1::text = '' OR skill_slug = $1::text)
  AND ($2::smallint = 0 OR rating = $2::smallint)
ORDER BY created_at DESC, id DESC
LIMIT $4::int
OFFSET $3::int
`

type ListFeedbackBySkillParams struct {
	SkillSlug    string `json:"skill_slug"`
	RatingFilter int16  `json:"rating_filter"`
	ResultOffset int32  `json:"result_offset"`
	ResultLimit  int32  `json:"result_limit"`
}

type ListFeedbackBySkillRow struct {
	ID        uuid.UUID `json:"id"`
	MessageID int64     `json:"message_id"`
	SkillSlug string    `json:"skill_slug"`
	Rating    int16     `json:"rating"`
	Comment   string    `json:"comment"`
	UserEmail string    `json:"user_email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Paginado por (created_at, id) descendente. skill_slug vacio = sin filtro.
func (q *Queries) ListFeedbackBySkill(ctx context.Context, arg ListFeedbackBySkillParams) ([]ListFeedbackBySkillRow, error) {
	rows, err := q.db.Query(ctx, listFeedbackBySkill,
		arg.SkillSlug,
		arg.RatingFilter,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedbackBySkillRow
	for rows.Next() {
		var i ListFeedbackBySkillRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.SkillSlug,
			&i.Rating,
			&i.Comment,
			&i.UserEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeedback = `-- name: UpsertFeedback :one
INSERT INTO skill_feedback (message_id, skill_slug, rating, comment, user_email)
VALUES (
    $1,
    NULLIF($2, ''),
    $3,
    NULLIF($4, ''),
    NULLIF($5, '')
)
ON CONFLICT (message_id) DO UPDATE
SET skill_slug = NULLIF($2, ''),
    rating     = $3,
    comment    = NULLIF($4, ''),
    user_email = NULLIF($5, ''),
    updated_at = NOW()
RETURNING id, message_id,
          COALESCE(skill_slug, '')::text AS skill_slug,
          rating,
          COALESCE(comment, '')::text AS comment,
          COALESCE(user_email, '')::text AS user_email,
          created_at, updated_at
`

type UpsertFeedbackParams struct {
	MessageID int64       `json:"message_id"`
	SkillSlug interface{} `json:"skill_slug"`
	Rating    int16       `json:"rating"`
	Comment   interface{} `json:"comment"`
	UserEmail interface{} `json:"user_email"`
}

type UpsertFeedbackRow struct {
	ID        uuid.UUID `json:"id"`
	MessageID int64     `json:"message_id"`
	SkillSlug string    `json:"skill_slug"`
	Rating    int16     `json:"rating"`
	Comment   string    `json:"comment"`
	UserEmail string    `json:"user_email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Idempotente por message_id: el segundo submit del mismo mensaje hace UPDATE
// (cambia el rating/comment/skill_slug, refresca updated_at).
func (q *Queries) UpsertFeedback(ctx context.Context, arg UpsertFeedbackParams) (UpsertFeedbackRow, error) {
	row := q.db.QueryRow(ctx, upsertFeedback,
		arg.MessageID,
		arg.SkillSlug,
		arg.Rating,
		arg.Comment,
		arg.UserEmail,
	)
	var i UpsertFeedbackRow
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.SkillSlug,
		&i.Rating,
		&i.Comment,
		&i.UserEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFeedbackDaily = `-- name: UpsertFeedbackDaily :exec
INSERT INTO skill_feedback_daily (skill_slug, day, count_up, count_down, last_feedback_at, updated_at)
VALUES ($1, $2, $3,
        $4, $5, NOW())
ON CONFLICT (skill_slug, day) DO UPDATE
SET count_up         = $3,
    count_down       = $4,
    last_feedback_at = $5,
    updated_at       = NOW()
`

type UpsertFeedbackDailyParams struct {
	SkillSlug      string             `json:"skill_slug"`
	Day            pgtype.Date        `json:"day"`
	CountUp        int32              `json:"count_up"`
	CountDown      int32              `json:"count_down"`
	LastFeedbackAt pgtype.Timestamptz `json:"last_feedback_at"`
}

// Persiste un agregado diario (self-contained, NO skill_metrics).
func (q *Queries) UpsertFeedbackDaily(ctx context.Context, arg UpsertFeedbackDailyParams) error {
	_, err := q.db.Exec(ctx, upsertFeedbackDaily,
		arg.SkillSlug,
		arg.Day,
		arg.CountUp,
		arg.CountDown,
		arg.LastFeedbackAt,
	)
	return err
}
