package seeds

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"

	"nunezlagos/domain/internal/agentprotocol"
)

// PlatformPoliciesSeeder siembra las policies baseline de la plataforma
// (issue-01.7 + issue-01.8). DB como source of truth — markdown auto-generado.
type PlatformPoliciesSeeder struct{}

func (s *PlatformPoliciesSeeder) Name() string    { return "platform_policies" }
func (s *PlatformPoliciesSeeder) Version() int    { return 3 }
func (s *PlatformPoliciesSeeder) Order() int      { return 30 }
func (s *PlatformPoliciesSeeder) IsDevOnly() bool { return false }

type policyEntry struct {
	Slug, Name, Kind, BodyMD, SourceFile string
}

func (s *PlatformPoliciesSeeder) Run(ctx context.Context, tx pgx.Tx, env Env) (Report, error) {
	var rep Report

	policies := []policyEntry{
		{
			Slug:       "agent-protocol",
			Name:       "Protocolo de agente IA (memoria + policies + tools domain_*)",
			Kind:       "convention",
			SourceFile: "internal/agentprotocol/protocol.go",
			BodyMD:     agentprotocol.Full,
		},
		{
			Slug:       "sdd-tdd-strict",
			Name:       "TDD estricto para toda HU",
			Kind:       "sdd_workflow",
			SourceFile: ".claude/rules/sdd.md",
			BodyMD: `Cada HU sigue el ciclo TDD obligatorio:
1. Red: escribir test que falle por la razón correcta.
2. Green: mínima implementación para pasar el test.
3. Refactor: limpiar duplicación + naming + aplicar conventions.
4. Sabotaje: romper invariante intencionalmente → verificar que el test lo atrapa.

NUNCA implementar sin test. NUNCA commitear sin tests verdes locales.`,
		},
		{
			Slug:       "conventional-commits-spanish",
			Name:       "Conventional Commits en español sin Co-Authored-By",
			Kind:       "convention",
			SourceFile: ".claude/rules/git.md",
			BodyMD: `Format: <type>(<scope>)?: <description>
Types: feat, fix, perf, refactor, docs, test, build, ci, chore, style, revert.
Body en español. NUNCA Co-Authored-By IA. Un commit = una intención.
Breaking changes: feat!: ... o body con BREAKING CHANGE.`,
		},
		{
			Slug:       "secrets-redaction",
			Name:       "Secretos NUNCA en logs/métricas/traces",
			Kind:       "security_rule",
			SourceFile: ".claude/rules/security.md",
			BodyMD: `Lista bloqueada de keys en logs: password, secret, token, api_key,
otp, email, rut, phone, dob, address, pan, cvc, content, payload.
Usar campos seguros: email_hash (sha256 first 8), key_prefix, user_id (UUID),
content_length. PII redaction regex en issue-02.5.`,
		},
		{
			Slug:       "rls-defense-in-depth",
			Name:       "RLS obligatorio en tablas sensibles",
			Kind:       "security_rule",
			SourceFile: ".claude/rules/db.md",
			BodyMD: `Tablas en migration 000028 (auth_secrets, audit_log, auth_otp_codes,
activity_log, auth_api_keys) tienen RLS FORCE. Queries DEBEN envolver en
db.WithOrgTx para set_config('app.current_org_id'). Sabotaje: query sin
SET LOCAL → 0 rows. app_user es NOBYPASSRLS; app_admin BYPASSRLS solo
para auth path.`,
		},
		{
			Slug:       "migration-safety",
			Name:       "Migration safety rules",
			Kind:       "migration_rule",
			SourceFile: ".claude/rules/migrations.md",
			BodyMD: `Reglas duras:
- CREATE INDEX CONCURRENTLY siempre (override solo con squawk-ignore + reason)
- ALTER COLUMN NOT NULL requiere DEFAULT o backfill previo (expand/contract)
- DROP TABLE con IF EXISTS + CASCADE
- ADD FK con NOT VALID + VALIDATE posterior en tablas con datos
- Header obligatorio: migration, author, issue, description, breaking, duration
- Numeración secuencial 6 dígitos zero-padded; NUNCA renumerar`,
		},
		{
			Slug:       "low-cardinality-metrics",
			Name:       "Métricas Prometheus con baja cardinalidad",
			Kind:       "observability",
			SourceFile: ".claude/rules/observability.md",
			BodyMD: `NUNCA labels con: user_id, request_id, run_id, observation_id,
project_id, trace_id. org_id permitido solo si <10000 orgs.
issue-17.1 lint chequea regex _id="<uuid>" en /metrics response y falla CI.
Path normalization UUID→:id, numeric→:n previene explosion.`,
		},
		{
			Slug:       "clean-architecture-by-feature",
			Name:       "Clean Architecture por feature (no por capa técnica)",
			Kind:       "architecture",
			SourceFile: ".claude/rules/clean-architecture.md",
			BodyMD: `Dirs por feature: internal/{domain,service,store/pg,api,mcp}/{memory,
agent,flow,skill,...}/. NO "utils", NO "common", NO "helpers".
Dependency rule: domain ← service ← store/api/mcp. domain sin imports
externos. Interfaces en el package que las CONSUME.`,
		},
		{
			Slug:       "no-co-authored-ia",
			Name:       "Sin atribución IA en commits",
			Kind:       "convention",
			SourceFile: ".claude/rules/git.md",
			BodyMD: `NUNCA Co-Authored-By: Claude o similar. NUNCA "Generated by Claude
Code". El humano que dirigió la generación es el autor; la IA es
herramienta. Esta regla aplica a todos los commits del proyecto.`,
		},
		{
			Slug:       "local-only-repo",
			Name:       "Repo local-only hasta orden explícita",
			Kind:       "sdd_workflow",
			SourceFile: ".claude/rules/git.md",
			BodyMD: `NO push, NO git remote add, NO gh repo create sin orden explícita
del usuario. Branch main solo en .git/ local. CI workflows están
preparados pero no se ejecutarán hasta que exista remote.`,
		},
		{
			Slug:       "test-naming-convention",
			Name:       "Test naming Subject_Method_Scenario_Outcome",
			Kind:       "convention",
			SourceFile: ".claude/rules/testing.md",
			BodyMD: `Tests siguen: Test<Subject>_<Method>_<Scenario>_<ExpectedOutcome>.
Ej: TestUserService_CreateUser_DuplicateEmail_Returns409.
require.NoError(t, err) — no assert.Nil(t, err).
testcontainers para integration; build tag //go:build integration.
Sabotaje test obligatorio por HU.`,
		},
	}

	for _, p := range policies {

		tag, err := tx.Exec(ctx, `
			INSERT INTO platform_policies (slug, name, kind, body_md, source_file, is_active)
			VALUES ($1, $2, $3, $4, NULLIF($5, ''), TRUE)
			ON CONFLICT (slug, is_active) DO UPDATE
			SET name        = CASE WHEN platform_policies.is_user_modified THEN platform_policies.name        ELSE EXCLUDED.name        END,
			    kind        = CASE WHEN platform_policies.is_user_modified THEN platform_policies.kind        ELSE EXCLUDED.kind        END,
			    body_md     = CASE WHEN platform_policies.is_user_modified THEN platform_policies.body_md     ELSE EXCLUDED.body_md     END,
			    source_file = CASE WHEN platform_policies.is_user_modified THEN platform_policies.source_file ELSE EXCLUDED.source_file END`,
			p.Slug, p.Name, p.Kind, p.BodyMD, p.SourceFile,
		)
		if err != nil {
			return rep, fmt.Errorf("seed policy %s: %w", p.Slug, err)
		}
		if tag.RowsAffected() == 1 {
			rep.Created++
		} else {
			rep.Updated++
		}
	}
	return rep, nil
}
