package seeds

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"

	"nunezlagos/domain/internal/agentprotocol"
)

// PlatformPoliciesSeeder siembra las policies baseline de la plataforma
// (issue-01.7 + issue-01.8). DB como source of truth — markdown auto-generado.
type PlatformPoliciesSeeder struct{}

func (s *PlatformPoliciesSeeder) Name() string    { return "platform_policies" }
func (s *PlatformPoliciesSeeder) Version() int    { return 8 }
func (s *PlatformPoliciesSeeder) Order() int      { return 30 }
func (s *PlatformPoliciesSeeder) IsDevOnly() bool { return false }

type policyEntry struct {
	Slug, Name, Kind, BodyMD, SourceFile string
}

func (s *PlatformPoliciesSeeder) Run(ctx context.Context, tx pgx.Tx, env Env) (Report, error) {
	var rep Report

	policies := []policyEntry{
		{
			Slug:       "agent-protocol",
			Name:       "Protocolo de agente IA (memoria + policies + tools domain_*)",
			Kind:       "convention",
			SourceFile: "internal/agentprotocol/protocol.go",
			BodyMD:     agentprotocol.Full,
		},
		{
			Slug:       "sdd-tdd-strict",
			Name:       "TDD estricto para toda HU",
			Kind:       "sdd_workflow",
			SourceFile: ".claude/rules/sdd.md",
			BodyMD: `Cada HU sigue el ciclo TDD obligatorio:
1. Red: escribir test que falle por la razón correcta.
2. Green: mínima implementación para pasar el test.
3. Refactor: limpiar duplicación + naming + aplicar conventions.
4. Sabotaje: romper invariante intencionalmente → verificar que el test lo atrapa.

NUNCA implementar sin test. NUNCA commitear sin tests verdes locales.`,
		},
		{
			Slug:       "conventional-commits-spanish",
			Name:       "Conventional Commits en español sin Co-Authored-By",
			Kind:       "convention",
			SourceFile: ".claude/rules/git.md",
			BodyMD: `Format: <type>(<scope>)?: <description>
Types: feat, fix, perf, refactor, docs, test, build, ci, chore, style, revert.
Body en español. NUNCA Co-Authored-By IA. Un commit = una intención.
Breaking changes: feat!: ... o body con BREAKING CHANGE.`,
		},
		{
			Slug:       "secrets-redaction",
			Name:       "Secretos NUNCA en logs/métricas/traces",
			Kind:       "security_rule",
			SourceFile: ".claude/rules/security.md",
			BodyMD: `Lista bloqueada de keys en logs: password, secret, token, api_key,
otp, email, rut, phone, dob, address, pan, cvc, content, payload.
Usar campos seguros: email_hash (sha256 first 8), key_prefix, user_id (UUID),
content_length. PII redaction regex en issue-02.5.`,
		},
		{
			Slug:       "rls-defense-in-depth",
			Name:       "RLS obligatorio en tablas sensibles",
			Kind:       "security_rule",
			SourceFile: ".claude/rules/db.md",
			BodyMD: `Tablas en migration 000028 (auth_secrets, audit_log, auth_otp_codes,
activity_log, auth_api_keys) tienen RLS FORCE. Queries DEBEN envolver en
db.WithOrgTx para SET LOCAL app.current_org_id. Sabotaje: query sin
SET LOCAL → 0 rows. app_user es NOBYPASSRLS; app_admin BYPASSRLS solo
para auth path.
API canónica: Pool.BeginTx(ctx) + tx.Exec("SET LOCAL app.current_org_id = $1", orgID).
NO usar set_config() de PostgreSQL directamente — siempre a través de WithOrgTx.`,
		},
		{
			Slug:       "migration-safety",
			Name:       "Migration safety rules",
			Kind:       "migration_rule",
			SourceFile: ".claude/rules/migrations.md",
			BodyMD: `Reglas duras:
- CREATE INDEX CONCURRENTLY siempre (override solo con squawk-ignore + reason)
- ALTER COLUMN NOT NULL requiere DEFAULT o backfill previo (expand/contract)
- DROP TABLE con IF EXISTS + CASCADE
- ADD FK con NOT VALID + VALIDATE posterior en tablas con datos
- Header obligatorio: migration, author, issue, description, breaking, duration
- Numeración secuencial 6 dígitos zero-padded; NUNCA renumerar`,
		},
		{
			Slug:       "low-cardinality-metrics",
			Name:       "Métricas Prometheus con baja cardinalidad",
			Kind:       "observability",
			SourceFile: ".claude/rules/observability.md",
			BodyMD: `NUNCA labels con: user_id, request_id, run_id, observation_id,
project_id, trace_id. org_id permitido solo si <10000 orgs.
issue-17.1 lint chequea regex _id="<uuid>" en /metrics response y falla CI.
Path normalization UUID→:id, numeric→:n previene explosion.`,
		},
		{
			Slug:       "clean-architecture-by-feature",
			Name:       "Clean Architecture por feature (no por capa técnica)",
			Kind:       "architecture",
			SourceFile: ".claude/rules/clean-architecture.md",
			BodyMD: `Dirs por feature: internal/{domain,service,store/pg,api,mcp}/{memory,
agent,flow,skill,...}/. NO "utils", NO "common", NO "helpers".
Dependency rule: domain ← service ← store/api/mcp. domain sin imports
externos. Interfaces en el package que las CONSUME.`,
		},
		{
			Slug:       "no-co-authored-ia",
			Name:       "Sin atribución IA en commits",
			Kind:       "convention",
			SourceFile: ".claude/rules/git.md",
			BodyMD: `NUNCA Co-Authored-By: Claude o similar. NUNCA "Generated by Claude
Code". El humano que dirigió la generación es el autor; la IA es
herramienta. Esta regla aplica a todos los commits del proyecto.`,
		},
		{
			Slug:       "local-only-repo",
			Name:       "Repo local-only hasta orden explícita",
			Kind:       "sdd_workflow",
			SourceFile: ".claude/rules/git.md",
			BodyMD: `NO push, NO git remote add, NO gh repo create sin orden explícita
del usuario. Branch main solo en .git/ local. CI workflows están
preparados pero no se ejecutarán hasta que exista remote.`,
		},
		{
			Slug:       "test-naming-convention",
			Name:       "Test naming Subject_Method_Scenario_Outcome",
			Kind:       "convention",
			SourceFile: ".claude/rules/testing.md",
			BodyMD: `Tests siguen: Test<Subject>_<Method>_<Scenario>_<ExpectedOutcome>.
Ej: TestUserService_CreateUser_DuplicateEmail_Returns409.
require.NoError(t, err) — no assert.Nil(t, err).
testcontainers para integration; build tag //go:build integration.
Sabotaje test obligatorio por HU.`,
		},
		// ── Políticas v4: extraídas del análisis cross-project (9 proyectos Saargo) ──
		{
			Slug:       "openspec-spec-format",
			Name:       "OpenSpec: formato estándar de specs (RFC 2119)",
			Kind:       "sdd_workflow",
			SourceFile: "openspec/config.yaml",
			BodyMD: `OpenSpec specs siguen el estándar RFC 2119:
- MUST/SHALL: requisito absoluto — fallar = incumplimiento
- SHOULD: recomendado; excepciones permitidas si se documentan
- MAY: opcional, sin penalidad

LÍMITE: máximo 7 requisitos MUST por spec. Si hay más → dividir por área.

Cada requisito MUST tiene al menos 1 escenario con 4 hashtags:
#### Scenario: Descripción clara
Given [precondición]
When [acción usuario/sistema]
Then [resultado verificable]

Delta specs (modificaciones) incluyen el texto anterior completo:
## MODIFIED Requirements
REQ-XXX (anterior): [texto completo original]
REQ-XXX (nuevo): [texto completo modificado]

Sin ambigüedades: "rápido" no es válido, "< 200ms p95" sí.
Sin lenguaje de implementación: spec dice QUÉ, no CÓMO.`,
		},
		{
			Slug:       "openspec-naming-convention",
			Name:       "OpenSpec: naming verbal kebab-case para changes",
			Kind:       "sdd_workflow",
			SourceFile: "openspec/config.yaml",
			BodyMD: `Changes OpenSpec se nombran con prefijo verbal en kebab-case:
- add-: feature nueva (ej: add-exportar-csv)
- update-: modificar existente (ej: update-filtro-proyectos)
- remove-: eliminar funcionalidad (ej: remove-legacy-pdf-merger)
- refactor-: reestructurar sin cambiar comportamiento (ej: refactor-auth-service)
- fix-: corregir bug (ej: fix-token-expiration)

Formato: <prefijo>-<slug-kebab-case>
Un change = una intención. Si toca áreas no relacionadas → dividir.
No usar "implementar", "hacer", "tarea" como prefijos — son verbos de acción, no cambios.`,
		},
		{
			Slug:       "file-size-limit",
			Name:       "Límite de tamaño: archivos < 150 líneas, funciones < 30",
			Kind:       "convention",
			SourceFile: ".claude/rules/structure.md",
			BodyMD: `Límites de tamaño — aplicados a código nuevo:
- Archivos: < 150 líneas de código (excluye imports y comentarios de bloque)
- Funciones/métodos: < 30 líneas
- Controllers: sin lógica de negocio > 20 líneas (extraer a Service)
- Cada clase/módulo: una sola responsabilidad clara (SRP)

Si se excede el límite:
- Extraer funciones auxiliares a helpers/ o utils/
- Dividir en módulos más pequeños con responsabilidad única

Archivos existentes que excedan el límite son deuda técnica:
- No agregar código a ellos sin refactorizar primero
- Documentar como "deuda existente" en el design del change

Excepción única: archivos de migración de datos (seed/migration) que
son inherentemente largos por su naturaleza declarativa.`,
		},
		{
			Slug:       "yagni-simplicity",
			Name:       "YAGNI: < 100 líneas nuevas por change, no abstracciones prematuras",
			Kind:       "convention",
			SourceFile: ".claude/rules/architecture.md",
			BodyMD: `YAGNI (You Aren't Gonna Need It) es obligatorio en todo change:

REGLAS
- < 100 líneas de código nuevo por change como default
- Implementaciones single-file hasta que sea insuficiente (con evidencia)
- Complejidad adicional requiere justificación empírica: métricas concretas,
  > 1000 usuarios activos, o requisitos medibles explícitos
- 3 líneas similares > abstracción prematura
- NO error handling ni fallbacks para escenarios que no pueden ocurrir
- NO feature flags ni backward-compat shims cuando el código puede cambiarse directamente
- NO over-engineering: la implementación mínima que pasa los tests es la correcta

SEÑALES DE ABSTRACCIÓN PREMATURA
- "En el futuro podría..."
- "Para soportar N tipos diferentes..."
- "Separémoslo por si acaso..."
Si la justificación empieza así → no lo hagas.

EXCEPCIÓN: si hay métricas de producción que justifican la complejidad,
documentarlo en el design del change con los números concretos.`,
		},
		{
			Slug:       "audit-tasks-checklist",
			Name:       "Checklist de auditoría como última task de cada change",
			Kind:       "sdd_workflow",
			SourceFile: "openspec/config.yaml",
			BodyMD: `Toda lista de tasks DEBE incluir una task final de auditoría (sección "verify").
Esta task valida que el change completo cumple:

1. Ningún archivo nuevo supera 150 líneas de código
2. Todos los inputs del usuario están validados en el boundary del sistema
   (FormRequest, express-validator, Pydantic, etc.)
3. Sin secretos hardcodeados (API keys, passwords, tokens, rutas absolutas de prod)
4. Sin N+1 queries — eager loading aplicado en todas las relaciones iteradas
5. Código sigue convenciones del proyecto (naming, idioma, patrones establecidos)
6. Tests pasan localmente: php artisan test / npm test / go test / pytest
7. Sin código muerto (dd(), console.log, var_dump, print statements de debug)

Esta task no se puede marcar done si cualquiera de los criterios falla.
Es la última task de la lista — siempre, sin excepción.`,
		},
		{
			Slug:       "no-n-plus-one",
			Name:       "Sin queries N+1: eager loading obligatorio",
			Kind:       "convention",
			SourceFile: ".claude/rules/db.md",
			BodyMD: `N+1 queries son una violación crítica de performance:

PROHIBIDO
- Queries dentro de loops (foreach, map, for, while)
- Acceder a relaciones ORM sin eager loading cuando se itera una colección
- SELECT dentro de loops aunque sea "solo una tabla pequeña"

REQUERIDO por ORM/framework:
- Laravel Eloquent: with('relation') o load() antes de iterar colecciones
- Lucid ORM (AdonisJS): preload() en queries de listado
- SQLAlchemy: joinedload() o selectinload() en queries de colecciones
- Sequelize: include: [Model] en queries de listado
- Django: select_related() para FK, prefetch_related() para M2M

DETECCIÓN
- Habilitar query logger en dev y verificar que el count NO escala con N
- Si el número de queries crece linealmente con el tamaño del resultado → N+1
- EXPLAIN ANALYZE para confirmar: Seq Scan en tablas grandes es señal de alerta

ÍNDICES RELACIONADOS
Columnas usadas en JOIN y WHERE frecuentes deben tener índice.
CREATE INDEX CONCURRENTLY para no bloquear en tablas con datos.`,
		},
	}

	for _, p := range policies {

		tag, err := tx.Exec(ctx, `
			INSERT INTO platform_policies (slug, name, kind, body_md, source_file, is_active)
			VALUES ($1, $2, $3, $4, NULLIF($5, ''), TRUE)
			ON CONFLICT (slug, is_active) DO UPDATE
			SET name        = CASE WHEN platform_policies.is_user_modified THEN platform_policies.name        ELSE EXCLUDED.name        END,
			    kind        = CASE WHEN platform_policies.is_user_modified THEN platform_policies.kind        ELSE EXCLUDED.kind        END,
			    body_md     = CASE WHEN platform_policies.is_user_modified THEN platform_policies.body_md     ELSE EXCLUDED.body_md     END,
			    source_file = CASE WHEN platform_policies.is_user_modified THEN platform_policies.source_file ELSE EXCLUDED.source_file END`,
			p.Slug, p.Name, p.Kind, p.BodyMD, p.SourceFile,
		)
		if err != nil {
			return rep, fmt.Errorf("seed policy %s: %w", p.Slug, err)
		}
		if tag.RowsAffected() == 1 {
			rep.Created++
		} else {
			rep.Updated++
		}
	}
	return rep, nil
}
