// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package mcpinstallerdb

import (
	"context"
)

const listProviders = `-- name: ListProviders :many
SELECT name, description, command, default_args, env_template, required_env, tags
FROM mcp_providers
ORDER BY name
`

type ListProvidersRow struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Command     string   `json:"command"`
	DefaultArgs []string `json:"default_args"`
	EnvTemplate []byte   `json:"env_template"`
	RequiredEnv []string `json:"required_env"`
	Tags        []string `json:"tags"`
}

func (q *Queries) ListProviders(ctx context.Context) ([]ListProvidersRow, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProvidersRow
	for rows.Next() {
		var i ListProvidersRow
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.Command,
			&i.DefaultArgs,
			&i.EnvTemplate,
			&i.RequiredEnv,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
