// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package usagedb

import (
	"context"
	"time"
)

const getCounters = `-- name: GetCounters :one
SELECT
  (SELECT COUNT(*)::bigint FROM knowledge_observations
     WHERE knowledge_observations.created_at >= $1 AND knowledge_observations.created_at < $2 AND knowledge_observations.deleted_at IS NULL) AS observations,
  (SELECT COUNT(*)::bigint FROM agents
     WHERE agents.deleted_at IS NULL) AS agents,
  (SELECT COUNT(*)::bigint FROM agent_runs
     WHERE agent_runs.created_at >= $1 AND agent_runs.created_at < $2) AS agent_runs,
  (SELECT COUNT(*)::bigint FROM flow_runs
     WHERE flow_runs.created_at >= $1 AND flow_runs.created_at < $2) AS flow_runs
`

type GetCountersParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetCountersRow struct {
	Observations int64 `json:"observations"`
	Agents       int64 `json:"agents"`
	AgentRuns    int64 `json:"agent_runs"`
	FlowRuns     int64 `json:"flow_runs"`
}

func (q *Queries) GetCounters(ctx context.Context, arg GetCountersParams) (GetCountersRow, error) {
	row := q.db.QueryRow(ctx, getCounters, arg.CreatedAt, arg.CreatedAt_2)
	var i GetCountersRow
	err := row.Scan(
		&i.Observations,
		&i.Agents,
		&i.AgentRuns,
		&i.FlowRuns,
	)
	return i, err
}

const getMaxDuration = `-- name: GetMaxDuration :one
SELECT max_flow_duration_seconds FROM flow_config LIMIT 1
`

func (q *Queries) GetMaxDuration(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxDuration)
	var max_flow_duration_seconds int32
	err := row.Scan(&max_flow_duration_seconds)
	return max_flow_duration_seconds, err
}

const getObservationHistory = `-- name: GetObservationHistory :many
SELECT date_trunc('day', created_at AT TIME ZONE 'UTC')::date AS day,
       COUNT(*)::bigint AS count
FROM knowledge_observations
WHERE created_at >= $1 AND created_at < $2 AND deleted_at IS NULL
GROUP BY 1
`

type GetObservationHistoryParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetObservationHistoryRow struct {
	Day   time.Time `json:"day"`
	Count int64     `json:"count"`
}

func (q *Queries) GetObservationHistory(ctx context.Context, arg GetObservationHistoryParams) ([]GetObservationHistoryRow, error) {
	rows, err := q.db.Query(ctx, getObservationHistory, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetObservationHistoryRow
	for rows.Next() {
		var i GetObservationHistoryRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunHistory = `-- name: GetRunHistory :many
WITH series AS (
  SELECT generate_series($1::timestamptz, $2::timestamptz - interval '1 day', interval '1 day')::date AS day
),
agent_runs_agg AS (
  SELECT date_trunc('day', created_at AT TIME ZONE 'UTC')::date AS day,
         COUNT(*)::bigint AS count
  FROM agent_runs
  WHERE created_at >= $1 AND created_at < $2
  GROUP BY 1
),
flow_runs_agg AS (
  SELECT date_trunc('day', created_at AT TIME ZONE 'UTC')::date AS day,
         COUNT(*)::bigint AS count
  FROM flow_runs
  WHERE created_at >= $1 AND created_at < $2
  GROUP BY 1
)
SELECT s.day,
       COALESCE(a.count, 0)::bigint AS agent_runs,
       COALESCE(f.count, 0)::bigint AS flow_runs
FROM series s
LEFT JOIN agent_runs_agg a ON a.day = s.day
LEFT JOIN flow_runs_agg f ON f.day = s.day
ORDER BY s.day DESC
`

type GetRunHistoryParams struct {
	Column1 time.Time `json:"column_1"`
	Column2 time.Time `json:"column_2"`
}

type GetRunHistoryRow struct {
	Day       time.Time `json:"day"`
	AgentRuns int64     `json:"agent_runs"`
	FlowRuns  int64     `json:"flow_runs"`
}

func (q *Queries) GetRunHistory(ctx context.Context, arg GetRunHistoryParams) ([]GetRunHistoryRow, error) {
	rows, err := q.db.Query(ctx, getRunHistory, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRunHistoryRow
	for rows.Next() {
		var i GetRunHistoryRow
		if err := rows.Scan(&i.Day, &i.AgentRuns, &i.FlowRuns); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
