// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package projecttemplatedb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTemplate = `-- name: DeleteTemplate :execrows
DELETE FROM project_templates WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, slug, name, COALESCE(description, '')::text AS description,
    is_default, is_public, settings, default_skills, default_agents,
    default_flows, created_at, updated_at
FROM project_templates
WHERE id = $1
`

type GetTemplateByIDRow struct {
	ID            uuid.UUID `json:"id"`
	Slug          string    `json:"slug"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	IsDefault     bool      `json:"is_default"`
	IsPublic      bool      `json:"is_public"`
	Settings      []byte    `json:"settings"`
	DefaultSkills []string  `json:"default_skills"`
	DefaultAgents []string  `json:"default_agents"`
	DefaultFlows  []string  `json:"default_flows"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) GetTemplateByID(ctx context.Context, id uuid.UUID) (GetTemplateByIDRow, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i GetTemplateByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.IsPublic,
		&i.Settings,
		&i.DefaultSkills,
		&i.DefaultAgents,
		&i.DefaultFlows,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateBySlug = `-- name: GetTemplateBySlug :one
SELECT id, slug, name, COALESCE(description, '')::text AS description,
    is_default, is_public, settings, default_skills, default_agents,
    default_flows, created_at, updated_at
FROM project_templates
WHERE slug = $1
`

type GetTemplateBySlugRow struct {
	ID            uuid.UUID `json:"id"`
	Slug          string    `json:"slug"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	IsDefault     bool      `json:"is_default"`
	IsPublic      bool      `json:"is_public"`
	Settings      []byte    `json:"settings"`
	DefaultSkills []string  `json:"default_skills"`
	DefaultAgents []string  `json:"default_agents"`
	DefaultFlows  []string  `json:"default_flows"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) GetTemplateBySlug(ctx context.Context, slug string) (GetTemplateBySlugRow, error) {
	row := q.db.QueryRow(ctx, getTemplateBySlug, slug)
	var i GetTemplateBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.IsPublic,
		&i.Settings,
		&i.DefaultSkills,
		&i.DefaultAgents,
		&i.DefaultFlows,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTemplate = `-- name: InsertTemplate :one
INSERT INTO project_templates
    (slug, name, description, is_default, is_public,
     settings, default_skills, default_agents, default_flows)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at, updated_at
`

type InsertTemplateParams struct {
	Slug          string   `json:"slug"`
	Name          string   `json:"name"`
	Description   *string  `json:"description"`
	IsDefault     bool     `json:"is_default"`
	IsPublic      bool     `json:"is_public"`
	Settings      []byte   `json:"settings"`
	DefaultSkills []string `json:"default_skills"`
	DefaultAgents []string `json:"default_agents"`
	DefaultFlows  []string `json:"default_flows"`
}

type InsertTemplateRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InsertTemplate(ctx context.Context, arg InsertTemplateParams) (InsertTemplateRow, error) {
	row := q.db.QueryRow(ctx, insertTemplate,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.IsDefault,
		arg.IsPublic,
		arg.Settings,
		arg.DefaultSkills,
		arg.DefaultAgents,
		arg.DefaultFlows,
	)
	var i InsertTemplateRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, slug, name, COALESCE(description, '')::text AS description,
    is_default, is_public, settings, default_skills, default_agents,
    default_flows, created_at, updated_at
FROM project_templates
ORDER BY is_default DESC, name
`

type ListTemplatesRow struct {
	ID            uuid.UUID `json:"id"`
	Slug          string    `json:"slug"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	IsDefault     bool      `json:"is_default"`
	IsPublic      bool      `json:"is_public"`
	Settings      []byte    `json:"settings"`
	DefaultSkills []string  `json:"default_skills"`
	DefaultAgents []string  `json:"default_agents"`
	DefaultFlows  []string  `json:"default_flows"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListTemplates(ctx context.Context) ([]ListTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTemplatesRow
	for rows.Next() {
		var i ListTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IsDefault,
			&i.IsPublic,
			&i.Settings,
			&i.DefaultSkills,
			&i.DefaultAgents,
			&i.DefaultFlows,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
