// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package webhookdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Webhook struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	CreatedBy       *uuid.UUID         `json:"created_by"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	SecretEncrypted []byte             `json:"secret_encrypted"`
	SourceType      string             `json:"source_type"`
	TargetType      string             `json:"target_type"`
	TargetID        uuid.UUID          `json:"target_id"`
	InputsMapping   []byte             `json:"inputs_mapping"`
	Enabled         bool               `json:"enabled"`
	LastDeliveryAt  pgtype.Timestamptz `json:"last_delivery_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
