// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package costdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const dailyByAgent = `-- name: DailyByAgent :many
SELECT day, agent_id, agent_slug, runs, tokens_input, tokens_output, cost_usd
FROM domain_cost_daily_by_agent
WHERE day >= CURRENT_DATE - $1::int
ORDER BY day DESC, cost_usd DESC
`

type DailyByAgentRow struct {
	Day          time.Time      `json:"day"`
	AgentID      uuid.UUID      `json:"agent_id"`
	AgentSlug    string         `json:"agent_slug"`
	Runs         int64          `json:"runs"`
	TokensInput  int64          `json:"tokens_input"`
	TokensOutput int64          `json:"tokens_output"`
	CostUsd      pgtype.Numeric `json:"cost_usd"`
}

func (q *Queries) DailyByAgent(ctx context.Context, days int32) ([]DailyByAgentRow, error) {
	rows, err := q.db.Query(ctx, dailyByAgent, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyByAgentRow
	for rows.Next() {
		var i DailyByAgentRow
		if err := rows.Scan(
			&i.Day,
			&i.AgentID,
			&i.AgentSlug,
			&i.Runs,
			&i.TokensInput,
			&i.TokensOutput,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dailyByOrg = `-- name: DailyByOrg :many
SELECT day, runs, tokens_input, tokens_output, cost_usd, avg_duration_s,
       CAST(LAG(cost_usd) OVER (ORDER BY day) AS numeric) AS prev_cost_usd
FROM domain_cost_daily_by_org
WHERE day >= CURRENT_DATE - $1::int
ORDER BY day DESC
`

type DailyByOrgRow struct {
	Day          time.Time      `json:"day"`
	Runs         int64          `json:"runs"`
	TokensInput  int64          `json:"tokens_input"`
	TokensOutput int64          `json:"tokens_output"`
	CostUsd      pgtype.Numeric `json:"cost_usd"`
	AvgDurationS pgtype.Numeric `json:"avg_duration_s"`
	PrevCostUsd  pgtype.Numeric `json:"prev_cost_usd"`
}

func (q *Queries) DailyByOrg(ctx context.Context, days int32) ([]DailyByOrgRow, error) {
	rows, err := q.db.Query(ctx, dailyByOrg, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyByOrgRow
	for rows.Next() {
		var i DailyByOrgRow
		if err := rows.Scan(
			&i.Day,
			&i.Runs,
			&i.TokensInput,
			&i.TokensOutput,
			&i.CostUsd,
			&i.AvgDurationS,
			&i.PrevCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
