// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package timelinedb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAnchorObservation = `-- name: GetAnchorObservation :one
SELECT created_at, project_id, content
FROM knowledge_observations
WHERE id = $1 AND deleted_at IS NULL
`

type GetAnchorObservationRow struct {
	CreatedAt time.Time `json:"created_at"`
	ProjectID uuid.UUID `json:"project_id"`
	Content   string    `json:"content"`
}

func (q *Queries) GetAnchorObservation(ctx context.Context, observationID uuid.UUID) (GetAnchorObservationRow, error) {
	row := q.db.QueryRow(ctx, getAnchorObservation, observationID)
	var i GetAnchorObservationRow
	err := row.Scan(&i.CreatedAt, &i.ProjectID, &i.Content)
	return i, err
}

const listEntriesAfter = `-- name: ListEntriesAfter :many
SELECT 'observation'::text AS kind, ko.id, ko.observation_type, ko.content, ko.created_at
FROM knowledge_observations ko
WHERE ko.project_id = $2 AND ko.created_at > $3 AND ko.deleted_at IS NULL
UNION ALL
SELECT 'prompt'::text AS kind, p.id, p.slug, p.body, p.created_at
FROM prompts p
WHERE p.project_id = $2 AND p.created_at > $3 AND p.is_active = true AND p.deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $1
`

type ListEntriesAfterParams struct {
	Lim       int32     `json:"lim"`
	ProjectID uuid.UUID `json:"project_id"`
	Ts        time.Time `json:"ts"`
}

type ListEntriesAfterRow struct {
	Kind            string    `json:"kind"`
	ID              uuid.UUID `json:"id"`
	ObservationType string    `json:"observation_type"`
	Content         string    `json:"content"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) ListEntriesAfter(ctx context.Context, arg ListEntriesAfterParams) ([]ListEntriesAfterRow, error) {
	rows, err := q.db.Query(ctx, listEntriesAfter, arg.Lim, arg.ProjectID, arg.Ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesAfterRow
	for rows.Next() {
		var i ListEntriesAfterRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.ObservationType,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesBefore = `-- name: ListEntriesBefore :many
SELECT 'observation'::text AS kind, ko.id, ko.observation_type, ko.content, ko.created_at
FROM knowledge_observations ko
WHERE ko.project_id = $2 AND ko.created_at < $3 AND ko.deleted_at IS NULL
UNION ALL
SELECT 'prompt'::text AS kind, p.id, p.slug, p.body, p.created_at
FROM prompts p
WHERE p.project_id = $2 AND p.created_at < $3 AND p.is_active = true AND p.deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1
`

type ListEntriesBeforeParams struct {
	Lim       int32     `json:"lim"`
	ProjectID uuid.UUID `json:"project_id"`
	Ts        time.Time `json:"ts"`
}

type ListEntriesBeforeRow struct {
	Kind            string    `json:"kind"`
	ID              uuid.UUID `json:"id"`
	ObservationType string    `json:"observation_type"`
	Content         string    `json:"content"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) ListEntriesBefore(ctx context.Context, arg ListEntriesBeforeParams) ([]ListEntriesBeforeRow, error) {
	rows, err := q.db.Query(ctx, listEntriesBefore, arg.Lim, arg.ProjectID, arg.Ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesBeforeRow
	for rows.Next() {
		var i ListEntriesBeforeRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.ObservationType,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservations = `-- name: ListObservations :many
SELECT id, observation_type, content, created_at
FROM knowledge_observations
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1
`

type ListObservationsRow struct {
	ID              uuid.UUID `json:"id"`
	ObservationType string    `json:"observation_type"`
	Content         string    `json:"content"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) ListObservations(ctx context.Context, lim int32) ([]ListObservationsRow, error) {
	rows, err := q.db.Query(ctx, listObservations, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListObservationsRow
	for rows.Next() {
		var i ListObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ObservationType,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByProject = `-- name: ListObservationsByProject :many
SELECT id, observation_type, content, created_at
FROM knowledge_observations
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListObservationsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Lim       int32     `json:"lim"`
}

type ListObservationsByProjectRow struct {
	ID              uuid.UUID `json:"id"`
	ObservationType string    `json:"observation_type"`
	Content         string    `json:"content"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) ListObservationsByProject(ctx context.Context, arg ListObservationsByProjectParams) ([]ListObservationsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listObservationsByProject, arg.ProjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListObservationsByProjectRow
	for rows.Next() {
		var i ListObservationsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ObservationType,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrompts = `-- name: ListPrompts :many
SELECT id, slug, body, created_at
FROM prompts
WHERE is_active = true AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1
`

type ListPromptsRow struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListPrompts(ctx context.Context, lim int32) ([]ListPromptsRow, error) {
	rows, err := q.db.Query(ctx, listPrompts, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromptsRow
	for rows.Next() {
		var i ListPromptsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptsByProject = `-- name: ListPromptsByProject :many
SELECT id, slug, body, created_at
FROM prompts
WHERE project_id = $1 AND is_active = true AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListPromptsByProjectParams struct {
	ProjectID *uuid.UUID `json:"project_id"`
	Lim       int32      `json:"lim"`
}

type ListPromptsByProjectRow struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListPromptsByProject(ctx context.Context, arg ListPromptsByProjectParams) ([]ListPromptsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listPromptsByProject, arg.ProjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromptsByProjectRow
	for rows.Next() {
		var i ListPromptsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
