// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package skillabtestdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SkillAbTest struct {
	ID              uuid.UUID          `json:"id"`
	SkillSlug       string             `json:"skill_slug"`
	VersionA        int32              `json:"version_a"`
	VersionB        int32              `json:"version_b"`
	TrafficSplitA   pgtype.Numeric     `json:"traffic_split_a"`
	MinInvocations  int32              `json:"min_invocations"`
	AutoApplyWinner bool               `json:"auto_apply_winner"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	Winner          *string            `json:"winner"`
	Confidence      pgtype.Numeric     `json:"confidence"`
	Status          string             `json:"status"`
	CreatedBy       *uuid.UUID         `json:"created_by"`
	CreatedAt       time.Time          `json:"created_at"`
}
