// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package skillabtestdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelABTest = `-- name: CancelABTest :exec
UPDATE skill_ab_tests
SET status   = 'cancelled',
    ended_at = NOW()
WHERE id = $1 AND status = 'running'
`

func (q *Queries) CancelABTest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelABTest, id)
	return err
}

const createABTest = `-- name: CreateABTest :one

INSERT INTO skill_ab_tests (
    skill_slug, version_a, version_b, traffic_split_a,
    min_invocations, auto_apply_winner, started_at, status, created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, skill_slug, version_a, version_b, traffic_split_a, min_invocations,
          auto_apply_winner, started_at, ended_at, winner, confidence, status,
          created_by, created_at
`

type CreateABTestParams struct {
	SkillSlug       string             `json:"skill_slug"`
	VersionA        int32              `json:"version_a"`
	VersionB        int32              `json:"version_b"`
	TrafficSplitA   pgtype.Numeric     `json:"traffic_split_a"`
	MinInvocations  int32              `json:"min_invocations"`
	AutoApplyWinner bool               `json:"auto_apply_winner"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	Status          string             `json:"status"`
	CreatedBy       *uuid.UUID         `json:"created_by"`
}

// HU-52.4 — A/B testing de prompts.
//
// skill_ab_tests define el experimento; skill_ab_test_results acumula por
// variante. El opt-in se deriva de GetRunningBySlug (status='running'): si NO hay
// fila, el Router cae al pin normal del skill. Single-tenant (regla dura 1): NADA
// de organization_id en ninguna query (ni en skills, que NO la tiene en runtime
// desde mig 000142; bug HU-52.3 a NO repetir).
// Crea un experimento. status arranca 'running' por default en el DDL; started_at
// lo setea Start (o este mismo Create cuando se arranca de inmediato). El indice
// parcial skill_ab_tests_running_uniq garantiza UN solo running por slug.
func (q *Queries) CreateABTest(ctx context.Context, arg CreateABTestParams) (SkillAbTest, error) {
	row := q.db.QueryRow(ctx, createABTest,
		arg.SkillSlug,
		arg.VersionA,
		arg.VersionB,
		arg.TrafficSplitA,
		arg.MinInvocations,
		arg.AutoApplyWinner,
		arg.StartedAt,
		arg.Status,
		arg.CreatedBy,
	)
	var i SkillAbTest
	err := row.Scan(
		&i.ID,
		&i.SkillSlug,
		&i.VersionA,
		&i.VersionB,
		&i.TrafficSplitA,
		&i.MinInvocations,
		&i.AutoApplyWinner,
		&i.StartedAt,
		&i.EndedAt,
		&i.Winner,
		&i.Confidence,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const declareWinner = `-- name: DeclareWinner :exec
UPDATE skill_ab_tests
SET winner     = $1,
    confidence = $2,
    status     = 'completed',
    ended_at   = NOW()
WHERE id = $3 AND status = 'running'
`

type DeclareWinnerParams struct {
	Winner     *string        `json:"winner"`
	Confidence pgtype.Numeric `json:"confidence"`
	ID         uuid.UUID      `json:"id"`
}

// Cierra el experimento con un ganador (a|b|inconclusive). Solo aplica a tests
// 'running' (idempotente: un test ya completed no se re-cierra).
func (q *Queries) DeclareWinner(ctx context.Context, arg DeclareWinnerParams) error {
	_, err := q.db.Exec(ctx, declareWinner, arg.Winner, arg.Confidence, arg.ID)
	return err
}

const getABTest = `-- name: GetABTest :one
SELECT id, skill_slug, version_a, version_b, traffic_split_a, min_invocations,
       auto_apply_winner, started_at, ended_at, winner, confidence, status,
       created_by, created_at
FROM skill_ab_tests
WHERE id = $1
`

func (q *Queries) GetABTest(ctx context.Context, id uuid.UUID) (SkillAbTest, error) {
	row := q.db.QueryRow(ctx, getABTest, id)
	var i SkillAbTest
	err := row.Scan(
		&i.ID,
		&i.SkillSlug,
		&i.VersionA,
		&i.VersionB,
		&i.TrafficSplitA,
		&i.MinInvocations,
		&i.AutoApplyWinner,
		&i.StartedAt,
		&i.EndedAt,
		&i.Winner,
		&i.Confidence,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getResults = `-- name: GetResults :many
SELECT ab_test_id, version, invocations_count, success_count,
       success_rate::float8 AS success_rate,
       avg_feedback::float8 AS avg_feedback,
       updated_at
FROM skill_ab_test_results
WHERE ab_test_id = $1
ORDER BY version ASC
`

type GetResultsRow struct {
	AbTestID         uuid.UUID `json:"ab_test_id"`
	Version          string    `json:"version"`
	InvocationsCount int32     `json:"invocations_count"`
	SuccessCount     int32     `json:"success_count"`
	SuccessRate      float64   `json:"success_rate"`
	AvgFeedback      float64   `json:"avg_feedback"`
	UpdatedAt        time.Time `json:"updated_at"`
}

// Resultados de ambas variantes de un test (a luego b).
func (q *Queries) GetResults(ctx context.Context, abTestID uuid.UUID) ([]GetResultsRow, error) {
	rows, err := q.db.Query(ctx, getResults, abTestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResultsRow
	for rows.Next() {
		var i GetResultsRow
		if err := rows.Scan(
			&i.AbTestID,
			&i.Version,
			&i.InvocationsCount,
			&i.SuccessCount,
			&i.SuccessRate,
			&i.AvgFeedback,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunningBySlug = `-- name: GetRunningBySlug :one
SELECT id, skill_slug, version_a, version_b, traffic_split_a, min_invocations,
       auto_apply_winner, started_at, ended_at, winner, confidence, status,
       created_by, created_at
FROM skill_ab_tests
WHERE skill_slug = $1 AND status = 'running'
`

// El Router consulta esto en request-time. A lo sumo una fila (indice parcial).
func (q *Queries) GetRunningBySlug(ctx context.Context, skillSlug string) (SkillAbTest, error) {
	row := q.db.QueryRow(ctx, getRunningBySlug, skillSlug)
	var i SkillAbTest
	err := row.Scan(
		&i.ID,
		&i.SkillSlug,
		&i.VersionA,
		&i.VersionB,
		&i.TrafficSplitA,
		&i.MinInvocations,
		&i.AutoApplyWinner,
		&i.StartedAt,
		&i.EndedAt,
		&i.Winner,
		&i.Confidence,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const incrementResult = `-- name: IncrementResult :exec
INSERT INTO skill_ab_test_results (
    ab_test_id, version, invocations_count, success_count, success_rate, updated_at
) VALUES (
    $1, $2,
    1, $3,
    ROUND($3::numeric * 100, 2),
    NOW()
)
ON CONFLICT (ab_test_id, version) DO UPDATE
SET invocations_count = skill_ab_test_results.invocations_count + 1,
    success_count     = skill_ab_test_results.success_count + $3,
    success_rate      = ROUND(
        (skill_ab_test_results.success_count + $3)::numeric * 100
        / (skill_ab_test_results.invocations_count + 1), 2),
    updated_at        = NOW()
`

type IncrementResultParams struct {
	AbTestID     uuid.UUID `json:"ab_test_id"`
	Version      string    `json:"version"`
	SuccessDelta int32     `json:"success_delta"`
}

// Suma una invocacion (y opcionalmente un exito) a una variante, recomputando
// success_rate. Lo usa el Router/feedback path en caliente. Crea la fila si no
// existe (ON CONFLICT). avg_feedback se deja igual (lo recalcula el analyzer).
func (q *Queries) IncrementResult(ctx context.Context, arg IncrementResultParams) error {
	_, err := q.db.Exec(ctx, incrementResult, arg.AbTestID, arg.Version, arg.SuccessDelta)
	return err
}

const listRunningABTests = `-- name: ListRunningABTests :many
SELECT id, skill_slug, version_a, version_b, traffic_split_a, min_invocations,
       auto_apply_winner, started_at, ended_at, winner, confidence, status,
       created_by, created_at
FROM skill_ab_tests
WHERE status = 'running'
ORDER BY created_at ASC
`

// El cron analyzer itera sobre todos los running cada pasada.
func (q *Queries) ListRunningABTests(ctx context.Context) ([]SkillAbTest, error) {
	rows, err := q.db.Query(ctx, listRunningABTests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillAbTest
	for rows.Next() {
		var i SkillAbTest
		if err := rows.Scan(
			&i.ID,
			&i.SkillSlug,
			&i.VersionA,
			&i.VersionB,
			&i.TrafficSplitA,
			&i.MinInvocations,
			&i.AutoApplyWinner,
			&i.StartedAt,
			&i.EndedAt,
			&i.Winner,
			&i.Confidence,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinSkillVersion = `-- name: PinSkillVersion :exec
UPDATE skills
SET pinned_version = $1
WHERE id = $2
`

type PinSkillVersionParams struct {
	Version *int32    `json:"version"`
	ID      uuid.UUID `json:"id"`
}

// Pinea la version ganadora en el skill (auto_apply_winner=TRUE). Single-tenant:
// WHERE solo por id, SIN organization_id (bug HU-52.3 a NO repetir).
func (q *Queries) PinSkillVersion(ctx context.Context, arg PinSkillVersionParams) error {
	_, err := q.db.Exec(ctx, pinSkillVersion, arg.Version, arg.ID)
	return err
}

const skillIDBySlug = `-- name: SkillIDBySlug :one
SELECT id
FROM skills
WHERE slug = $1 AND deleted_at IS NULL
LIMIT 1
`

// Resuelve el skill_id (vivo) desde el slug. Lo usa el auto-apply del ganador
// para pinear la version via skill_versions/pinned_version. JAMAS toca
// organization_id (no existe en skills en runtime, mig 000142).
func (q *Queries) SkillIDBySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, skillIDBySlug, slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const startABTest = `-- name: StartABTest :exec
UPDATE skill_ab_tests
SET started_at = COALESCE(started_at, NOW())
WHERE id = $1 AND status = 'running'
`

// Marca started_at (idempotente: solo si aun esta running sin started_at). El
// estado ya es 'running' por default; esto solo registra el arranque temporal.
func (q *Queries) StartABTest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, startABTest, id)
	return err
}

const upsertResult = `-- name: UpsertResult :exec
INSERT INTO skill_ab_test_results (
    ab_test_id, version, invocations_count, success_count,
    success_rate, avg_feedback, updated_at
) VALUES (
    $1, $2,
    $3, $4,
    $5, $6, NOW()
)
ON CONFLICT (ab_test_id, version) DO UPDATE
SET invocations_count = $3,
    success_count     = $4,
    success_rate      = $5,
    avg_feedback      = $6,
    updated_at        = NOW()
`

type UpsertResultParams struct {
	AbTestID         uuid.UUID      `json:"ab_test_id"`
	Version          string         `json:"version"`
	InvocationsCount int32          `json:"invocations_count"`
	SuccessCount     int32          `json:"success_count"`
	SuccessRate      pgtype.Numeric `json:"success_rate"`
	AvgFeedback      pgtype.Numeric `json:"avg_feedback"`
}

// Persiste (idempotente por PK) el agregado de una variante. Lo usa tanto el
// recorder incremental (RecordResult) como el recompute del analyzer.
func (q *Queries) UpsertResult(ctx context.Context, arg UpsertResultParams) error {
	_, err := q.db.Exec(ctx, upsertResult,
		arg.AbTestID,
		arg.Version,
		arg.InvocationsCount,
		arg.SuccessCount,
		arg.SuccessRate,
		arg.AvgFeedback,
	)
	return err
}
