// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package knowledgedb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

const getChunks = `-- name: GetChunks :many
SELECT id, knowledge_doc_id, chunk_index, content, created_at
FROM knowledge_chunks
WHERE knowledge_doc_id = $1
ORDER BY chunk_index ASC
`

type GetChunksRow struct {
	ID             uuid.UUID `json:"id"`
	KnowledgeDocID uuid.UUID `json:"knowledge_doc_id"`
	ChunkIndex     int32     `json:"chunk_index"`
	Content        string    `json:"content"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) GetChunks(ctx context.Context, knowledgeDocID uuid.UUID) ([]GetChunksRow, error) {
	rows, err := q.db.Query(ctx, getChunks, knowledgeDocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChunksRow
	for rows.Next() {
		var i GetChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeDocID,
			&i.ChunkIndex,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDoc = `-- name: GetDoc :one
SELECT id, project_id, created_by, title, body, source,
       source_url,
       tags, metadata, has_attachments, created_at, updated_at
FROM knowledge_docs
WHERE id = $1 AND deleted_at IS NULL
`

type GetDocRow struct {
	ID             uuid.UUID  `json:"id"`
	ProjectID      uuid.UUID  `json:"project_id"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	Title          string     `json:"title"`
	Body           string     `json:"body"`
	Source         string     `json:"source"`
	SourceUrl      *string    `json:"source_url"`
	Tags           []string   `json:"tags"`
	Metadata       []byte     `json:"metadata"`
	HasAttachments bool       `json:"has_attachments"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

func (q *Queries) GetDoc(ctx context.Context, id uuid.UUID) (GetDocRow, error) {
	row := q.db.QueryRow(ctx, getDoc, id)
	var i GetDocRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.SourceUrl,
		&i.Tags,
		&i.Metadata,
		&i.HasAttachments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChunk = `-- name: InsertChunk :one
INSERT INTO knowledge_chunks (knowledge_doc_id, chunk_index, content, embedding)
VALUES ($1, $2, $3, $4::vector)
RETURNING id, knowledge_doc_id, chunk_index, content, created_at
`

type InsertChunkParams struct {
	KnowledgeDocID uuid.UUID        `json:"knowledge_doc_id"`
	ChunkIndex     int32            `json:"chunk_index"`
	Content        string           `json:"content"`
	Embedding      *pgvector.Vector `json:"embedding"`
}

type InsertChunkRow struct {
	ID             uuid.UUID `json:"id"`
	KnowledgeDocID uuid.UUID `json:"knowledge_doc_id"`
	ChunkIndex     int32     `json:"chunk_index"`
	Content        string    `json:"content"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) (InsertChunkRow, error) {
	row := q.db.QueryRow(ctx, insertChunk,
		arg.KnowledgeDocID,
		arg.ChunkIndex,
		arg.Content,
		arg.Embedding,
	)
	var i InsertChunkRow
	err := row.Scan(
		&i.ID,
		&i.KnowledgeDocID,
		&i.ChunkIndex,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const insertDoc = `-- name: InsertDoc :one
INSERT INTO knowledge_docs (
    project_id, created_by, title, body, source, source_url, tags, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, project_id, created_by, title, body, source,
          source_url,
          tags, metadata, has_attachments, created_at, updated_at
`

type InsertDocParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	CreatedBy *uuid.UUID `json:"created_by"`
	Title     string     `json:"title"`
	Body      string     `json:"body"`
	Source    string     `json:"source"`
	SourceUrl *string    `json:"source_url"`
	Tags      []string   `json:"tags"`
	Metadata  []byte     `json:"metadata"`
}

type InsertDocRow struct {
	ID             uuid.UUID  `json:"id"`
	ProjectID      uuid.UUID  `json:"project_id"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	Title          string     `json:"title"`
	Body           string     `json:"body"`
	Source         string     `json:"source"`
	SourceUrl      *string    `json:"source_url"`
	Tags           []string   `json:"tags"`
	Metadata       []byte     `json:"metadata"`
	HasAttachments bool       `json:"has_attachments"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

func (q *Queries) InsertDoc(ctx context.Context, arg InsertDocParams) (InsertDocRow, error) {
	row := q.db.QueryRow(ctx, insertDoc,
		arg.ProjectID,
		arg.CreatedBy,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.SourceUrl,
		arg.Tags,
		arg.Metadata,
	)
	var i InsertDocRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.SourceUrl,
		&i.Tags,
		&i.Metadata,
		&i.HasAttachments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocsByProject = `-- name: ListDocsByProject :many
SELECT id, project_id, created_by, title, body, source,
       source_url,
       tags, metadata, has_attachments, created_at, updated_at
FROM knowledge_docs
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2::int
`

type ListDocsByProjectParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	ResultLimit int32     `json:"result_limit"`
}

type ListDocsByProjectRow struct {
	ID             uuid.UUID  `json:"id"`
	ProjectID      uuid.UUID  `json:"project_id"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	Title          string     `json:"title"`
	Body           string     `json:"body"`
	Source         string     `json:"source"`
	SourceUrl      *string    `json:"source_url"`
	Tags           []string   `json:"tags"`
	Metadata       []byte     `json:"metadata"`
	HasAttachments bool       `json:"has_attachments"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

func (q *Queries) ListDocsByProject(ctx context.Context, arg ListDocsByProjectParams) ([]ListDocsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listDocsByProject, arg.ProjectID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocsByProjectRow
	for rows.Next() {
		var i ListDocsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CreatedBy,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.SourceUrl,
			&i.Tags,
			&i.Metadata,
			&i.HasAttachments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBm25 = `-- name: SearchBm25 :many
SELECT c.id, c.knowledge_doc_id, c.chunk_index, d.title, c.content,
       d.project_id, c.created_at,
       ts_rank(c.content_tsv, q)::float8 AS score
FROM knowledge_chunks c
JOIN knowledge_docs d ON d.id = c.knowledge_doc_id
     AND d.deleted_at IS NULL,
     plainto_tsquery('spanish', $1) AS q
WHERE c.content_tsv @@ q
ORDER BY score DESC
LIMIT $2::int
`

type SearchBm25Params struct {
	QueryText   string `json:"query_text"`
	ResultLimit int32  `json:"result_limit"`
}

type SearchBm25Row struct {
	ID             uuid.UUID `json:"id"`
	KnowledgeDocID uuid.UUID `json:"knowledge_doc_id"`
	ChunkIndex     int32     `json:"chunk_index"`
	Title          string    `json:"title"`
	Content        string    `json:"content"`
	ProjectID      uuid.UUID `json:"project_id"`
	CreatedAt      time.Time `json:"created_at"`
	Score          float64   `json:"score"`
}

func (q *Queries) SearchBm25(ctx context.Context, arg SearchBm25Params) ([]SearchBm25Row, error) {
	rows, err := q.db.Query(ctx, searchBm25, arg.QueryText, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBm25Row
	for rows.Next() {
		var i SearchBm25Row
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeDocID,
			&i.ChunkIndex,
			&i.Title,
			&i.Content,
			&i.ProjectID,
			&i.CreatedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHybrid = `-- name: SearchHybrid :many
WITH bm25 AS (
  SELECT c.id, ROW_NUMBER() OVER (ORDER BY ts_rank(c.content_tsv, q) DESC) AS r
  FROM knowledge_chunks c
  JOIN knowledge_docs d ON d.id = c.knowledge_doc_id
       AND d.deleted_at IS NULL,
       plainto_tsquery('spanish', $2) AS q
  WHERE c.content_tsv @@ q
  LIMIT $3::int
),
vec AS (
  SELECT c.id, ROW_NUMBER() OVER (ORDER BY c.embedding <=> $4::vector ASC) AS r
  FROM knowledge_chunks c
  JOIN knowledge_docs d ON d.id = c.knowledge_doc_id
       AND d.deleted_at IS NULL
  WHERE c.embedding IS NOT NULL
  LIMIT $3::int
),
fused AS (
  SELECT COALESCE(bm25.id, vec.id) AS id,
         COALESCE(1.0 / ($5::int + bm25.r), 0) + COALESCE(1.0 / ($5::int + vec.r), 0) AS score
  FROM bm25 FULL OUTER JOIN vec ON bm25.id = vec.id
)
SELECT c.id, c.knowledge_doc_id, c.chunk_index, d.title, c.content,
       d.project_id, c.created_at, fused.score::float8 AS score
FROM fused
JOIN knowledge_chunks c ON c.id = fused.id
JOIN knowledge_docs d ON d.id = c.knowledge_doc_id
ORDER BY fused.score DESC
LIMIT $1::int
`

type SearchHybridParams struct {
	ResultLimit int32            `json:"result_limit"`
	QueryText   string           `json:"query_text"`
	Candidates  int32            `json:"candidates"`
	QueryVec    *pgvector.Vector `json:"query_vec"`
	RrfK        int32            `json:"rrf_k"`
}

type SearchHybridRow struct {
	ID             uuid.UUID `json:"id"`
	KnowledgeDocID uuid.UUID `json:"knowledge_doc_id"`
	ChunkIndex     int32     `json:"chunk_index"`
	Title          string    `json:"title"`
	Content        string    `json:"content"`
	ProjectID      uuid.UUID `json:"project_id"`
	CreatedAt      time.Time `json:"created_at"`
	Score          float64   `json:"score"`
}

func (q *Queries) SearchHybrid(ctx context.Context, arg SearchHybridParams) ([]SearchHybridRow, error) {
	rows, err := q.db.Query(ctx, searchHybrid,
		arg.ResultLimit,
		arg.QueryText,
		arg.Candidates,
		arg.QueryVec,
		arg.RrfK,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchHybridRow
	for rows.Next() {
		var i SearchHybridRow
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeDocID,
			&i.ChunkIndex,
			&i.Title,
			&i.Content,
			&i.ProjectID,
			&i.CreatedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDoc = `-- name: SoftDeleteDoc :execrows
UPDATE knowledge_docs SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDoc(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDoc, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
