// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package codegraphdb

import (
	"time"

	"github.com/google/uuid"
)

type CodeEdge struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"project_id"`
	SourceNodeID uuid.UUID `json:"source_node_id"`
	TargetNodeID uuid.UUID `json:"target_node_id"`
	EdgeType     string    `json:"edge_type"`
	Metadata     []byte    `json:"metadata"`
	CreatedAt    time.Time `json:"created_at"`
}

type CodeIndexFile struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	FilePath    string    `json:"file_path"`
	ContentHash []byte    `json:"content_hash"`
	GitHead     *string   `json:"git_head"`
	NodeCount   *int32    `json:"node_count"`
	IndexedAt   time.Time `json:"indexed_at"`
}
