// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package codegraphdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteEdgesBySourceNodes = `-- name: DeleteEdgesBySourceNodes :execrows
DELETE FROM code_edges
WHERE project_id = $1
  AND source_node_id = ANY($2::uuid[])
`

type DeleteEdgesBySourceNodesParams struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	SourceNodeIds []uuid.UUID `json:"source_node_ids"`
}

// Borra (hard) todas las aristas salientes de un conjunto de nodos source.
// Se usa al re-parsear un archivo: primero se limpian las aristas de sus nodos.
func (q *Queries) DeleteEdgesBySourceNodes(ctx context.Context, arg DeleteEdgesBySourceNodesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEdgesBySourceNodes, arg.ProjectID, arg.SourceNodeIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEdgesByTargetNodes = `-- name: DeleteEdgesByTargetNodes :execrows
DELETE FROM code_edges
WHERE project_id = $1
  AND target_node_id = ANY($2::uuid[])
`

type DeleteEdgesByTargetNodesParams struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	TargetNodeIds []uuid.UUID `json:"target_node_ids"`
}

// Borra (hard) todas las aristas ENTRANTES de un conjunto de nodos target. Se usa
// cuando un nodo deja de existir (re-parseo que lo elimina o archivo borrado):
// las aristas que apuntaban a él desde OTROS archivos quedarían colgando porque
// soft-delete es UPDATE y no dispara el ON DELETE CASCADE. Hard-delete evita
// aristas huérfanas hacia nodos muertos.
func (q *Queries) DeleteEdgesByTargetNodes(ctx context.Context, arg DeleteEdgesByTargetNodesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEdgesByTargetNodes, arg.ProjectID, arg.TargetNodeIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIndexFile = `-- name: DeleteIndexFile :execrows
DELETE FROM code_index_files
WHERE project_id = $1
  AND file_path = $2
`

type DeleteIndexFileParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	FilePath  string    `json:"file_path"`
}

func (q *Queries) DeleteIndexFile(ctx context.Context, arg DeleteIndexFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIndexFile, arg.ProjectID, arg.FilePath)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCodeNodeProject = `-- name: GetCodeNodeProject :one

SELECT id, project_id
FROM code_nodes
WHERE id = $1
  AND deleted_at IS NULL
`

type GetCodeNodeProjectRow struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

// ---------------------------------------------------------------------------
// Observation <-> Code links (cruce memoria/código, mig 000179)
// ---------------------------------------------------------------------------
// Devuelve el project del nodo (para validar mismo-project en el cruce).
func (q *Queries) GetCodeNodeProject(ctx context.Context, id uuid.UUID) (GetCodeNodeProjectRow, error) {
	row := q.db.QueryRow(ctx, getCodeNodeProject, id)
	var i GetCodeNodeProjectRow
	err := row.Scan(&i.ID, &i.ProjectID)
	return i, err
}

const getIndexFile = `-- name: GetIndexFile :one
SELECT id, project_id, file_path, content_hash, git_head,
       node_count, indexed_at
FROM code_index_files
WHERE project_id = $1
  AND file_path = $2
`

type GetIndexFileParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	FilePath  string    `json:"file_path"`
}

func (q *Queries) GetIndexFile(ctx context.Context, arg GetIndexFileParams) (CodeIndexFile, error) {
	row := q.db.QueryRow(ctx, getIndexFile, arg.ProjectID, arg.FilePath)
	var i CodeIndexFile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FilePath,
		&i.ContentHash,
		&i.GitHead,
		&i.NodeCount,
		&i.IndexedAt,
	)
	return i, err
}

const getNodeByQualified = `-- name: GetNodeByQualified :one
SELECT id, project_id, kind, name, qualified_name, file_path,
       line_start, line_end, signature, doc, language, content_hash,
       metadata, created_at, updated_at
FROM code_nodes
WHERE project_id = $1
  AND qualified_name = $2
  AND kind = $3
  AND deleted_at IS NULL
`

type GetNodeByQualifiedParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	QualifiedName *string   `json:"qualified_name"`
	Kind          string    `json:"kind"`
}

type GetNodeByQualifiedRow struct {
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"project_id"`
	Kind          string    `json:"kind"`
	Name          *string   `json:"name"`
	QualifiedName *string   `json:"qualified_name"`
	FilePath      *string   `json:"file_path"`
	LineStart     *int32    `json:"line_start"`
	LineEnd       *int32    `json:"line_end"`
	Signature     *string   `json:"signature"`
	Doc           *string   `json:"doc"`
	Language      string    `json:"language"`
	ContentHash   []byte    `json:"content_hash"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) GetNodeByQualified(ctx context.Context, arg GetNodeByQualifiedParams) (GetNodeByQualifiedRow, error) {
	row := q.db.QueryRow(ctx, getNodeByQualified, arg.ProjectID, arg.QualifiedName, arg.Kind)
	var i GetNodeByQualifiedRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Name,
		&i.QualifiedName,
		&i.FilePath,
		&i.LineStart,
		&i.LineEnd,
		&i.Signature,
		&i.Doc,
		&i.Language,
		&i.ContentHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getObservationProject = `-- name: GetObservationProject :one
SELECT id, project_id
FROM knowledge_observations
WHERE id = $1
  AND deleted_at IS NULL
`

type GetObservationProjectRow struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

// Devuelve el project de la observation (para validar mismo-project en el cruce).
// Vive en este paquete para no acoplar el LinkService a observationdb; lee solo
// las columnas necesarias de knowledge_observations.
func (q *Queries) GetObservationProject(ctx context.Context, id uuid.UUID) (GetObservationProjectRow, error) {
	row := q.db.QueryRow(ctx, getObservationProject, id)
	var i GetObservationProjectRow
	err := row.Scan(&i.ID, &i.ProjectID)
	return i, err
}

const insertEdgeIfAbsent = `-- name: InsertEdgeIfAbsent :one

INSERT INTO code_edges
   (project_id, source_node_id, target_node_id, edge_type, metadata)
 VALUES ($1, $2,
         $3, $4, $5)
 ON CONFLICT (project_id, source_node_id, target_node_id, edge_type)
   DO NOTHING
 RETURNING id, project_id, source_node_id, target_node_id, edge_type,
           metadata, created_at
`

type InsertEdgeIfAbsentParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	SourceNodeID uuid.UUID `json:"source_node_id"`
	TargetNodeID uuid.UUID `json:"target_node_id"`
	EdgeType     string    `json:"edge_type"`
	Metadata     []byte    `json:"metadata"`
}

// ---------------------------------------------------------------------------
// Edges
// ---------------------------------------------------------------------------
// Inserción idempotente: si ya existe (mismo project/source/target/tipo) NO
// inserta ni lanza excepción (evita abortar la tx en loops de inserción masiva).
// RETURNING vacío => no se insertó (ya existía).
func (q *Queries) InsertEdgeIfAbsent(ctx context.Context, arg InsertEdgeIfAbsentParams) (CodeEdge, error) {
	row := q.db.QueryRow(ctx, insertEdgeIfAbsent,
		arg.ProjectID,
		arg.SourceNodeID,
		arg.TargetNodeID,
		arg.EdgeType,
		arg.Metadata,
	)
	var i CodeEdge
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceNodeID,
		&i.TargetNodeID,
		&i.EdgeType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertObsCodeLinkIfAbsent = `-- name: InsertObsCodeLinkIfAbsent :one
INSERT INTO knowledge_observation_code_links
   (project_id, observation_id, code_node_id, link_type, note, metadata, created_by)
 VALUES ($1, $2, $3,
         $4, $5, $6,
         $7)
 ON CONFLICT (project_id, observation_id, code_node_id, link_type)
   WHERE deleted_at IS NULL
   DO NOTHING
 RETURNING id, project_id, observation_id, code_node_id, link_type,
           note, metadata, created_by, created_at
`

type InsertObsCodeLinkIfAbsentParams struct {
	ProjectID     uuid.UUID  `json:"project_id"`
	ObservationID uuid.UUID  `json:"observation_id"`
	CodeNodeID    uuid.UUID  `json:"code_node_id"`
	LinkType      string     `json:"link_type"`
	Note          *string    `json:"note"`
	Metadata      []byte     `json:"metadata"`
	CreatedBy     *uuid.UUID `json:"created_by"`
}

type InsertObsCodeLinkIfAbsentRow struct {
	ID            uuid.UUID  `json:"id"`
	ProjectID     uuid.UUID  `json:"project_id"`
	ObservationID uuid.UUID  `json:"observation_id"`
	CodeNodeID    uuid.UUID  `json:"code_node_id"`
	LinkType      string     `json:"link_type"`
	Note          *string    `json:"note"`
	Metadata      []byte     `json:"metadata"`
	CreatedBy     *uuid.UUID `json:"created_by"`
	CreatedAt     time.Time  `json:"created_at"`
}

// Inserción idempotente del vínculo observation -> code_node. Si ya existe un
// vínculo activo (mismo project/observation/code_node/tipo) NO inserta ni lanza
// excepción (ON CONFLICT DO NOTHING sobre el índice único parcial). RETURNING
// vacío => ya existía.
func (q *Queries) InsertObsCodeLinkIfAbsent(ctx context.Context, arg InsertObsCodeLinkIfAbsentParams) (InsertObsCodeLinkIfAbsentRow, error) {
	row := q.db.QueryRow(ctx, insertObsCodeLinkIfAbsent,
		arg.ProjectID,
		arg.ObservationID,
		arg.CodeNodeID,
		arg.LinkType,
		arg.Note,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i InsertObsCodeLinkIfAbsentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ObservationID,
		&i.CodeNodeID,
		&i.LinkType,
		&i.Note,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listEdgesByProject = `-- name: ListEdgesByProject :many
SELECT id, project_id, source_node_id, target_node_id, edge_type,
       metadata, created_at
FROM code_edges
WHERE project_id = $1
  AND ($2::text IS NULL OR edge_type = $2::text)
ORDER BY created_at DESC
`

type ListEdgesByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	EdgeType  *string   `json:"edge_type"`
}

func (q *Queries) ListEdgesByProject(ctx context.Context, arg ListEdgesByProjectParams) ([]CodeEdge, error) {
	rows, err := q.db.Query(ctx, listEdgesByProject, arg.ProjectID, arg.EdgeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeEdge
	for rows.Next() {
		var i CodeEdge
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.EdgeType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesByProjectActive = `-- name: ListEdgesByProjectActive :many
SELECT e.id, e.project_id, e.source_node_id, e.target_node_id, e.edge_type,
       e.metadata, e.created_at
FROM code_edges e
JOIN code_nodes s ON s.id = e.source_node_id AND s.deleted_at IS NULL
JOIN code_nodes t ON t.id = e.target_node_id AND t.deleted_at IS NULL
WHERE e.project_id = $1
  AND ($2::text IS NULL OR e.edge_type = $2::text)
ORDER BY e.created_at DESC
`

type ListEdgesByProjectActiveParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	EdgeType  *string   `json:"edge_type"`
}

// Aristas del project cuyos DOS extremos son nodos activos (deleted_at IS NULL).
// Usado por Path para que el BFS no atraviese nodos muertos via aristas huérfanas
// que pudieran sobrevivir. Filtra en SQL en vez de en memoria.
func (q *Queries) ListEdgesByProjectActive(ctx context.Context, arg ListEdgesByProjectActiveParams) ([]CodeEdge, error) {
	rows, err := q.db.Query(ctx, listEdgesByProjectActive, arg.ProjectID, arg.EdgeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeEdge
	for rows.Next() {
		var i CodeEdge
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.EdgeType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesBySource = `-- name: ListEdgesBySource :many
SELECT id, project_id, source_node_id, target_node_id, edge_type,
       metadata, created_at
FROM code_edges
WHERE project_id = $1
  AND source_node_id = $2
  AND ($3::text IS NULL OR edge_type = $3::text)
ORDER BY created_at DESC
`

type ListEdgesBySourceParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	SourceNodeID uuid.UUID `json:"source_node_id"`
	EdgeType     *string   `json:"edge_type"`
}

func (q *Queries) ListEdgesBySource(ctx context.Context, arg ListEdgesBySourceParams) ([]CodeEdge, error) {
	rows, err := q.db.Query(ctx, listEdgesBySource, arg.ProjectID, arg.SourceNodeID, arg.EdgeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeEdge
	for rows.Next() {
		var i CodeEdge
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.EdgeType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesByTarget = `-- name: ListEdgesByTarget :many
SELECT id, project_id, source_node_id, target_node_id, edge_type,
       metadata, created_at
FROM code_edges
WHERE project_id = $1
  AND target_node_id = $2
  AND ($3::text IS NULL OR edge_type = $3::text)
ORDER BY created_at DESC
`

type ListEdgesByTargetParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	TargetNodeID uuid.UUID `json:"target_node_id"`
	EdgeType     *string   `json:"edge_type"`
}

func (q *Queries) ListEdgesByTarget(ctx context.Context, arg ListEdgesByTargetParams) ([]CodeEdge, error) {
	rows, err := q.db.Query(ctx, listEdgesByTarget, arg.ProjectID, arg.TargetNodeID, arg.EdgeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeEdge
	for rows.Next() {
		var i CodeEdge
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.EdgeType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndexFiles = `-- name: ListIndexFiles :many
SELECT id, project_id, file_path, content_hash, git_head,
       node_count, indexed_at
FROM code_index_files
WHERE project_id = $1
ORDER BY file_path ASC
`

func (q *Queries) ListIndexFiles(ctx context.Context, projectID uuid.UUID) ([]CodeIndexFile, error) {
	rows, err := q.db.Query(ctx, listIndexFiles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeIndexFile
	for rows.Next() {
		var i CodeIndexFile
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FilePath,
			&i.ContentHash,
			&i.GitHead,
			&i.NodeCount,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksByCodeNode = `-- name: ListLinksByCodeNode :many
SELECT id, project_id, observation_id, code_node_id, link_type,
       note, metadata, created_by, created_at
FROM knowledge_observation_code_links
WHERE code_node_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListLinksByCodeNodeRow struct {
	ID            uuid.UUID  `json:"id"`
	ProjectID     uuid.UUID  `json:"project_id"`
	ObservationID uuid.UUID  `json:"observation_id"`
	CodeNodeID    uuid.UUID  `json:"code_node_id"`
	LinkType      string     `json:"link_type"`
	Note          *string    `json:"note"`
	Metadata      []byte     `json:"metadata"`
	CreatedBy     *uuid.UUID `json:"created_by"`
	CreatedAt     time.Time  `json:"created_at"`
}

// Vínculos activos de un nodo de código (qué memorias lo afectan).
func (q *Queries) ListLinksByCodeNode(ctx context.Context, codeNodeID uuid.UUID) ([]ListLinksByCodeNodeRow, error) {
	rows, err := q.db.Query(ctx, listLinksByCodeNode, codeNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinksByCodeNodeRow
	for rows.Next() {
		var i ListLinksByCodeNodeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ObservationID,
			&i.CodeNodeID,
			&i.LinkType,
			&i.Note,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksByObservation = `-- name: ListLinksByObservation :many
SELECT id, project_id, observation_id, code_node_id, link_type,
       note, metadata, created_by, created_at
FROM knowledge_observation_code_links
WHERE observation_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListLinksByObservationRow struct {
	ID            uuid.UUID  `json:"id"`
	ProjectID     uuid.UUID  `json:"project_id"`
	ObservationID uuid.UUID  `json:"observation_id"`
	CodeNodeID    uuid.UUID  `json:"code_node_id"`
	LinkType      string     `json:"link_type"`
	Note          *string    `json:"note"`
	Metadata      []byte     `json:"metadata"`
	CreatedBy     *uuid.UUID `json:"created_by"`
	CreatedAt     time.Time  `json:"created_at"`
}

// Vínculos activos de una observation (qué nodos de código toca).
func (q *Queries) ListLinksByObservation(ctx context.Context, observationID uuid.UUID) ([]ListLinksByObservationRow, error) {
	rows, err := q.db.Query(ctx, listLinksByObservation, observationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinksByObservationRow
	for rows.Next() {
		var i ListLinksByObservationRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ObservationID,
			&i.CodeNodeID,
			&i.LinkType,
			&i.Note,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByFile = `-- name: ListNodesByFile :many
SELECT id, project_id, kind, name, qualified_name, file_path,
       line_start, line_end, signature, doc, language, content_hash,
       metadata, created_at, updated_at
FROM code_nodes
WHERE project_id = $1
  AND file_path = $2
  AND deleted_at IS NULL
ORDER BY line_start ASC
`

type ListNodesByFileParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	FilePath  *string   `json:"file_path"`
}

type ListNodesByFileRow struct {
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"project_id"`
	Kind          string    `json:"kind"`
	Name          *string   `json:"name"`
	QualifiedName *string   `json:"qualified_name"`
	FilePath      *string   `json:"file_path"`
	LineStart     *int32    `json:"line_start"`
	LineEnd       *int32    `json:"line_end"`
	Signature     *string   `json:"signature"`
	Doc           *string   `json:"doc"`
	Language      string    `json:"language"`
	ContentHash   []byte    `json:"content_hash"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListNodesByFile(ctx context.Context, arg ListNodesByFileParams) ([]ListNodesByFileRow, error) {
	rows, err := q.db.Query(ctx, listNodesByFile, arg.ProjectID, arg.FilePath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodesByFileRow
	for rows.Next() {
		var i ListNodesByFileRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.FilePath,
			&i.LineStart,
			&i.LineEnd,
			&i.Signature,
			&i.Doc,
			&i.Language,
			&i.ContentHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByProject = `-- name: ListNodesByProject :many
SELECT id, project_id, kind, name, qualified_name, file_path,
       line_start, line_end, signature, doc, language, content_hash,
       metadata, created_at, updated_at
FROM code_nodes
WHERE project_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR kind = $2::text)
ORDER BY file_path ASC, line_start ASC
`

type ListNodesByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Kind      *string   `json:"kind"`
}

type ListNodesByProjectRow struct {
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"project_id"`
	Kind          string    `json:"kind"`
	Name          *string   `json:"name"`
	QualifiedName *string   `json:"qualified_name"`
	FilePath      *string   `json:"file_path"`
	LineStart     *int32    `json:"line_start"`
	LineEnd       *int32    `json:"line_end"`
	Signature     *string   `json:"signature"`
	Doc           *string   `json:"doc"`
	Language      string    `json:"language"`
	ContentHash   []byte    `json:"content_hash"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListNodesByProject(ctx context.Context, arg ListNodesByProjectParams) ([]ListNodesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listNodesByProject, arg.ProjectID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodesByProjectRow
	for rows.Next() {
		var i ListNodesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.FilePath,
			&i.LineStart,
			&i.LineEnd,
			&i.Signature,
			&i.Doc,
			&i.Language,
			&i.ContentHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByCodeNode = `-- name: ListObservationsByCodeNode :many
SELECT l.id            AS link_id,
       l.link_type     AS link_type,
       l.note          AS note,
       l.created_at    AS linked_at,
       o.id            AS observation_id,
       o.content       AS content,
       o.observation_type AS observation_type,
       o.created_at    AS observation_created_at
FROM knowledge_observation_code_links l
JOIN knowledge_observations o ON o.id = l.observation_id AND o.deleted_at IS NULL
WHERE l.project_id = $1
  AND l.code_node_id = $2
  AND l.deleted_at IS NULL
ORDER BY l.created_at DESC
`

type ListObservationsByCodeNodeParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	CodeNodeID uuid.UUID `json:"code_node_id"`
}

type ListObservationsByCodeNodeRow struct {
	LinkID               uuid.UUID `json:"link_id"`
	LinkType             string    `json:"link_type"`
	Note                 *string   `json:"note"`
	LinkedAt             time.Time `json:"linked_at"`
	ObservationID        uuid.UUID `json:"observation_id"`
	Content              string    `json:"content"`
	ObservationType      string    `json:"observation_type"`
	ObservationCreatedAt time.Time `json:"observation_created_at"`
}

// Decisiones/memorias que afectan a un nodo de código, con su contenido y tipo
// (JOIN a knowledge_observations). Acotado al project para el aislamiento.
func (q *Queries) ListObservationsByCodeNode(ctx context.Context, arg ListObservationsByCodeNodeParams) ([]ListObservationsByCodeNodeRow, error) {
	rows, err := q.db.Query(ctx, listObservationsByCodeNode, arg.ProjectID, arg.CodeNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListObservationsByCodeNodeRow
	for rows.Next() {
		var i ListObservationsByCodeNodeRow
		if err := rows.Scan(
			&i.LinkID,
			&i.LinkType,
			&i.Note,
			&i.LinkedAt,
			&i.ObservationID,
			&i.Content,
			&i.ObservationType,
			&i.ObservationCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNodesByName = `-- name: SearchNodesByName :many
SELECT id, project_id, kind, name, qualified_name, file_path,
       line_start, line_end, signature, doc, language, content_hash,
       metadata, created_at, updated_at
FROM code_nodes
WHERE project_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR kind = $2::text)
  AND (name ILIKE $3 OR qualified_name ILIKE $3)
ORDER BY name ASC
LIMIT $4
`

type SearchNodesByNameParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Kind        *string   `json:"kind"`
	Pattern     *string   `json:"pattern"`
	ResultLimit int32     `json:"result_limit"`
}

type SearchNodesByNameRow struct {
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"project_id"`
	Kind          string    `json:"kind"`
	Name          *string   `json:"name"`
	QualifiedName *string   `json:"qualified_name"`
	FilePath      *string   `json:"file_path"`
	LineStart     *int32    `json:"line_start"`
	LineEnd       *int32    `json:"line_end"`
	Signature     *string   `json:"signature"`
	Doc           *string   `json:"doc"`
	Language      string    `json:"language"`
	ContentHash   []byte    `json:"content_hash"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) SearchNodesByName(ctx context.Context, arg SearchNodesByNameParams) ([]SearchNodesByNameRow, error) {
	rows, err := q.db.Query(ctx, searchNodesByName,
		arg.ProjectID,
		arg.Kind,
		arg.Pattern,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNodesByNameRow
	for rows.Next() {
		var i SearchNodesByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.FilePath,
			&i.LineStart,
			&i.LineEnd,
			&i.Signature,
			&i.Doc,
			&i.Language,
			&i.ContentHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNodesByFile = `-- name: SoftDeleteNodesByFile :execrows
UPDATE code_nodes
SET deleted_at = NOW()
WHERE project_id = $1
  AND file_path = $2
  AND deleted_at IS NULL
`

type SoftDeleteNodesByFileParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	FilePath  *string   `json:"file_path"`
}

// Marca como borrados todos los nodos activos de un archivo. Se usa al eliminar
// un archivo que desapareció del disco (removeFile).
func (q *Queries) SoftDeleteNodesByFile(ctx context.Context, arg SoftDeleteNodesByFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteNodesByFile, arg.ProjectID, arg.FilePath)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteNodesByFileExcept = `-- name: SoftDeleteNodesByFileExcept :many
UPDATE code_nodes
SET deleted_at = NOW()
WHERE project_id = $1
  AND file_path = $2
  AND deleted_at IS NULL
  AND id <> ALL($3::uuid[])
RETURNING id
`

type SoftDeleteNodesByFileExceptParams struct {
	ProjectID   uuid.UUID   `json:"project_id"`
	FilePath    *string     `json:"file_path"`
	KeepNodeIds []uuid.UUID `json:"keep_node_ids"`
}

// Re-parseo: marca como borrados los nodos activos de un archivo cuyo id NO está
// en el conjunto de ids recién upserteados (símbolos que ya no existen en el
// archivo). Los ids retenidos conservan su identidad (no se soft-deletean), por
// lo que las aristas entrantes y los vínculos memoria/código siguen apuntando al
// mismo node_id. RETURNING ids para que el caller borre sus aristas colgantes.
func (q *Queries) SoftDeleteNodesByFileExcept(ctx context.Context, arg SoftDeleteNodesByFileExceptParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, softDeleteNodesByFileExcept, arg.ProjectID, arg.FilePath, arg.KeepNodeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteObsCodeLink = `-- name: SoftDeleteObsCodeLink :execrows
UPDATE knowledge_observation_code_links
SET deleted_at = NOW()
WHERE project_id = $1
  AND observation_id = $2
  AND code_node_id = $3
  AND link_type = $4
  AND deleted_at IS NULL
`

type SoftDeleteObsCodeLinkParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	ObservationID uuid.UUID `json:"observation_id"`
	CodeNodeID    uuid.UUID `json:"code_node_id"`
	LinkType      string    `json:"link_type"`
}

// Marca como borrado el vínculo activo (observation, code_node, tipo) del project.
func (q *Queries) SoftDeleteObsCodeLink(ctx context.Context, arg SoftDeleteObsCodeLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteObsCodeLink,
		arg.ProjectID,
		arg.ObservationID,
		arg.CodeNodeID,
		arg.LinkType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertIndexFile = `-- name: UpsertIndexFile :one

INSERT INTO code_index_files
   (project_id, file_path, content_hash, git_head, node_count, indexed_at)
 VALUES ($1, $2, $3,
         $4, $5, NOW())
 ON CONFLICT (project_id, file_path)
   DO UPDATE SET
     content_hash = EXCLUDED.content_hash,
     git_head     = EXCLUDED.git_head,
     node_count   = EXCLUDED.node_count,
     indexed_at   = NOW()
 RETURNING id, project_id, file_path, content_hash, git_head,
           node_count, indexed_at
`

type UpsertIndexFileParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	FilePath    string    `json:"file_path"`
	ContentHash []byte    `json:"content_hash"`
	GitHead     *string   `json:"git_head"`
	NodeCount   *int32    `json:"node_count"`
}

// ---------------------------------------------------------------------------
// Index files (incrementalidad)
// ---------------------------------------------------------------------------
func (q *Queries) UpsertIndexFile(ctx context.Context, arg UpsertIndexFileParams) (CodeIndexFile, error) {
	row := q.db.QueryRow(ctx, upsertIndexFile,
		arg.ProjectID,
		arg.FilePath,
		arg.ContentHash,
		arg.GitHead,
		arg.NodeCount,
	)
	var i CodeIndexFile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FilePath,
		&i.ContentHash,
		&i.GitHead,
		&i.NodeCount,
		&i.IndexedAt,
	)
	return i, err
}

const upsertNode = `-- name: UpsertNode :one


INSERT INTO code_nodes
   (project_id, kind, name, qualified_name, file_path, line_start, line_end,
    signature, doc, language, content_hash, metadata)
 VALUES ($1, $2, $3,
         $4, $5,
         $6, $7,
         $8, $9, $10,
         $11, $12)
 ON CONFLICT (project_id, qualified_name, kind)
   WHERE deleted_at IS NULL
   DO UPDATE SET
     name         = EXCLUDED.name,
     file_path    = EXCLUDED.file_path,
     line_start   = EXCLUDED.line_start,
     line_end     = EXCLUDED.line_end,
     signature    = EXCLUDED.signature,
     doc          = EXCLUDED.doc,
     language     = EXCLUDED.language,
     content_hash = EXCLUDED.content_hash,
     metadata     = EXCLUDED.metadata,
     deleted_at   = NULL,
     updated_at   = NOW()
 RETURNING id, project_id, kind, name, qualified_name, file_path,
           line_start, line_end, signature, doc, language, content_hash,
           metadata, created_at, updated_at
`

type UpsertNodeParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	Kind          string    `json:"kind"`
	Name          *string   `json:"name"`
	QualifiedName *string   `json:"qualified_name"`
	FilePath      *string   `json:"file_path"`
	LineStart     *int32    `json:"line_start"`
	LineEnd       *int32    `json:"line_end"`
	Signature     *string   `json:"signature"`
	Doc           *string   `json:"doc"`
	Language      string    `json:"language"`
	ContentHash   []byte    `json:"content_hash"`
	Metadata      []byte    `json:"metadata"`
}

type UpsertNodeRow struct {
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"project_id"`
	Kind          string    `json:"kind"`
	Name          *string   `json:"name"`
	QualifiedName *string   `json:"qualified_name"`
	FilePath      *string   `json:"file_path"`
	LineStart     *int32    `json:"line_start"`
	LineEnd       *int32    `json:"line_end"`
	Signature     *string   `json:"signature"`
	Doc           *string   `json:"doc"`
	Language      string    `json:"language"`
	ContentHash   []byte    `json:"content_hash"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// ===========================================================================
// Code graph — grafo de CÓDIGO del repo (Go-only v1), tablas code_nodes /
// code_edges / code_index_files (mig 000178). Aislamiento por project_id
// (single-tenant). El binario domain-mcp parsea el AST client-side y materializa
// el grafo aquí; code_index_files da incrementalidad por content_hash.
// ===========================================================================
// ---------------------------------------------------------------------------
// Nodes
// ---------------------------------------------------------------------------
// Upsert idempotente por (project_id, qualified_name, kind) sobre nodos activos.
// Si el nodo existe (no borrado) actualiza ubicación/firma/doc/hash y reabre por
// si estaba borrado (deleted_at = NULL). El conflict target replica el predicado
// del índice único parcial de la mig 000178.
func (q *Queries) UpsertNode(ctx context.Context, arg UpsertNodeParams) (UpsertNodeRow, error) {
	row := q.db.QueryRow(ctx, upsertNode,
		arg.ProjectID,
		arg.Kind,
		arg.Name,
		arg.QualifiedName,
		arg.FilePath,
		arg.LineStart,
		arg.LineEnd,
		arg.Signature,
		arg.Doc,
		arg.Language,
		arg.ContentHash,
		arg.Metadata,
	)
	var i UpsertNodeRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Name,
		&i.QualifiedName,
		&i.FilePath,
		&i.LineStart,
		&i.LineEnd,
		&i.Signature,
		&i.Doc,
		&i.Language,
		&i.ContentHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
