// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package projectpolicydb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPolicy = `-- name: GetPolicy :one
SELECT id, project_id, slug, name, kind,
       body_md, body_structured, version, is_active, override_platform,
       source, created_at, updated_at, deleted_at
FROM project_policies
WHERE id = $1 AND deleted_at IS NULL
`

type GetPolicyRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Kind             string             `json:"kind"`
	BodyMd           string             `json:"body_md"`
	BodyStructured   []byte             `json:"body_structured"`
	Version          int32              `json:"version"`
	IsActive         bool               `json:"is_active"`
	OverridePlatform bool               `json:"override_platform"`
	Source           string             `json:"source"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetPolicy(ctx context.Context, id uuid.UUID) (GetPolicyRow, error) {
	row := q.db.QueryRow(ctx, getPolicy, id)
	var i GetPolicyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.BodyMd,
		&i.BodyStructured,
		&i.Version,
		&i.IsActive,
		&i.OverridePlatform,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPolicyBySlug = `-- name: GetPolicyBySlug :one
SELECT id, project_id, slug, name, kind,
       body_md, body_structured, version, is_active, override_platform,
       source, created_at, updated_at, deleted_at
FROM project_policies
WHERE project_id = $1 AND slug = $2
  AND is_active = TRUE AND deleted_at IS NULL AND proposed = false
`

type GetPolicyBySlugParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Slug      string    `json:"slug"`
}

type GetPolicyBySlugRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Kind             string             `json:"kind"`
	BodyMd           string             `json:"body_md"`
	BodyStructured   []byte             `json:"body_structured"`
	Version          int32              `json:"version"`
	IsActive         bool               `json:"is_active"`
	OverridePlatform bool               `json:"override_platform"`
	Source           string             `json:"source"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetPolicyBySlug(ctx context.Context, arg GetPolicyBySlugParams) (GetPolicyBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPolicyBySlug, arg.ProjectID, arg.Slug)
	var i GetPolicyBySlugRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.BodyMd,
		&i.BodyStructured,
		&i.Version,
		&i.IsActive,
		&i.OverridePlatform,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertPolicy = `-- name: InsertPolicy :one
INSERT INTO project_policies
   (project_id, slug, name, kind,
    body_md, body_structured, override_platform, source)
 VALUES ($1, $2, $3,
         $4, $5, $6,
         $7, $8)
 RETURNING id, project_id, slug, name, kind,
           body_md, body_structured, version, is_active, override_platform,
           source, created_at, updated_at, deleted_at
`

type InsertPolicyParams struct {
	ProjectID        uuid.UUID `json:"project_id"`
	Slug             string    `json:"slug"`
	Name             string    `json:"name"`
	Kind             string    `json:"kind"`
	BodyMd           string    `json:"body_md"`
	BodyStructured   []byte    `json:"body_structured"`
	OverridePlatform bool      `json:"override_platform"`
	Source           string    `json:"source"`
}

type InsertPolicyRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Kind             string             `json:"kind"`
	BodyMd           string             `json:"body_md"`
	BodyStructured   []byte             `json:"body_structured"`
	Version          int32              `json:"version"`
	IsActive         bool               `json:"is_active"`
	OverridePlatform bool               `json:"override_platform"`
	Source           string             `json:"source"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertPolicy(ctx context.Context, arg InsertPolicyParams) (InsertPolicyRow, error) {
	row := q.db.QueryRow(ctx, insertPolicy,
		arg.ProjectID,
		arg.Slug,
		arg.Name,
		arg.Kind,
		arg.BodyMd,
		arg.BodyStructured,
		arg.OverridePlatform,
		arg.Source,
	)
	var i InsertPolicyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.BodyMd,
		&i.BodyStructured,
		&i.Version,
		&i.IsActive,
		&i.OverridePlatform,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPolicies = `-- name: ListPolicies :many
SELECT id, project_id, slug, name, kind,
       body_md, body_structured, version, is_active, override_platform,
       source, created_at, updated_at, deleted_at
FROM project_policies
WHERE project_id = $1
  AND is_active = TRUE AND deleted_at IS NULL AND proposed = false
  AND ($2::text IS NULL OR kind = $2::text)
ORDER BY kind ASC, slug ASC
`

type ListPoliciesParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Kind      *string   `json:"kind"`
}

type ListPoliciesRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Kind             string             `json:"kind"`
	BodyMd           string             `json:"body_md"`
	BodyStructured   []byte             `json:"body_structured"`
	Version          int32              `json:"version"`
	IsActive         bool               `json:"is_active"`
	OverridePlatform bool               `json:"override_platform"`
	Source           string             `json:"source"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListPolicies(ctx context.Context, arg ListPoliciesParams) ([]ListPoliciesRow, error) {
	rows, err := q.db.Query(ctx, listPolicies, arg.ProjectID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoliciesRow
	for rows.Next() {
		var i ListPoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.BodyMd,
			&i.BodyStructured,
			&i.Version,
			&i.IsActive,
			&i.OverridePlatform,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePolicy = `-- name: SoftDeletePolicy :execrows
UPDATE project_policies
SET deleted_at = NOW(), is_active = FALSE
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePolicy(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePolicy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE project_policies
SET name = $1, kind = $2,
    body_md = $3, body_structured = $4,
    override_platform = $5,
    version = $6
WHERE id = $7 AND deleted_at IS NULL
RETURNING id, project_id, slug, name, kind,
          body_md, body_structured, version, is_active, override_platform,
          source, created_at, updated_at, deleted_at
`

type UpdatePolicyParams struct {
	Name             string    `json:"name"`
	Kind             string    `json:"kind"`
	BodyMd           string    `json:"body_md"`
	BodyStructured   []byte    `json:"body_structured"`
	OverridePlatform bool      `json:"override_platform"`
	Version          int32     `json:"version"`
	ID               uuid.UUID `json:"id"`
}

type UpdatePolicyRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Kind             string             `json:"kind"`
	BodyMd           string             `json:"body_md"`
	BodyStructured   []byte             `json:"body_structured"`
	Version          int32              `json:"version"`
	IsActive         bool               `json:"is_active"`
	OverridePlatform bool               `json:"override_platform"`
	Source           string             `json:"source"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (UpdatePolicyRow, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.Name,
		arg.Kind,
		arg.BodyMd,
		arg.BodyStructured,
		arg.OverridePlatform,
		arg.Version,
		arg.ID,
	)
	var i UpdatePolicyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.BodyMd,
		&i.BodyStructured,
		&i.Version,
		&i.IsActive,
		&i.OverridePlatform,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
