// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package outboundwebhookdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM webhook_outbound_subscriptions WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubscription, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getByID = `-- name: GetByID :one
SELECT id, organization_id, name, url, events, filters, active,
	failure_count, last_success_at, last_failure_at, created_at, updated_at
FROM webhook_outbound_subscriptions
WHERE id = $1
`

type GetByIDRow struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Name           string     `json:"name"`
	Url            string     `json:"url"`
	Events         []string   `json:"events"`
	Filters        []byte     `json:"filters"`
	Active         bool       `json:"active"`
	FailureCount   int32      `json:"failure_count"`
	LastSuccessAt  *time.Time `json:"last_success_at"`
	LastFailureAt  *time.Time `json:"last_failure_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (GetByIDRow, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i GetByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Url,
		&i.Events,
		&i.Filters,
		&i.Active,
		&i.FailureCount,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretCipher = `-- name: GetSecretCipher :one
SELECT secret_cipher FROM webhook_outbound_subscriptions WHERE id = $1
`

func (q *Queries) GetSecretCipher(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSecretCipher, id)
	var secret_cipher []byte
	err := row.Scan(&secret_cipher)
	return secret_cipher, err
}

const insertSubscription = `-- name: InsertSubscription :one
INSERT INTO webhook_outbound_subscriptions
	(organization_id, name, url, events, filters, secret_cipher)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at
`

type InsertSubscriptionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	Url            string    `json:"url"`
	Events         []string  `json:"events"`
	Filters        []byte    `json:"filters"`
	SecretCipher   []byte    `json:"secret_cipher"`
}

type InsertSubscriptionRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) (InsertSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, insertSubscription,
		arg.OrganizationID,
		arg.Name,
		arg.Url,
		arg.Events,
		arg.Filters,
		arg.SecretCipher,
	)
	var i InsertSubscriptionRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listAll = `-- name: ListAll :many
SELECT id, organization_id, name, url, events, filters, active,
	failure_count, last_success_at, last_failure_at, created_at, updated_at
FROM webhook_outbound_subscriptions
ORDER BY created_at DESC
`

type ListAllRow struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Name           string     `json:"name"`
	Url            string     `json:"url"`
	Events         []string   `json:"events"`
	Filters        []byte     `json:"filters"`
	Active         bool       `json:"active"`
	FailureCount   int32      `json:"failure_count"`
	LastSuccessAt  *time.Time `json:"last_success_at"`
	LastFailureAt  *time.Time `json:"last_failure_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

func (q *Queries) ListAll(ctx context.Context) ([]ListAllRow, error) {
	rows, err := q.db.Query(ctx, listAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllRow
	for rows.Next() {
		var i ListAllRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Url,
			&i.Events,
			&i.Filters,
			&i.Active,
			&i.FailureCount,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByEvent = `-- name: ListByEvent :many
SELECT id, organization_id, name, url, events, filters, active,
	failure_count, last_success_at, last_failure_at, created_at, updated_at
FROM webhook_outbound_subscriptions
WHERE active = TRUE
  AND $1::text = ANY(events)
`

type ListByEventRow struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Name           string     `json:"name"`
	Url            string     `json:"url"`
	Events         []string   `json:"events"`
	Filters        []byte     `json:"filters"`
	Active         bool       `json:"active"`
	FailureCount   int32      `json:"failure_count"`
	LastSuccessAt  *time.Time `json:"last_success_at"`
	LastFailureAt  *time.Time `json:"last_failure_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

func (q *Queries) ListByEvent(ctx context.Context, eventType string) ([]ListByEventRow, error) {
	rows, err := q.db.Query(ctx, listByEvent, eventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListByEventRow
	for rows.Next() {
		var i ListByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Url,
			&i.Events,
			&i.Filters,
			&i.Active,
			&i.FailureCount,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
