// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package agentdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const agentSlugTaken = `-- name: AgentSlugTaken :one
SELECT EXISTS (
  SELECT 1 FROM agents
  WHERE slug = $1 AND deleted_at IS NULL
)
`

func (q *Queries) AgentSlugTaken(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, agentSlugTaken, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countValidSkills = `-- name: CountValidSkills :one
SELECT COUNT(*) FROM skills
WHERE slug = ANY($1::text[]) AND deleted_at IS NULL
`

func (q *Queries) CountValidSkills(ctx context.Context, slugs []string) (int64, error) {
	row := q.db.QueryRow(ctx, countValidSkills, slugs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAgentTemplate = `-- name: DeleteAgentTemplate :execrows
DELETE FROM agent_templates WHERE slug = $1
`

func (q *Queries) DeleteAgentTemplate(ctx context.Context, slug string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentTemplate, slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, slug, name, COALESCE(description, '')::text AS description,
       provider, model, COALESCE(system_prompt, '')::text AS system_prompt,
       skills_slugs, max_iterations, token_budget, temperature,
       seed_managed, seed_version, is_user_modified, created_at, updated_at
FROM agents
WHERE id = $1 AND deleted_at IS NULL
`

type GetAgentByIDRow struct {
	ID             uuid.UUID      `json:"id"`
	Slug           string         `json:"slug"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	Provider       string         `json:"provider"`
	Model          string         `json:"model"`
	SystemPrompt   string         `json:"system_prompt"`
	SkillsSlugs    []string       `json:"skills_slugs"`
	MaxIterations  int32          `json:"max_iterations"`
	TokenBudget    *int64         `json:"token_budget"`
	Temperature    pgtype.Numeric `json:"temperature"`
	SeedManaged    bool           `json:"seed_managed"`
	SeedVersion    *int32         `json:"seed_version"`
	IsUserModified bool           `json:"is_user_modified"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) GetAgentByID(ctx context.Context, id uuid.UUID) (GetAgentByIDRow, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i GetAgentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Model,
		&i.SystemPrompt,
		&i.SkillsSlugs,
		&i.MaxIterations,
		&i.TokenBudget,
		&i.Temperature,
		&i.SeedManaged,
		&i.SeedVersion,
		&i.IsUserModified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentBySlug = `-- name: GetAgentBySlug :one
SELECT id, slug, name, COALESCE(description, '')::text AS description,
       provider, model, COALESCE(system_prompt, '')::text AS system_prompt,
       skills_slugs, max_iterations, token_budget, temperature,
       seed_managed, seed_version, is_user_modified, created_at, updated_at
FROM agents
WHERE slug = $1 AND deleted_at IS NULL
`

type GetAgentBySlugRow struct {
	ID             uuid.UUID      `json:"id"`
	Slug           string         `json:"slug"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	Provider       string         `json:"provider"`
	Model          string         `json:"model"`
	SystemPrompt   string         `json:"system_prompt"`
	SkillsSlugs    []string       `json:"skills_slugs"`
	MaxIterations  int32          `json:"max_iterations"`
	TokenBudget    *int64         `json:"token_budget"`
	Temperature    pgtype.Numeric `json:"temperature"`
	SeedManaged    bool           `json:"seed_managed"`
	SeedVersion    *int32         `json:"seed_version"`
	IsUserModified bool           `json:"is_user_modified"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) GetAgentBySlug(ctx context.Context, slug string) (GetAgentBySlugRow, error) {
	row := q.db.QueryRow(ctx, getAgentBySlug, slug)
	var i GetAgentBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Model,
		&i.SystemPrompt,
		&i.SkillsSlugs,
		&i.MaxIterations,
		&i.TokenBudget,
		&i.Temperature,
		&i.SeedManaged,
		&i.SeedVersion,
		&i.IsUserModified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentTemplateBySlug = `-- name: GetAgentTemplateBySlug :one
SELECT id, slug, name, system_prompt,
       COALESCE(personality, '')::text AS personality,
       capabilities, model, temperature, max_tokens,
       handoff_policy, metadata
FROM agent_templates
WHERE slug = $1
`

type GetAgentTemplateBySlugRow struct {
	ID            uuid.UUID      `json:"id"`
	Slug          string         `json:"slug"`
	Name          string         `json:"name"`
	SystemPrompt  string         `json:"system_prompt"`
	Personality   string         `json:"personality"`
	Capabilities  []string       `json:"capabilities"`
	Model         string         `json:"model"`
	Temperature   pgtype.Numeric `json:"temperature"`
	MaxTokens     int32          `json:"max_tokens"`
	HandoffPolicy string         `json:"handoff_policy"`
	Metadata      []byte         `json:"metadata"`
}

func (q *Queries) GetAgentTemplateBySlug(ctx context.Context, slug string) (GetAgentTemplateBySlugRow, error) {
	row := q.db.QueryRow(ctx, getAgentTemplateBySlug, slug)
	var i GetAgentTemplateBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SystemPrompt,
		&i.Personality,
		&i.Capabilities,
		&i.Model,
		&i.Temperature,
		&i.MaxTokens,
		&i.HandoffPolicy,
		&i.Metadata,
	)
	return i, err
}

const insertAgent = `-- name: InsertAgent :one

INSERT INTO agents
  (slug, name, description, provider, model, system_prompt,
   skills_slugs, max_iterations, token_budget, temperature)
VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8,
  $9, $10
)
RETURNING id, slug, name, COALESCE(description, '')::text AS description,
          provider, model, COALESCE(system_prompt, '')::text AS system_prompt,
          skills_slugs, max_iterations, token_budget, temperature,
          seed_managed, seed_version, is_user_modified, created_at, updated_at
`

type InsertAgentParams struct {
	Slug          string         `json:"slug"`
	Name          string         `json:"name"`
	Description   *string        `json:"description"`
	Provider      string         `json:"provider"`
	Model         string         `json:"model"`
	SystemPrompt  *string        `json:"system_prompt"`
	SkillsSlugs   []string       `json:"skills_slugs"`
	MaxIterations int32          `json:"max_iterations"`
	TokenBudget   *int64         `json:"token_budget"`
	Temperature   pgtype.Numeric `json:"temperature"`
}

type InsertAgentRow struct {
	ID             uuid.UUID      `json:"id"`
	Slug           string         `json:"slug"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	Provider       string         `json:"provider"`
	Model          string         `json:"model"`
	SystemPrompt   string         `json:"system_prompt"`
	SkillsSlugs    []string       `json:"skills_slugs"`
	MaxIterations  int32          `json:"max_iterations"`
	TokenBudget    *int64         `json:"token_budget"`
	Temperature    pgtype.Numeric `json:"temperature"`
	SeedManaged    bool           `json:"seed_managed"`
	SeedVersion    *int32         `json:"seed_version"`
	IsUserModified bool           `json:"is_user_modified"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

// agent: pg_repository.go
func (q *Queries) InsertAgent(ctx context.Context, arg InsertAgentParams) (InsertAgentRow, error) {
	row := q.db.QueryRow(ctx, insertAgent,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Provider,
		arg.Model,
		arg.SystemPrompt,
		arg.SkillsSlugs,
		arg.MaxIterations,
		arg.TokenBudget,
		arg.Temperature,
	)
	var i InsertAgentRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Model,
		&i.SystemPrompt,
		&i.SkillsSlugs,
		&i.MaxIterations,
		&i.TokenBudget,
		&i.Temperature,
		&i.SeedManaged,
		&i.SeedVersion,
		&i.IsUserModified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAgentVersion = `-- name: InsertAgentVersion :exec

INSERT INTO agent_versions (agent_id, version, snapshot, changed_by)
SELECT $1::uuid,
       COALESCE((SELECT MAX(av.version) FROM agent_versions av WHERE av.agent_id = $1::uuid), 0) + 1,
       $2,
       $3
`

type InsertAgentVersionParams struct {
	AgentID   uuid.UUID  `json:"agent_id"`
	Snapshot  []byte     `json:"snapshot"`
	ChangedBy *uuid.UUID `json:"changed_by"`
}

// agent_versions
func (q *Queries) InsertAgentVersion(ctx context.Context, arg InsertAgentVersionParams) error {
	_, err := q.db.Exec(ctx, insertAgentVersion, arg.AgentID, arg.Snapshot, arg.ChangedBy)
	return err
}

const listAgentTemplates = `-- name: ListAgentTemplates :many
SELECT id, slug, name, system_prompt,
       COALESCE(personality, '')::text AS personality,
       capabilities, model, temperature, max_tokens,
       handoff_policy, metadata
FROM agent_templates
ORDER BY slug ASC
LIMIT $1::int
`

type ListAgentTemplatesRow struct {
	ID            uuid.UUID      `json:"id"`
	Slug          string         `json:"slug"`
	Name          string         `json:"name"`
	SystemPrompt  string         `json:"system_prompt"`
	Personality   string         `json:"personality"`
	Capabilities  []string       `json:"capabilities"`
	Model         string         `json:"model"`
	Temperature   pgtype.Numeric `json:"temperature"`
	MaxTokens     int32          `json:"max_tokens"`
	HandoffPolicy string         `json:"handoff_policy"`
	Metadata      []byte         `json:"metadata"`
}

func (q *Queries) ListAgentTemplates(ctx context.Context, resultLimit int32) ([]ListAgentTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listAgentTemplates, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentTemplatesRow
	for rows.Next() {
		var i ListAgentTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.SystemPrompt,
			&i.Personality,
			&i.Capabilities,
			&i.Model,
			&i.Temperature,
			&i.MaxTokens,
			&i.HandoffPolicy,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentVersions = `-- name: ListAgentVersions :many
SELECT version, snapshot, changed_by, created_at
FROM agent_versions
WHERE agent_id = $1
ORDER BY version DESC
LIMIT $2::int
`

type ListAgentVersionsParams struct {
	AgentID     uuid.UUID `json:"agent_id"`
	ResultLimit int32     `json:"result_limit"`
}

type ListAgentVersionsRow struct {
	Version   int32      `json:"version"`
	Snapshot  []byte     `json:"snapshot"`
	ChangedBy *uuid.UUID `json:"changed_by"`
	CreatedAt time.Time  `json:"created_at"`
}

func (q *Queries) ListAgentVersions(ctx context.Context, arg ListAgentVersionsParams) ([]ListAgentVersionsRow, error) {
	rows, err := q.db.Query(ctx, listAgentVersions, arg.AgentID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentVersionsRow
	for rows.Next() {
		var i ListAgentVersionsRow
		if err := rows.Scan(
			&i.Version,
			&i.Snapshot,
			&i.ChangedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, slug, name, COALESCE(description, '')::text AS description,
       provider, model, COALESCE(system_prompt, '')::text AS system_prompt,
       skills_slugs, max_iterations, token_budget, temperature,
       seed_managed, seed_version, is_user_modified, created_at, updated_at
FROM agents
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1::int
`

type ListAgentsRow struct {
	ID             uuid.UUID      `json:"id"`
	Slug           string         `json:"slug"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	Provider       string         `json:"provider"`
	Model          string         `json:"model"`
	SystemPrompt   string         `json:"system_prompt"`
	SkillsSlugs    []string       `json:"skills_slugs"`
	MaxIterations  int32          `json:"max_iterations"`
	TokenBudget    *int64         `json:"token_budget"`
	Temperature    pgtype.Numeric `json:"temperature"`
	SeedManaged    bool           `json:"seed_managed"`
	SeedVersion    *int32         `json:"seed_version"`
	IsUserModified bool           `json:"is_user_modified"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) ListAgents(ctx context.Context, resultLimit int32) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsRow
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Provider,
			&i.Model,
			&i.SystemPrompt,
			&i.SkillsSlugs,
			&i.MaxIterations,
			&i.TokenBudget,
			&i.Temperature,
			&i.SeedManaged,
			&i.SeedVersion,
			&i.IsUserModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldAgentVersions = `-- name: PurgeOldAgentVersions :exec
DELETE FROM agent_versions av
WHERE av.agent_id = $1::uuid
  AND av.version <= (
    SELECT MAX(av2.version) - $2::int
    FROM agent_versions av2
    WHERE av2.agent_id = $1::uuid
  )
`

type PurgeOldAgentVersionsParams struct {
	AgentID         uuid.UUID `json:"agent_id"`
	MaxVersionsKept int32     `json:"max_versions_kept"`
}

func (q *Queries) PurgeOldAgentVersions(ctx context.Context, arg PurgeOldAgentVersionsParams) error {
	_, err := q.db.Exec(ctx, purgeOldAgentVersions, arg.AgentID, arg.MaxVersionsKept)
	return err
}

const softDeleteAgent = `-- name: SoftDeleteAgent :exec
UPDATE agents SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAgent, id)
	return err
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET name            = $1,
    description     = $2,
    provider        = $3,
    model           = $4,
    system_prompt   = $5,
    skills_slugs    = $6,
    max_iterations  = $7,
    token_budget    = $8,
    temperature     = $9,
    is_user_modified = $10
WHERE id = $11 AND deleted_at IS NULL
RETURNING id, slug, name, COALESCE(description, '')::text AS description,
          provider, model, COALESCE(system_prompt, '')::text AS system_prompt,
          skills_slugs, max_iterations, token_budget, temperature,
          seed_managed, seed_version, is_user_modified, created_at, updated_at
`

type UpdateAgentParams struct {
	Name           string         `json:"name"`
	Description    *string        `json:"description"`
	Provider       string         `json:"provider"`
	Model          string         `json:"model"`
	SystemPrompt   *string        `json:"system_prompt"`
	SkillsSlugs    []string       `json:"skills_slugs"`
	MaxIterations  int32          `json:"max_iterations"`
	TokenBudget    *int64         `json:"token_budget"`
	Temperature    pgtype.Numeric `json:"temperature"`
	IsUserModified bool           `json:"is_user_modified"`
	ID             uuid.UUID      `json:"id"`
}

type UpdateAgentRow struct {
	ID             uuid.UUID      `json:"id"`
	Slug           string         `json:"slug"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	Provider       string         `json:"provider"`
	Model          string         `json:"model"`
	SystemPrompt   string         `json:"system_prompt"`
	SkillsSlugs    []string       `json:"skills_slugs"`
	MaxIterations  int32          `json:"max_iterations"`
	TokenBudget    *int64         `json:"token_budget"`
	Temperature    pgtype.Numeric `json:"temperature"`
	SeedManaged    bool           `json:"seed_managed"`
	SeedVersion    *int32         `json:"seed_version"`
	IsUserModified bool           `json:"is_user_modified"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (UpdateAgentRow, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.Name,
		arg.Description,
		arg.Provider,
		arg.Model,
		arg.SystemPrompt,
		arg.SkillsSlugs,
		arg.MaxIterations,
		arg.TokenBudget,
		arg.Temperature,
		arg.IsUserModified,
		arg.ID,
	)
	var i UpdateAgentRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Model,
		&i.SystemPrompt,
		&i.SkillsSlugs,
		&i.MaxIterations,
		&i.TokenBudget,
		&i.Temperature,
		&i.SeedManaged,
		&i.SeedVersion,
		&i.IsUserModified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentTemplate = `-- name: UpsertAgentTemplate :one

INSERT INTO agent_templates
  (slug, name, system_prompt, personality, capabilities,
   model, temperature, max_tokens, handoff_policy, metadata)
VALUES (
  $1, $2, $3,
  NULLIF($4, ''), $5,
  $6, $7, $8,
  $9, $10
)
ON CONFLICT (slug)
DO UPDATE SET
  name           = EXCLUDED.name,
  system_prompt  = EXCLUDED.system_prompt,
  personality    = EXCLUDED.personality,
  capabilities   = EXCLUDED.capabilities,
  model          = EXCLUDED.model,
  temperature    = EXCLUDED.temperature,
  max_tokens     = EXCLUDED.max_tokens,
  handoff_policy = EXCLUDED.handoff_policy,
  metadata       = EXCLUDED.metadata,
  updated_at     = now()
RETURNING id, slug, name, system_prompt,
          COALESCE(personality, '')::text AS personality,
          capabilities, model, temperature, max_tokens,
          handoff_policy, metadata
`

type UpsertAgentTemplateParams struct {
	Slug          string         `json:"slug"`
	Name          string         `json:"name"`
	SystemPrompt  string         `json:"system_prompt"`
	Personality   interface{}    `json:"personality"`
	Capabilities  []string       `json:"capabilities"`
	Model         string         `json:"model"`
	Temperature   pgtype.Numeric `json:"temperature"`
	MaxTokens     int32          `json:"max_tokens"`
	HandoffPolicy string         `json:"handoff_policy"`
	Metadata      []byte         `json:"metadata"`
}

type UpsertAgentTemplateRow struct {
	ID            uuid.UUID      `json:"id"`
	Slug          string         `json:"slug"`
	Name          string         `json:"name"`
	SystemPrompt  string         `json:"system_prompt"`
	Personality   string         `json:"personality"`
	Capabilities  []string       `json:"capabilities"`
	Model         string         `json:"model"`
	Temperature   pgtype.Numeric `json:"temperature"`
	MaxTokens     int32          `json:"max_tokens"`
	HandoffPolicy string         `json:"handoff_policy"`
	Metadata      []byte         `json:"metadata"`
}

// agent: orchestration/templates_store.go
func (q *Queries) UpsertAgentTemplate(ctx context.Context, arg UpsertAgentTemplateParams) (UpsertAgentTemplateRow, error) {
	row := q.db.QueryRow(ctx, upsertAgentTemplate,
		arg.Slug,
		arg.Name,
		arg.SystemPrompt,
		arg.Personality,
		arg.Capabilities,
		arg.Model,
		arg.Temperature,
		arg.MaxTokens,
		arg.HandoffPolicy,
		arg.Metadata,
	)
	var i UpsertAgentTemplateRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SystemPrompt,
		&i.Personality,
		&i.Capabilities,
		&i.Model,
		&i.Temperature,
		&i.MaxTokens,
		&i.HandoffPolicy,
		&i.Metadata,
	)
	return i, err
}
