// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package enrollmentdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findTokensByPrefix = `-- name: FindTokensByPrefix :many
SELECT id, token_hash, role_on_enroll
FROM enrollment_tokens
WHERE token_prefix = $1 AND revoked_at IS NULL
`

type FindTokensByPrefixRow struct {
	ID           uuid.UUID `json:"id"`
	TokenHash    []byte    `json:"token_hash"`
	RoleOnEnroll string    `json:"role_on_enroll"`
}

func (q *Queries) FindTokensByPrefix(ctx context.Context, tokenPrefix string) ([]FindTokensByPrefixRow, error) {
	rows, err := q.db.Query(ctx, findTokensByPrefix, tokenPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindTokensByPrefixRow
	for rows.Next() {
		var i FindTokensByPrefixRow
		if err := rows.Scan(&i.ID, &i.TokenHash, &i.RoleOnEnroll); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveMetadata = `-- name: GetActiveMetadata :one
SELECT token_prefix, role_on_enroll, created_at
FROM enrollment_tokens
WHERE revoked_at IS NULL
`

type GetActiveMetadataRow struct {
	TokenPrefix  string    `json:"token_prefix"`
	RoleOnEnroll string    `json:"role_on_enroll"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetActiveMetadata(ctx context.Context) (GetActiveMetadataRow, error) {
	row := q.db.QueryRow(ctx, getActiveMetadata)
	var i GetActiveMetadataRow
	err := row.Scan(&i.TokenPrefix, &i.RoleOnEnroll, &i.CreatedAt)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :exec
INSERT INTO auth_api_keys (id, user_id, key_hash, key_prefix, name, environment, expires_at)
VALUES ($1, $2, $3, $4, 'default', 'live', NULL)
`

type InsertAPIKeyParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	KeyHash   []byte    `json:"key_hash"`
	KeyPrefix string    `json:"key_prefix"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error {
	_, err := q.db.Exec(ctx, insertAPIKey,
		arg.ID,
		arg.UserID,
		arg.KeyHash,
		arg.KeyPrefix,
	)
	return err
}

const insertToken = `-- name: InsertToken :one
INSERT INTO enrollment_tokens (token_hash, token_prefix, role_on_enroll, created_by_user_id)
VALUES ($1, $2, $3, $4)
RETURNING created_at
`

type InsertTokenParams struct {
	TokenHash       []byte     `json:"token_hash"`
	TokenPrefix     string     `json:"token_prefix"`
	RoleOnEnroll    string     `json:"role_on_enroll"`
	CreatedByUserID *uuid.UUID `json:"created_by_user_id"`
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertToken,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.RoleOnEnroll,
		arg.CreatedByUserID,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (email, name, role)
VALUES ($1, NULLIF($2, ''), $3)
RETURNING id, created_at
`

type InsertUserParams struct {
	Email string      `json:"email"`
	Name  interface{} `json:"name"`
	Role  string      `json:"role"`
}

type InsertUserRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Email, arg.Name, arg.Role)
	var i InsertUserRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const revokeAllActive = `-- name: RevokeAllActive :execrows
UPDATE enrollment_tokens SET revoked_at = NOW() WHERE revoked_at IS NULL
`

func (q *Queries) RevokeAllActive(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllActive)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
