# TYPE        DATABASE        USER             ADDRESS         METHOD

# Socket UNIX local (solo accesible desde adentro del container): trust
local         all             all                              trust

# Red interna Docker (PG no expuesto al público): no requiere SSL
host          all             all              172.16.0.0/12    scram-sha-256
host          all             all              192.168.0.0/16   scram-sha-256

# Conexiones externas (eventualmente, hoy no aplica): exigir SSL
hostssl       all             all              0.0.0.0/0        scram-sha-256
hostssl       all             all              ::/0             scram-sha-256
hostnossl     all             all              0.0.0.0/0        reject
hostnossl     all             all              ::/0             reject
