// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package wizardplandb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRequirementSlugByIssueID = `-- name: GetRequirementSlugByIssueID :one
SELECT r.slug
FROM issues us
JOIN sdd_requirements r ON r.id = us.req_id
WHERE us.id = $1::uuid
`

func (q *Queries) GetRequirementSlugByIssueID(ctx context.Context, issueID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getRequirementSlugByIssueID, issueID)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const listAgentRunsSince = `-- name: ListAgentRunsSince :many
SELECT ar.id, COALESCE(a.slug, '')::text AS agent_slug, ar.started_at,
       LEFT(COALESCE(ar.outputs::text, ''), 200)::text AS summary
FROM agent_runs ar
LEFT JOIN agents a ON a.id = ar.agent_id
WHERE ar.started_at >= now() - $1::interval
  AND ($2::uuid IS NULL OR ar.user_id = $2::uuid)
ORDER BY ar.started_at DESC
LIMIT $3::int
`

type ListAgentRunsSinceParams struct {
	IntervalDays pgtype.Interval `json:"interval_days"`
	UserID       *uuid.UUID      `json:"user_id"`
	ResultLimit  int32           `json:"result_limit"`
}

type ListAgentRunsSinceRow struct {
	ID        uuid.UUID          `json:"id"`
	AgentSlug string             `json:"agent_slug"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	Summary   string             `json:"summary"`
}

// wizardplan: sources/agent_history.go
func (q *Queries) ListAgentRunsSince(ctx context.Context, arg ListAgentRunsSinceParams) ([]ListAgentRunsSinceRow, error) {
	rows, err := q.db.Query(ctx, listAgentRunsSince, arg.IntervalDays, arg.UserID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentRunsSinceRow
	for rows.Next() {
		var i ListAgentRunsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentSlug,
			&i.StartedAt,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByFTS = `-- name: ListIssuesByFTS :many
SELECT id, slug, title, status,
       ts_rank(to_tsvector('spanish', coalesce(title, '') || ' ' || coalesce(description, '')),
               plainto_tsquery('spanish', $1::text)) AS score
FROM issues
WHERE to_tsvector('spanish', coalesce(title, '') || ' ' || coalesce(description, ''))
      @@ plainto_tsquery('spanish', $1::text)
ORDER BY score DESC
LIMIT $2::int
`

type ListIssuesByFTSParams struct {
	Query       string `json:"query"`
	ResultLimit int32  `json:"result_limit"`
}

type ListIssuesByFTSRow struct {
	ID     uuid.UUID `json:"id"`
	Slug   string    `json:"slug"`
	Title  string    `json:"title"`
	Status string    `json:"status"`
	Score  float32   `json:"score"`
}

// wizardplan: sources/issue_dedup.go
func (q *Queries) ListIssuesByFTS(ctx context.Context, arg ListIssuesByFTSParams) ([]ListIssuesByFTSRow, error) {
	rows, err := q.db.Query(ctx, listIssuesByFTS, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuesByFTSRow
	for rows.Next() {
		var i ListIssuesByFTSRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
