// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package inventorydb

import (
	"context"
)

const listAgents = `-- name: ListAgents :many
SELECT slug, name, COALESCE(description, '')::text AS description,
       COALESCE(model, '')::text AS model,
       COALESCE(skills_slugs, '{}')::text[] AS skills_slugs
FROM agents
WHERE deleted_at IS NULL
ORDER BY slug
`

type ListAgentsRow struct {
	Slug        string   `json:"slug"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Model       string   `json:"model"`
	SkillsSlugs []string `json:"skills_slugs"`
}

func (q *Queries) ListAgents(ctx context.Context) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsRow
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Model,
			&i.SkillsSlugs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlows = `-- name: ListFlows :many
SELECT slug, name, COALESCE(description, '')::text AS description
FROM flows
WHERE deleted_at IS NULL
ORDER BY slug
`

type ListFlowsRow struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) ListFlows(ctx context.Context) ([]ListFlowsRow, error) {
	rows, err := q.db.Query(ctx, listFlows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlowsRow
	for rows.Next() {
		var i ListFlowsRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPProviders = `-- name: ListMCPProviders :many
SELECT name, description, command, tags, required_env
FROM mcp_providers
ORDER BY name
`

type ListMCPProvidersRow struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Command     string   `json:"command"`
	Tags        []string `json:"tags"`
	RequiredEnv []string `json:"required_env"`
}

func (q *Queries) ListMCPProviders(ctx context.Context) ([]ListMCPProvidersRow, error) {
	rows, err := q.db.Query(ctx, listMCPProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCPProvidersRow
	for rows.Next() {
		var i ListMCPProvidersRow
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.Command,
			&i.Tags,
			&i.RequiredEnv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPServers = `-- name: ListMCPServers :many
SELECT name, transport, status, enabled
FROM mcp_servers
WHERE enabled = TRUE
ORDER BY name
`

type ListMCPServersRow struct {
	Name      string `json:"name"`
	Transport string `json:"transport"`
	Status    string `json:"status"`
	Enabled   bool   `json:"enabled"`
}

func (q *Queries) ListMCPServers(ctx context.Context) ([]ListMCPServersRow, error) {
	rows, err := q.db.Query(ctx, listMCPServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCPServersRow
	for rows.Next() {
		var i ListMCPServersRow
		if err := rows.Scan(
			&i.Name,
			&i.Transport,
			&i.Status,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformPolicies = `-- name: ListPlatformPolicies :many
SELECT slug, name, LEFT(COALESCE(body_md, ''), 120)::text AS description
FROM platform_policies
WHERE is_active = TRUE
ORDER BY slug
`

type ListPlatformPoliciesRow struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) ListPlatformPolicies(ctx context.Context) ([]ListPlatformPoliciesRow, error) {
	rows, err := q.db.Query(ctx, listPlatformPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlatformPoliciesRow
	for rows.Next() {
		var i ListPlatformPoliciesRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTemplates = `-- name: ListProjectTemplates :many
SELECT slug, name, COALESCE(description, '')::text AS description
FROM project_templates
ORDER BY slug
`

type ListProjectTemplatesRow struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) ListProjectTemplates(ctx context.Context) ([]ListProjectTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listProjectTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectTemplatesRow
	for rows.Next() {
		var i ListProjectTemplatesRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT slug, name, COALESCE(description, '')::text AS description,
       COALESCE(skill_type, 'prompt')::text AS skill_type
FROM skills
WHERE deleted_at IS NULL
ORDER BY slug
`

type ListSkillsRow struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
	SkillType   string `json:"skill_type"`
}

func (q *Queries) ListSkills(ctx context.Context) ([]ListSkillsRow, error) {
	rows, err := q.db.Query(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkillsRow
	for rows.Next() {
		var i ListSkillsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.SkillType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
