// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package projectmergedb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkTargetExists = `-- name: CheckTargetExists :one
SELECT 1 FROM projects WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) CheckTargetExists(ctx context.Context, targetID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, checkTargetExists, targetID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getSourceProject = `-- name: GetSourceProject :one
SELECT deleted_at, slug FROM projects WHERE id = $1
`

type GetSourceProjectRow struct {
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Slug      string             `json:"slug"`
}

func (q *Queries) GetSourceProject(ctx context.Context, sourceID uuid.UUID) (GetSourceProjectRow, error) {
	row := q.db.QueryRow(ctx, getSourceProject, sourceID)
	var i GetSourceProjectRow
	err := row.Scan(&i.DeletedAt, &i.Slug)
	return i, err
}

const insertMergeRecord = `-- name: InsertMergeRecord :exec
INSERT INTO project_merges (id, source_id, target_id, actor_id, report, merged_at)
VALUES ($1, $2, $3, $4, $5, now())
`

type InsertMergeRecordParams struct {
	ID       uuid.UUID  `json:"id"`
	SourceID uuid.UUID  `json:"source_id"`
	TargetID uuid.UUID  `json:"target_id"`
	ActorID  *uuid.UUID `json:"actor_id"`
	Report   []byte     `json:"report"`
}

func (q *Queries) InsertMergeRecord(ctx context.Context, arg InsertMergeRecordParams) error {
	_, err := q.db.Exec(ctx, insertMergeRecord,
		arg.ID,
		arg.SourceID,
		arg.TargetID,
		arg.ActorID,
		arg.Report,
	)
	return err
}

const insertMergeRecordNoActor = `-- name: InsertMergeRecordNoActor :exec
INSERT INTO project_merges (id, source_id, target_id, merged_at)
VALUES ($1, $2, $3, now())
`

type InsertMergeRecordNoActorParams struct {
	ID       uuid.UUID `json:"id"`
	SourceID uuid.UUID `json:"source_id"`
	TargetID uuid.UUID `json:"target_id"`
}

func (q *Queries) InsertMergeRecordNoActor(ctx context.Context, arg InsertMergeRecordNoActorParams) error {
	_, err := q.db.Exec(ctx, insertMergeRecordNoActor, arg.ID, arg.SourceID, arg.TargetID)
	return err
}

const moveObservations = `-- name: MoveObservations :execrows
UPDATE knowledge_observations SET project_id = $1 WHERE project_id = $2 AND deleted_at IS NULL
`

type MoveObservationsParams struct {
	TargetID uuid.UUID `json:"target_id"`
	SourceID uuid.UUID `json:"source_id"`
}

func (q *Queries) MoveObservations(ctx context.Context, arg MoveObservationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveObservations, arg.TargetID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteProject(ctx context.Context, sourceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, sourceID)
	return err
}
