// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package issuedb

import (
	"time"

	"github.com/google/uuid"
)

type Issue struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	Status      string    `json:"status"`
	Priority    string    `json:"priority"`
	ReqID       uuid.UUID `json:"req_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ProjectID   uuid.UUID `json:"project_id"`
}

type IssueGherkinScenario struct {
	ID        uuid.UUID `json:"id"`
	IssueID   uuid.UUID `json:"issue_id"`
	Feature   string    `json:"feature"`
	Scenario  string    `json:"scenario"`
	Given     []string  `json:"given"`
	WhenText  string    `json:"when_text"`
	ThenRows  []string  `json:"then_rows"`
	Position  int32     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	ProjectID uuid.UUID `json:"project_id"`
}
