// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package extsyncdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ExternalSyncState struct {
	ID              uuid.UUID          `json:"id"`
	ProviderID      uuid.UUID          `json:"provider_id"`
	EntityKind      string             `json:"entity_kind"`
	EntityID        uuid.UUID          `json:"entity_id"`
	ExternalKey     string             `json:"external_key"`
	ExternalUrl     string             `json:"external_url"`
	ExternalType    *string            `json:"external_type"`
	SyncDirection   string             `json:"sync_direction"`
	SyncStatus      string             `json:"sync_status"`
	FieldMapping    []byte             `json:"field_mapping"`
	LastPushedAt    pgtype.Timestamptz `json:"last_pushed_at"`
	LastPulledAt    pgtype.Timestamptz `json:"last_pulled_at"`
	LastSyncedAt    pgtype.Timestamptz `json:"last_synced_at"`
	DriftDetectedAt pgtype.Timestamptz `json:"drift_detected_at"`
	DriftFields     []byte             `json:"drift_fields"`
	PartialFailures []byte             `json:"partial_failures"`
	RetryCount      int32              `json:"retry_count"`
	NextRetryAt     pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}
