// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package requirementdb

import (
	"time"

	"github.com/google/uuid"
)

type SddRequirement struct {
	ID          uuid.UUID  `json:"id"`
	Slug        string     `json:"slug"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	Status      string     `json:"status"`
	Priority    string     `json:"priority"`
	ParentID    *uuid.UUID `json:"parent_id"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ProjectID   uuid.UUID  `json:"project_id"`
}
