// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package requirementdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveRequirement = `-- name: ArchiveRequirement :exec
UPDATE sdd_requirements SET status = 'archived', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ArchiveRequirement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveRequirement, id)
	return err
}

const archiveRequirementRecursive = `-- name: ArchiveRequirementRecursive :exec
UPDATE sdd_requirements SET status = 'archived', updated_at = NOW()
WHERE id = $1 OR parent_id = $1
`

func (q *Queries) ArchiveRequirementRecursive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveRequirementRecursive, id)
	return err
}

const getRequirementByID = `-- name: GetRequirementByID :one
SELECT id, slug, title, description, status, priority, parent_id, created_at, updated_at, project_id
FROM sdd_requirements WHERE id = $1
`

func (q *Queries) GetRequirementByID(ctx context.Context, id uuid.UUID) (SddRequirement, error) {
	row := q.db.QueryRow(ctx, getRequirementByID, id)
	var i SddRequirement
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
	)
	return i, err
}

const getRequirementBySlug = `-- name: GetRequirementBySlug :one
SELECT id, slug, title, description, status, priority, parent_id, created_at, updated_at, project_id
FROM sdd_requirements WHERE slug = $1
`

func (q *Queries) GetRequirementBySlug(ctx context.Context, slug string) (SddRequirement, error) {
	row := q.db.QueryRow(ctx, getRequirementBySlug, slug)
	var i SddRequirement
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
	)
	return i, err
}

const getRequirementTree = `-- name: GetRequirementTree :many
WITH RECURSIVE req_tree AS (
    SELECT sr.id, sr.slug, sr.title, sr.description, sr.status, sr.priority, sr.parent_id, sr.created_at, sr.updated_at, sr.project_id, 0 AS depth
    FROM sdd_requirements sr WHERE sr.slug = $1
    UNION ALL
    SELECT r.id, r.slug, r.title, r.description, r.status, r.priority, r.parent_id, r.created_at, r.updated_at, r.project_id, rt.depth + 1
    FROM sdd_requirements r
    INNER JOIN req_tree rt ON r.parent_id = rt.id
    WHERE rt.depth < 10
)
SELECT rt.id, rt.slug, rt.title, rt.description, rt.status, rt.priority, rt.parent_id, rt.created_at, rt.updated_at, rt.project_id, rt.depth
FROM req_tree rt ORDER BY rt.depth, rt.slug
`

type GetRequirementTreeRow struct {
	ID          uuid.UUID  `json:"id"`
	Slug        string     `json:"slug"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	Status      string     `json:"status"`
	Priority    string     `json:"priority"`
	ParentID    *uuid.UUID `json:"parent_id"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ProjectID   uuid.UUID  `json:"project_id"`
	Depth       int32      `json:"depth"`
}

func (q *Queries) GetRequirementTree(ctx context.Context, slug string) ([]GetRequirementTreeRow, error) {
	rows, err := q.db.Query(ctx, getRequirementTree, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRequirementTreeRow
	for rows.Next() {
		var i GetRequirementTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRequirement = `-- name: InsertRequirement :one
INSERT INTO sdd_requirements (slug, title, description, status, priority, parent_id, project_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, slug, title, description, status, priority, parent_id, created_at, updated_at, project_id
`

type InsertRequirementParams struct {
	Slug        string     `json:"slug"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	Status      string     `json:"status"`
	Priority    string     `json:"priority"`
	ParentID    *uuid.UUID `json:"parent_id"`
	ProjectID   uuid.UUID  `json:"project_id"`
}

func (q *Queries) InsertRequirement(ctx context.Context, arg InsertRequirementParams) (SddRequirement, error) {
	row := q.db.QueryRow(ctx, insertRequirement,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.ParentID,
		arg.ProjectID,
	)
	var i SddRequirement
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
	)
	return i, err
}

const listRequirements = `-- name: ListRequirements :many
SELECT id, slug, title, description, status, priority, parent_id, created_at, updated_at, project_id
FROM sdd_requirements
WHERE ($3::text IS NULL OR status = $3::text)
  AND ($4::text IS NULL OR priority = $4::text)
  AND ($5::uuid IS NULL OR parent_id = $5::uuid)
ORDER BY slug
LIMIT $1 OFFSET $2
`

type ListRequirementsParams struct {
	Limit    int32      `json:"limit"`
	Offset   int32      `json:"offset"`
	Status   *string    `json:"status"`
	Priority *string    `json:"priority"`
	ParentID *uuid.UUID `json:"parent_id"`
}

func (q *Queries) ListRequirements(ctx context.Context, arg ListRequirementsParams) ([]SddRequirement, error) {
	rows, err := q.db.Query(ctx, listRequirements,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Priority,
		arg.ParentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SddRequirement
	for rows.Next() {
		var i SddRequirement
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequirement = `-- name: UpdateRequirement :one
UPDATE sdd_requirements SET title = $2, description = $3, status = $4, priority = $5, updated_at = NOW()
WHERE slug = $1
RETURNING id, slug, title, description, status, priority, parent_id, created_at, updated_at, project_id
`

type UpdateRequirementParams struct {
	Slug        string  `json:"slug"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Status      string  `json:"status"`
	Priority    string  `json:"priority"`
}

func (q *Queries) UpdateRequirement(ctx context.Context, arg UpdateRequirementParams) (SddRequirement, error) {
	row := q.db.QueryRow(ctx, updateRequirement,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
	)
	var i SddRequirement
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
	)
	return i, err
}
