// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package cronsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getCronByID = `-- name: GetCronByID :one
SELECT id, organization_id, created_by, slug, name, COALESCE(description,'')::text AS description,
       cron_expression, timezone, target_type, target_id, inputs, enabled,
       last_run_at, next_run_at, created_at, updated_at
FROM crons WHERE id = $1 AND deleted_at IS NULL
`

type GetCronByIDRow struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	Slug           string     `json:"slug"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	CronExpression string     `json:"cron_expression"`
	Timezone       string     `json:"timezone"`
	TargetType     string     `json:"target_type"`
	TargetID       uuid.UUID  `json:"target_id"`
	Inputs         []byte     `json:"inputs"`
	Enabled        bool       `json:"enabled"`
	LastRunAt      *time.Time `json:"last_run_at"`
	NextRunAt      *time.Time `json:"next_run_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

func (q *Queries) GetCronByID(ctx context.Context, id uuid.UUID) (GetCronByIDRow, error) {
	row := q.db.QueryRow(ctx, getCronByID, id)
	var i GetCronByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CronExpression,
		&i.Timezone,
		&i.TargetType,
		&i.TargetID,
		&i.Inputs,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCron = `-- name: InsertCron :one
INSERT INTO crons
   (created_by, slug, name, description, cron_expression,
    timezone, target_type, target_id, inputs, enabled, next_run_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, organization_id, created_by, slug, name, COALESCE(description,'')::text AS description,
          cron_expression, timezone, target_type, target_id, inputs, enabled,
          last_run_at, next_run_at, created_at, updated_at
`

type InsertCronParams struct {
	CreatedBy      *uuid.UUID `json:"created_by"`
	Slug           string     `json:"slug"`
	Name           string     `json:"name"`
	Description    *string    `json:"description"`
	CronExpression string     `json:"cron_expression"`
	Timezone       string     `json:"timezone"`
	TargetType     string     `json:"target_type"`
	TargetID       uuid.UUID  `json:"target_id"`
	Inputs         []byte     `json:"inputs"`
	Enabled        bool       `json:"enabled"`
	NextRunAt      *time.Time `json:"next_run_at"`
}

type InsertCronRow struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	Slug           string     `json:"slug"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	CronExpression string     `json:"cron_expression"`
	Timezone       string     `json:"timezone"`
	TargetType     string     `json:"target_type"`
	TargetID       uuid.UUID  `json:"target_id"`
	Inputs         []byte     `json:"inputs"`
	Enabled        bool       `json:"enabled"`
	LastRunAt      *time.Time `json:"last_run_at"`
	NextRunAt      *time.Time `json:"next_run_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

func (q *Queries) InsertCron(ctx context.Context, arg InsertCronParams) (InsertCronRow, error) {
	row := q.db.QueryRow(ctx, insertCron,
		arg.CreatedBy,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.CronExpression,
		arg.Timezone,
		arg.TargetType,
		arg.TargetID,
		arg.Inputs,
		arg.Enabled,
		arg.NextRunAt,
	)
	var i InsertCronRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CronExpression,
		&i.Timezone,
		&i.TargetType,
		&i.TargetID,
		&i.Inputs,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCrons = `-- name: ListCrons :many
SELECT id, organization_id, created_by, slug, name, COALESCE(description,'')::text AS description,
       cron_expression, timezone, target_type, target_id, inputs, enabled,
       last_run_at, next_run_at, created_at, updated_at
FROM crons WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1::int
`

type ListCronsRow struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	Slug           string     `json:"slug"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	CronExpression string     `json:"cron_expression"`
	Timezone       string     `json:"timezone"`
	TargetType     string     `json:"target_type"`
	TargetID       uuid.UUID  `json:"target_id"`
	Inputs         []byte     `json:"inputs"`
	Enabled        bool       `json:"enabled"`
	LastRunAt      *time.Time `json:"last_run_at"`
	NextRunAt      *time.Time `json:"next_run_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

func (q *Queries) ListCrons(ctx context.Context, resultLimit int32) ([]ListCronsRow, error) {
	rows, err := q.db.Query(ctx, listCrons, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCronsRow
	for rows.Next() {
		var i ListCronsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CronExpression,
			&i.Timezone,
			&i.TargetType,
			&i.TargetID,
			&i.Inputs,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickDueCrons = `-- name: PickDueCrons :many
SELECT id, organization_id, created_by, slug, name, COALESCE(description,'')::text AS description,
       cron_expression, timezone, target_type, target_id, inputs, enabled,
       last_run_at, next_run_at, created_at, updated_at
FROM crons
WHERE enabled = true AND deleted_at IS NULL
  AND next_run_at IS NOT NULL AND next_run_at <= NOW()
ORDER BY next_run_at ASC
LIMIT $1::int
FOR UPDATE SKIP LOCKED
`

type PickDueCronsRow struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	Slug           string     `json:"slug"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	CronExpression string     `json:"cron_expression"`
	Timezone       string     `json:"timezone"`
	TargetType     string     `json:"target_type"`
	TargetID       uuid.UUID  `json:"target_id"`
	Inputs         []byte     `json:"inputs"`
	Enabled        bool       `json:"enabled"`
	LastRunAt      *time.Time `json:"last_run_at"`
	NextRunAt      *time.Time `json:"next_run_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

func (q *Queries) PickDueCrons(ctx context.Context, resultLimit int32) ([]PickDueCronsRow, error) {
	rows, err := q.db.Query(ctx, pickDueCrons, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PickDueCronsRow
	for rows.Next() {
		var i PickDueCronsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CronExpression,
			&i.Timezone,
			&i.TargetType,
			&i.TargetID,
			&i.Inputs,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCronEnabled = `-- name: SetCronEnabled :execrows
UPDATE crons SET enabled = $1 WHERE id = $2 AND deleted_at IS NULL
`

type SetCronEnabledParams struct {
	Enabled bool      `json:"enabled"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) SetCronEnabled(ctx context.Context, arg SetCronEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCronEnabled, arg.Enabled, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteCron = `-- name: SoftDeleteCron :execrows
UPDATE crons SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCron(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCron, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCronRun = `-- name: UpdateCronRun :exec
UPDATE crons SET last_run_at = $1, next_run_at = $2 WHERE id = $3
`

type UpdateCronRunParams struct {
	LastRunAt *time.Time `json:"last_run_at"`
	NextRunAt *time.Time `json:"next_run_at"`
	ID        uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateCronRun(ctx context.Context, arg UpdateCronRunParams) error {
	_, err := q.db.Exec(ctx, updateCronRun, arg.LastRunAt, arg.NextRunAt, arg.ID)
	return err
}
