// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package projectdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getProjectByID = `-- name: GetProjectByID :one
SELECT
    p.id,
    p.name,
    p.slug,
    COALESCE(p.description, '')::text AS description,
    COALESCE(p.repository_url, '')::text AS repository_url,
    p.template_id,
    p.settings,
    p.client_id,
    COALESCE(c.slug, '')::text AS client_slug,
    COALESCE(c.name, '')::text AS client_name,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM projects p
LEFT JOIN project_clients c ON c.id = p.client_id
WHERE p.id = $1
`

type GetProjectByIDRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	Description   string             `json:"description"`
	RepositoryUrl string             `json:"repository_url"`
	TemplateID    *uuid.UUID         `json:"template_id"`
	Settings      []byte             `json:"settings"`
	ClientID      *uuid.UUID         `json:"client_id"`
	ClientSlug    string             `json:"client_slug"`
	ClientName    string             `json:"client_name"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (GetProjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.RepositoryUrl,
		&i.TemplateID,
		&i.Settings,
		&i.ClientID,
		&i.ClientSlug,
		&i.ClientName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT
    p.id,
    p.name,
    p.slug,
    COALESCE(p.description, '')::text AS description,
    COALESCE(p.repository_url, '')::text AS repository_url,
    p.template_id,
    p.settings,
    p.client_id,
    COALESCE(c.slug, '')::text AS client_slug,
    COALESCE(c.name, '')::text AS client_name,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM projects p
LEFT JOIN project_clients c ON c.id = p.client_id
WHERE p.slug = $1 AND p.deleted_at IS NULL
`

type GetProjectBySlugRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	Description   string             `json:"description"`
	RepositoryUrl string             `json:"repository_url"`
	TemplateID    *uuid.UUID         `json:"template_id"`
	Settings      []byte             `json:"settings"`
	ClientID      *uuid.UUID         `json:"client_id"`
	ClientSlug    string             `json:"client_slug"`
	ClientName    string             `json:"client_name"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (GetProjectBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i GetProjectBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.RepositoryUrl,
		&i.TemplateID,
		&i.Settings,
		&i.ClientID,
		&i.ClientSlug,
		&i.ClientName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (name, slug, description, repository_url, template_id, settings, client_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id
`

type InsertProjectParams struct {
	Name          string     `json:"name"`
	Slug          string     `json:"slug"`
	Description   *string    `json:"description"`
	RepositoryUrl *string    `json:"repository_url"`
	TemplateID    *uuid.UUID `json:"template_id"`
	Settings      []byte     `json:"settings"`
	ClientID      *uuid.UUID `json:"client_id"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertProject,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.RepositoryUrl,
		arg.TemplateID,
		arg.Settings,
		arg.ClientID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listProjects = `-- name: ListProjects :many
SELECT
    p.id,
    p.name,
    p.slug,
    COALESCE(p.description, '')::text AS description,
    COALESCE(p.repository_url, '')::text AS repository_url,
    p.template_id,
    p.settings,
    p.client_id,
    COALESCE(c.slug, '')::text AS client_slug,
    COALESCE(c.name, '')::text AS client_name,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM projects p
LEFT JOIN project_clients c ON c.id = p.client_id
WHERE p.deleted_at IS NULL
    AND ($1::uuid IS NULL OR p.client_id = $1::uuid)
ORDER BY p.created_at DESC
`

type ListProjectsRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	Description   string             `json:"description"`
	RepositoryUrl string             `json:"repository_url"`
	TemplateID    *uuid.UUID         `json:"template_id"`
	Settings      []byte             `json:"settings"`
	ClientID      *uuid.UUID         `json:"client_id"`
	ClientSlug    string             `json:"client_slug"`
	ClientName    string             `json:"client_name"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListProjects(ctx context.Context, clientID *uuid.UUID) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.RepositoryUrl,
			&i.TemplateID,
			&i.Settings,
			&i.ClientID,
			&i.ClientSlug,
			&i.ClientName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects
SET name = $1,
    description = $2,
    repository_url = $3,
    settings = $4
WHERE id = $5 AND deleted_at IS NULL
`

type UpdateProjectParams struct {
	Name          string    `json:"name"`
	Description   *string   `json:"description"`
	RepositoryUrl *string   `json:"repository_url"`
	Settings      []byte    `json:"settings"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.Exec(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.RepositoryUrl,
		arg.Settings,
		arg.ID,
	)
	return err
}

const updateProjectWithClient = `-- name: UpdateProjectWithClient :exec
UPDATE projects
SET name = $1,
    description = $2,
    repository_url = $3,
    settings = $4,
    client_id = $5
WHERE id = $6 AND deleted_at IS NULL
`

type UpdateProjectWithClientParams struct {
	Name          string     `json:"name"`
	Description   *string    `json:"description"`
	RepositoryUrl *string    `json:"repository_url"`
	Settings      []byte     `json:"settings"`
	ClientID      *uuid.UUID `json:"client_id"`
	ID            uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateProjectWithClient(ctx context.Context, arg UpdateProjectWithClientParams) error {
	_, err := q.db.Exec(ctx, updateProjectWithClient,
		arg.Name,
		arg.Description,
		arg.RepositoryUrl,
		arg.Settings,
		arg.ClientID,
		arg.ID,
	)
	return err
}
