// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package policydb

import (
	"time"

	"github.com/google/uuid"
)

type PlatformPolicy struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	Kind           string    `json:"kind"`
	BodyMd         string    `json:"body_md"`
	BodyStructured []byte    `json:"body_structured"`
	Version        int32     `json:"version"`
	IsActive       bool      `json:"is_active"`
	SourceFile     *string   `json:"source_file"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	IsUserModified bool      `json:"is_user_modified"`
}
