// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package policydb

import (
	"context"

	"github.com/google/uuid"
)

const deactivatePolicy = `-- name: DeactivatePolicy :execrows
UPDATE platform_policies SET is_active = FALSE WHERE id = $1 AND is_active = TRUE
`

func (q *Queries) DeactivatePolicy(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivatePolicy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActivePolicyBySlug = `-- name: GetActivePolicyBySlug :one
SELECT id, slug, name, kind, body_md, body_structured, version, is_active, source_file, created_at, updated_at, is_user_modified
FROM platform_policies WHERE slug = $1 AND is_active = TRUE
`

func (q *Queries) GetActivePolicyBySlug(ctx context.Context, slug string) (PlatformPolicy, error) {
	row := q.db.QueryRow(ctx, getActivePolicyBySlug, slug)
	var i PlatformPolicy
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.BodyMd,
		&i.BodyStructured,
		&i.Version,
		&i.IsActive,
		&i.SourceFile,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsUserModified,
	)
	return i, err
}

const getPolicyForUpdate = `-- name: GetPolicyForUpdate :one
SELECT id, slug, name, kind, body_md, body_structured, version, is_active, source_file, created_at, updated_at, is_user_modified
FROM platform_policies WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPolicyForUpdate(ctx context.Context, id uuid.UUID) (PlatformPolicy, error) {
	row := q.db.QueryRow(ctx, getPolicyForUpdate, id)
	var i PlatformPolicy
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.BodyMd,
		&i.BodyStructured,
		&i.Version,
		&i.IsActive,
		&i.SourceFile,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsUserModified,
	)
	return i, err
}

const insertPolicy = `-- name: InsertPolicy :one
INSERT INTO platform_policies (slug, name, kind, body_md, body_structured, source_file)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slug, name, kind, body_md, body_structured, version, is_active, source_file, created_at, updated_at, is_user_modified
`

type InsertPolicyParams struct {
	Slug           string  `json:"slug"`
	Name           string  `json:"name"`
	Kind           string  `json:"kind"`
	BodyMd         string  `json:"body_md"`
	BodyStructured []byte  `json:"body_structured"`
	SourceFile     *string `json:"source_file"`
}

func (q *Queries) InsertPolicy(ctx context.Context, arg InsertPolicyParams) (PlatformPolicy, error) {
	row := q.db.QueryRow(ctx, insertPolicy,
		arg.Slug,
		arg.Name,
		arg.Kind,
		arg.BodyMd,
		arg.BodyStructured,
		arg.SourceFile,
	)
	var i PlatformPolicy
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.BodyMd,
		&i.BodyStructured,
		&i.Version,
		&i.IsActive,
		&i.SourceFile,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsUserModified,
	)
	return i, err
}

const insertPolicyVersion = `-- name: InsertPolicyVersion :exec
INSERT INTO platform_policy_versions (policy_id, version, body_md, body_structured, changed_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPolicyVersionParams struct {
	PolicyID       uuid.UUID  `json:"policy_id"`
	Version        int32      `json:"version"`
	BodyMd         string     `json:"body_md"`
	BodyStructured []byte     `json:"body_structured"`
	ChangedBy      *uuid.UUID `json:"changed_by"`
}

func (q *Queries) InsertPolicyVersion(ctx context.Context, arg InsertPolicyVersionParams) error {
	_, err := q.db.Exec(ctx, insertPolicyVersion,
		arg.PolicyID,
		arg.Version,
		arg.BodyMd,
		arg.BodyStructured,
		arg.ChangedBy,
	)
	return err
}

const listActivePolicies = `-- name: ListActivePolicies :many
SELECT id, slug, name, kind, body_md, body_structured, version, is_active, source_file, created_at, updated_at, is_user_modified
FROM platform_policies
WHERE is_active = TRUE
  AND ($1::text IS NULL OR kind = $1::text)
ORDER BY kind, slug
`

func (q *Queries) ListActivePolicies(ctx context.Context, kind *string) ([]PlatformPolicy, error) {
	rows, err := q.db.Query(ctx, listActivePolicies, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformPolicy
	for rows.Next() {
		var i PlatformPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.BodyMd,
			&i.BodyStructured,
			&i.Version,
			&i.IsActive,
			&i.SourceFile,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsUserModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicyBody = `-- name: UpdatePolicyBody :exec
UPDATE platform_policies
SET body_md = $2, body_structured = $3, version = version + 1, is_user_modified = TRUE
WHERE id = $1
`

type UpdatePolicyBodyParams struct {
	ID             uuid.UUID `json:"id"`
	BodyMd         string    `json:"body_md"`
	BodyStructured []byte    `json:"body_structured"`
}

func (q *Queries) UpdatePolicyBody(ctx context.Context, arg UpdatePolicyBodyParams) error {
	_, err := q.db.Exec(ctx, updatePolicyBody, arg.ID, arg.BodyMd, arg.BodyStructured)
	return err
}
