// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package skilldb

import (
	"time"

	"github.com/google/uuid"
)

type SkillVersion struct {
	ID           uuid.UUID  `json:"id"`
	SkillID      uuid.UUID  `json:"skill_id"`
	Version      int32      `json:"version"`
	Content      *string    `json:"content"`
	InputSchema  []byte     `json:"input_schema"`
	OutputSchema []byte     `json:"output_schema"`
	Changelog    *string    `json:"changelog"`
	CreatedBy    *uuid.UUID `json:"created_by"`
	CreatedAt    time.Time  `json:"created_at"`
}
