// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package skilldb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const executionCreate = `-- name: ExecutionCreate :one
INSERT INTO skill_executions (skill_id, version_used, mode, status, parameters, created_by, started_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, skill_id, version_used, mode, status, parameters, output, error, execution_time_ms, started_at, completed_at, created_at
`

type ExecutionCreateParams struct {
	SkillID     uuid.UUID  `json:"skill_id"`
	VersionUsed *int32     `json:"version_used"`
	Mode        string     `json:"mode"`
	Status      string     `json:"status"`
	Parameters  []byte     `json:"parameters"`
	CreatedBy   *uuid.UUID `json:"created_by"`
}

type ExecutionCreateRow struct {
	ID              uuid.UUID          `json:"id"`
	SkillID         uuid.UUID          `json:"skill_id"`
	VersionUsed     *int32             `json:"version_used"`
	Mode            string             `json:"mode"`
	Status          string             `json:"status"`
	Parameters      []byte             `json:"parameters"`
	Output          *string            `json:"output"`
	Error           *string            `json:"error"`
	ExecutionTimeMs *int32             `json:"execution_time_ms"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

// skill: execution.go
func (q *Queries) ExecutionCreate(ctx context.Context, arg ExecutionCreateParams) (ExecutionCreateRow, error) {
	row := q.db.QueryRow(ctx, executionCreate,
		arg.SkillID,
		arg.VersionUsed,
		arg.Mode,
		arg.Status,
		arg.Parameters,
		arg.CreatedBy,
	)
	var i ExecutionCreateRow
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.VersionUsed,
		&i.Mode,
		&i.Status,
		&i.Parameters,
		&i.Output,
		&i.Error,
		&i.ExecutionTimeMs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const executionGetByID = `-- name: ExecutionGetByID :one
SELECT id, skill_id, version_used, mode, status, parameters, output, error, execution_time_ms, started_at, completed_at, created_at
FROM skill_executions WHERE id = $1
`

type ExecutionGetByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	SkillID         uuid.UUID          `json:"skill_id"`
	VersionUsed     *int32             `json:"version_used"`
	Mode            string             `json:"mode"`
	Status          string             `json:"status"`
	Parameters      []byte             `json:"parameters"`
	Output          *string            `json:"output"`
	Error           *string            `json:"error"`
	ExecutionTimeMs *int32             `json:"execution_time_ms"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

func (q *Queries) ExecutionGetByID(ctx context.Context, id uuid.UUID) (ExecutionGetByIDRow, error) {
	row := q.db.QueryRow(ctx, executionGetByID, id)
	var i ExecutionGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.VersionUsed,
		&i.Mode,
		&i.Status,
		&i.Parameters,
		&i.Output,
		&i.Error,
		&i.ExecutionTimeMs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const executionSetCompleted = `-- name: ExecutionSetCompleted :exec
UPDATE skill_executions SET status = 'completed', output = $1, execution_time_ms = $2, completed_at = NOW() WHERE id = $3
`

type ExecutionSetCompletedParams struct {
	Output          *string   `json:"output"`
	ExecutionTimeMs *int32    `json:"execution_time_ms"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) ExecutionSetCompleted(ctx context.Context, arg ExecutionSetCompletedParams) error {
	_, err := q.db.Exec(ctx, executionSetCompleted, arg.Output, arg.ExecutionTimeMs, arg.ID)
	return err
}

const executionSetFailed = `-- name: ExecutionSetFailed :exec
UPDATE skill_executions SET status = 'failed', error = $1, execution_time_ms = $2, completed_at = NOW() WHERE id = $3
`

type ExecutionSetFailedParams struct {
	Error           *string   `json:"error"`
	ExecutionTimeMs *int32    `json:"execution_time_ms"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) ExecutionSetFailed(ctx context.Context, arg ExecutionSetFailedParams) error {
	_, err := q.db.Exec(ctx, executionSetFailed, arg.Error, arg.ExecutionTimeMs, arg.ID)
	return err
}

const executionSetRunning = `-- name: ExecutionSetRunning :exec
UPDATE skill_executions SET status = 'running' WHERE id = $1 AND status = 'pending'
`

func (q *Queries) ExecutionSetRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, executionSetRunning, id)
	return err
}

const skillApplicableIDs = `-- name: SkillApplicableIDs :many
SELECT s.id FROM skills s
WHERE s.deleted_at IS NULL AND s.proposed = FALSE
  AND (s.project_id IS NULL OR s.project_id = $1)
  AND NOT EXISTS (
    SELECT 1 FROM project_skills ps
    WHERE ps.skill_id = s.id AND ps.project_id = $1 AND ps.is_enabled = FALSE
  )
`

func (q *Queries) SkillApplicableIDs(ctx context.Context, projectID *uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, skillApplicableIDs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skillCreate = `-- name: SkillCreate :one
INSERT INTO skills (
  slug, name, description, skill_type, content,
  input_schema, output_schema, timeout_seconds, idempotent,
  has_side_effects, depends_on, tags, embedding
) VALUES (
  $1, $2, $3,
  $4, $5,
  $6, $7,
  $8, $9,
  $10, $11, $12,
  $13::vector
)
RETURNING id, slug, name, COALESCE(description,'')::text AS description,
          skill_type, COALESCE(content,'')::text AS content,
          input_schema, output_schema,
          timeout_seconds, idempotent, has_side_effects, depends_on, tags,
          seed_managed, seed_version, is_user_modified, created_at, updated_at
`

type SkillCreateParams struct {
	Slug           string           `json:"slug"`
	Name           string           `json:"name"`
	Description    *string          `json:"description"`
	SkillType      string           `json:"skill_type"`
	Content        *string          `json:"content"`
	InputSchema    []byte           `json:"input_schema"`
	OutputSchema   []byte           `json:"output_schema"`
	TimeoutSeconds int32            `json:"timeout_seconds"`
	Idempotent     bool             `json:"idempotent"`
	HasSideEffects bool             `json:"has_side_effects"`
	DependsOn      []string         `json:"depends_on"`
	Tags           []string         `json:"tags"`
	Embedding      *pgvector.Vector `json:"embedding"`
}

type SkillCreateRow struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	SkillType      string    `json:"skill_type"`
	Content        string    `json:"content"`
	InputSchema    []byte    `json:"input_schema"`
	OutputSchema   []byte    `json:"output_schema"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
	Idempotent     bool      `json:"idempotent"`
	HasSideEffects bool      `json:"has_side_effects"`
	DependsOn      []string  `json:"depends_on"`
	Tags           []string  `json:"tags"`
	SeedManaged    bool      `json:"seed_managed"`
	SeedVersion    *int32    `json:"seed_version"`
	IsUserModified bool      `json:"is_user_modified"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// skill: service.go
func (q *Queries) SkillCreate(ctx context.Context, arg SkillCreateParams) (SkillCreateRow, error) {
	row := q.db.QueryRow(ctx, skillCreate,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.SkillType,
		arg.Content,
		arg.InputSchema,
		arg.OutputSchema,
		arg.TimeoutSeconds,
		arg.Idempotent,
		arg.HasSideEffects,
		arg.DependsOn,
		arg.Tags,
		arg.Embedding,
	)
	var i SkillCreateRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SkillType,
		&i.Content,
		&i.InputSchema,
		&i.OutputSchema,
		&i.TimeoutSeconds,
		&i.Idempotent,
		&i.HasSideEffects,
		&i.DependsOn,
		&i.Tags,
		&i.SeedManaged,
		&i.SeedVersion,
		&i.IsUserModified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const skillGetByID = `-- name: SkillGetByID :one
SELECT id, slug, name, COALESCE(description,'')::text AS description,
       skill_type, COALESCE(content,'')::text AS content,
       input_schema, output_schema,
       timeout_seconds, idempotent, has_side_effects, depends_on, tags,
       seed_managed, seed_version, is_user_modified, created_at, updated_at
FROM skills WHERE id = $1 AND deleted_at IS NULL
`

type SkillGetByIDRow struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	SkillType      string    `json:"skill_type"`
	Content        string    `json:"content"`
	InputSchema    []byte    `json:"input_schema"`
	OutputSchema   []byte    `json:"output_schema"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
	Idempotent     bool      `json:"idempotent"`
	HasSideEffects bool      `json:"has_side_effects"`
	DependsOn      []string  `json:"depends_on"`
	Tags           []string  `json:"tags"`
	SeedManaged    bool      `json:"seed_managed"`
	SeedVersion    *int32    `json:"seed_version"`
	IsUserModified bool      `json:"is_user_modified"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) SkillGetByID(ctx context.Context, id uuid.UUID) (SkillGetByIDRow, error) {
	row := q.db.QueryRow(ctx, skillGetByID, id)
	var i SkillGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SkillType,
		&i.Content,
		&i.InputSchema,
		&i.OutputSchema,
		&i.TimeoutSeconds,
		&i.Idempotent,
		&i.HasSideEffects,
		&i.DependsOn,
		&i.Tags,
		&i.SeedManaged,
		&i.SeedVersion,
		&i.IsUserModified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const skillGetBySlug = `-- name: SkillGetBySlug :one
SELECT id, slug, name, COALESCE(description,'')::text AS description,
       skill_type, COALESCE(content,'')::text AS content,
       input_schema, output_schema,
       timeout_seconds, idempotent, has_side_effects, depends_on, tags,
       seed_managed, seed_version, is_user_modified, created_at, updated_at
FROM skills WHERE slug = $1 AND deleted_at IS NULL AND proposed = false
`

type SkillGetBySlugRow struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	SkillType      string    `json:"skill_type"`
	Content        string    `json:"content"`
	InputSchema    []byte    `json:"input_schema"`
	OutputSchema   []byte    `json:"output_schema"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
	Idempotent     bool      `json:"idempotent"`
	HasSideEffects bool      `json:"has_side_effects"`
	DependsOn      []string  `json:"depends_on"`
	Tags           []string  `json:"tags"`
	SeedManaged    bool      `json:"seed_managed"`
	SeedVersion    *int32    `json:"seed_version"`
	IsUserModified bool      `json:"is_user_modified"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) SkillGetBySlug(ctx context.Context, slug string) (SkillGetBySlugRow, error) {
	row := q.db.QueryRow(ctx, skillGetBySlug, slug)
	var i SkillGetBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SkillType,
		&i.Content,
		&i.InputSchema,
		&i.OutputSchema,
		&i.TimeoutSeconds,
		&i.Idempotent,
		&i.HasSideEffects,
		&i.DependsOn,
		&i.Tags,
		&i.SeedManaged,
		&i.SeedVersion,
		&i.IsUserModified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const skillList = `-- name: SkillList :many
SELECT id, slug, name, COALESCE(description,'')::text AS description,
       skill_type, COALESCE(content,'')::text AS content,
       input_schema, output_schema,
       timeout_seconds, idempotent, has_side_effects, depends_on, tags,
       seed_managed, seed_version, is_user_modified, created_at, updated_at
FROM skills
WHERE deleted_at IS NULL AND proposed = false
  AND ($1::text IS NULL OR skill_type = $1::text)
  AND ($2::text IS NULL OR $2::text = ANY(tags))
ORDER BY created_at DESC
LIMIT $3::int
`

type SkillListParams struct {
	SkillType   *string `json:"skill_type"`
	Tag         *string `json:"tag"`
	ResultLimit int32   `json:"result_limit"`
}

type SkillListRow struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	SkillType      string    `json:"skill_type"`
	Content        string    `json:"content"`
	InputSchema    []byte    `json:"input_schema"`
	OutputSchema   []byte    `json:"output_schema"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
	Idempotent     bool      `json:"idempotent"`
	HasSideEffects bool      `json:"has_side_effects"`
	DependsOn      []string  `json:"depends_on"`
	Tags           []string  `json:"tags"`
	SeedManaged    bool      `json:"seed_managed"`
	SeedVersion    *int32    `json:"seed_version"`
	IsUserModified bool      `json:"is_user_modified"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) SkillList(ctx context.Context, arg SkillListParams) ([]SkillListRow, error) {
	rows, err := q.db.Query(ctx, skillList, arg.SkillType, arg.Tag, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillListRow
	for rows.Next() {
		var i SkillListRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.SkillType,
			&i.Content,
			&i.InputSchema,
			&i.OutputSchema,
			&i.TimeoutSeconds,
			&i.Idempotent,
			&i.HasSideEffects,
			&i.DependsOn,
			&i.Tags,
			&i.SeedManaged,
			&i.SeedVersion,
			&i.IsUserModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skillSearchHybridBM25Only = `-- name: SkillSearchHybridBM25Only :many
SELECT s.id, s.slug, s.name, COALESCE(s.description,'')::text AS description,
       s.skill_type, COALESCE(s.content,'')::text AS content,
       s.input_schema, s.output_schema,
       s.timeout_seconds, s.idempotent, s.has_side_effects, s.depends_on, s.tags,
       s.seed_managed, s.seed_version, s.is_user_modified, s.created_at, s.updated_at,
       ts_rank(s.description_tsv, q)::float8 AS score,
       0::bigint AS bm25_rank,
       0::bigint AS vec_rank
FROM skills s, plainto_tsquery('spanish', $1) AS q
WHERE s.deleted_at IS NULL AND s.proposed = false AND s.description_tsv @@ q
ORDER BY score DESC
LIMIT $2::int
`

type SkillSearchHybridBM25OnlyParams struct {
	QueryText   string `json:"query_text"`
	ResultLimit int32  `json:"result_limit"`
}

type SkillSearchHybridBM25OnlyRow struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	SkillType      string    `json:"skill_type"`
	Content        string    `json:"content"`
	InputSchema    []byte    `json:"input_schema"`
	OutputSchema   []byte    `json:"output_schema"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
	Idempotent     bool      `json:"idempotent"`
	HasSideEffects bool      `json:"has_side_effects"`
	DependsOn      []string  `json:"depends_on"`
	Tags           []string  `json:"tags"`
	SeedManaged    bool      `json:"seed_managed"`
	SeedVersion    *int32    `json:"seed_version"`
	IsUserModified bool      `json:"is_user_modified"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Score          float64   `json:"score"`
	Bm25Rank       int64     `json:"bm25_rank"`
	VecRank        int64     `json:"vec_rank"`
}

func (q *Queries) SkillSearchHybridBM25Only(ctx context.Context, arg SkillSearchHybridBM25OnlyParams) ([]SkillSearchHybridBM25OnlyRow, error) {
	rows, err := q.db.Query(ctx, skillSearchHybridBM25Only, arg.QueryText, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillSearchHybridBM25OnlyRow
	for rows.Next() {
		var i SkillSearchHybridBM25OnlyRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.SkillType,
			&i.Content,
			&i.InputSchema,
			&i.OutputSchema,
			&i.TimeoutSeconds,
			&i.Idempotent,
			&i.HasSideEffects,
			&i.DependsOn,
			&i.Tags,
			&i.SeedManaged,
			&i.SeedVersion,
			&i.IsUserModified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Score,
			&i.Bm25Rank,
			&i.VecRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skillSearchHybridWithVector = `-- name: SkillSearchHybridWithVector :many
WITH bm25 AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY ts_rank(description_tsv, q) DESC) AS r
  FROM skills, plainto_tsquery('spanish', $2) AS q
  WHERE deleted_at IS NULL AND proposed = false AND description_tsv @@ q
  LIMIT $3::int
),
vec AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY embedding <=> $4::vector ASC) AS r
  FROM skills
  WHERE deleted_at IS NULL AND proposed = false AND embedding IS NOT NULL
  LIMIT $3::int
),
fused AS (
  SELECT COALESCE(bm25.id, vec.id) AS id,
         COALESCE(1.0 / ($5::int + bm25.r), 0) + COALESCE(1.0 / ($5::int + vec.r), 0) AS score,
         COALESCE(bm25.r, 0) AS bm25_rank,
         COALESCE(vec.r, 0) AS vec_rank
  FROM bm25 FULL OUTER JOIN vec ON bm25.id = vec.id
)
SELECT s.id, s.slug, s.name, COALESCE(s.description,'')::text AS description,
       s.skill_type, COALESCE(s.content,'')::text AS content,
       s.input_schema, s.output_schema,
       s.timeout_seconds, s.idempotent, s.has_side_effects, s.depends_on, s.tags,
       s.seed_managed, s.seed_version, s.is_user_modified, s.created_at, s.updated_at,
       f.score::float8 AS score, f.bm25_rank::bigint AS bm25_rank, f.vec_rank::bigint AS vec_rank
FROM fused f
JOIN skills s ON s.id = f.id
ORDER BY f.score DESC
LIMIT $1::int
`

type SkillSearchHybridWithVectorParams struct {
	ResultLimit int32            `json:"result_limit"`
	QueryText   string           `json:"query_text"`
	Candidates  int32            `json:"candidates"`
	QueryVec    *pgvector.Vector `json:"query_vec"`
	RrfK        int32            `json:"rrf_k"`
}

type SkillSearchHybridWithVectorRow struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	SkillType      string    `json:"skill_type"`
	Content        string    `json:"content"`
	InputSchema    []byte    `json:"input_schema"`
	OutputSchema   []byte    `json:"output_schema"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
	Idempotent     bool      `json:"idempotent"`
	HasSideEffects bool      `json:"has_side_effects"`
	DependsOn      []string  `json:"depends_on"`
	Tags           []string  `json:"tags"`
	SeedManaged    bool      `json:"seed_managed"`
	SeedVersion    *int32    `json:"seed_version"`
	IsUserModified bool      `json:"is_user_modified"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Score          float64   `json:"score"`
	Bm25Rank       int64     `json:"bm25_rank"`
	VecRank        int64     `json:"vec_rank"`
}

func (q *Queries) SkillSearchHybridWithVector(ctx context.Context, arg SkillSearchHybridWithVectorParams) ([]SkillSearchHybridWithVectorRow, error) {
	rows, err := q.db.Query(ctx, skillSearchHybridWithVector,
		arg.ResultLimit,
		arg.QueryText,
		arg.Candidates,
		arg.QueryVec,
		arg.RrfK,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillSearchHybridWithVectorRow
	for rows.Next() {
		var i SkillSearchHybridWithVectorRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.SkillType,
			&i.Content,
			&i.InputSchema,
			&i.OutputSchema,
			&i.TimeoutSeconds,
			&i.Idempotent,
			&i.HasSideEffects,
			&i.DependsOn,
			&i.Tags,
			&i.SeedManaged,
			&i.SeedVersion,
			&i.IsUserModified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Score,
			&i.Bm25Rank,
			&i.VecRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skillSoftDelete = `-- name: SkillSoftDelete :exec
UPDATE skills SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SkillSoftDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, skillSoftDelete, id)
	return err
}

const skillSoftDeleteCountDeps = `-- name: SkillSoftDeleteCountDeps :one
SELECT COUNT(*) FROM skills
WHERE deleted_at IS NULL AND $1::text = ANY(depends_on)
`

func (q *Queries) SkillSoftDeleteCountDeps(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRow(ctx, skillSoftDeleteCountDeps, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const skillUpdate = `-- name: SkillUpdate :one
UPDATE skills
SET name = $1,
    description = $2,
    content = $3,
    input_schema = $4,
    output_schema = $5,
    timeout_seconds = $6,
    idempotent = $7,
    has_side_effects = $8,
    depends_on = $9,
    tags = $10,
    is_user_modified = $11
WHERE id = $12 AND deleted_at IS NULL
RETURNING id, slug, name, COALESCE(description,'')::text AS description,
          skill_type, COALESCE(content,'')::text AS content,
          input_schema, output_schema,
          timeout_seconds, idempotent, has_side_effects, depends_on, tags,
          seed_managed, seed_version, is_user_modified, created_at, updated_at
`

type SkillUpdateParams struct {
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	Content        *string   `json:"content"`
	InputSchema    []byte    `json:"input_schema"`
	OutputSchema   []byte    `json:"output_schema"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
	Idempotent     bool      `json:"idempotent"`
	HasSideEffects bool      `json:"has_side_effects"`
	DependsOn      []string  `json:"depends_on"`
	Tags           []string  `json:"tags"`
	IsUserModified bool      `json:"is_user_modified"`
	ID             uuid.UUID `json:"id"`
}

type SkillUpdateRow struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	SkillType      string    `json:"skill_type"`
	Content        string    `json:"content"`
	InputSchema    []byte    `json:"input_schema"`
	OutputSchema   []byte    `json:"output_schema"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
	Idempotent     bool      `json:"idempotent"`
	HasSideEffects bool      `json:"has_side_effects"`
	DependsOn      []string  `json:"depends_on"`
	Tags           []string  `json:"tags"`
	SeedManaged    bool      `json:"seed_managed"`
	SeedVersion    *int32    `json:"seed_version"`
	IsUserModified bool      `json:"is_user_modified"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) SkillUpdate(ctx context.Context, arg SkillUpdateParams) (SkillUpdateRow, error) {
	row := q.db.QueryRow(ctx, skillUpdate,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.InputSchema,
		arg.OutputSchema,
		arg.TimeoutSeconds,
		arg.Idempotent,
		arg.HasSideEffects,
		arg.DependsOn,
		arg.Tags,
		arg.IsUserModified,
		arg.ID,
	)
	var i SkillUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SkillType,
		&i.Content,
		&i.InputSchema,
		&i.OutputSchema,
		&i.TimeoutSeconds,
		&i.Idempotent,
		&i.HasSideEffects,
		&i.DependsOn,
		&i.Tags,
		&i.SeedManaged,
		&i.SeedVersion,
		&i.IsUserModified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const skillUpdateWithEmbedding = `-- name: SkillUpdateWithEmbedding :one
UPDATE skills
SET name = $1,
    description = $2,
    content = $3,
    input_schema = $4,
    output_schema = $5,
    timeout_seconds = $6,
    idempotent = $7,
    has_side_effects = $8,
    depends_on = $9,
    tags = $10,
    is_user_modified = $11,
    embedding = $12::vector
WHERE id = $13 AND deleted_at IS NULL
RETURNING id, slug, name, COALESCE(description,'')::text AS description,
          skill_type, COALESCE(content,'')::text AS content,
          input_schema, output_schema,
          timeout_seconds, idempotent, has_side_effects, depends_on, tags,
          seed_managed, seed_version, is_user_modified, created_at, updated_at
`

type SkillUpdateWithEmbeddingParams struct {
	Name           string           `json:"name"`
	Description    *string          `json:"description"`
	Content        *string          `json:"content"`
	InputSchema    []byte           `json:"input_schema"`
	OutputSchema   []byte           `json:"output_schema"`
	TimeoutSeconds int32            `json:"timeout_seconds"`
	Idempotent     bool             `json:"idempotent"`
	HasSideEffects bool             `json:"has_side_effects"`
	DependsOn      []string         `json:"depends_on"`
	Tags           []string         `json:"tags"`
	IsUserModified bool             `json:"is_user_modified"`
	Embedding      *pgvector.Vector `json:"embedding"`
	ID             uuid.UUID        `json:"id"`
}

type SkillUpdateWithEmbeddingRow struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	SkillType      string    `json:"skill_type"`
	Content        string    `json:"content"`
	InputSchema    []byte    `json:"input_schema"`
	OutputSchema   []byte    `json:"output_schema"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
	Idempotent     bool      `json:"idempotent"`
	HasSideEffects bool      `json:"has_side_effects"`
	DependsOn      []string  `json:"depends_on"`
	Tags           []string  `json:"tags"`
	SeedManaged    bool      `json:"seed_managed"`
	SeedVersion    *int32    `json:"seed_version"`
	IsUserModified bool      `json:"is_user_modified"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) SkillUpdateWithEmbedding(ctx context.Context, arg SkillUpdateWithEmbeddingParams) (SkillUpdateWithEmbeddingRow, error) {
	row := q.db.QueryRow(ctx, skillUpdateWithEmbedding,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.InputSchema,
		arg.OutputSchema,
		arg.TimeoutSeconds,
		arg.Idempotent,
		arg.HasSideEffects,
		arg.DependsOn,
		arg.Tags,
		arg.IsUserModified,
		arg.Embedding,
		arg.ID,
	)
	var i SkillUpdateWithEmbeddingRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SkillType,
		&i.Content,
		&i.InputSchema,
		&i.OutputSchema,
		&i.TimeoutSeconds,
		&i.Idempotent,
		&i.HasSideEffects,
		&i.DependsOn,
		&i.Tags,
		&i.SeedManaged,
		&i.SeedVersion,
		&i.IsUserModified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const versionCreate = `-- name: VersionCreate :one
INSERT INTO skill_versions (skill_id, version, content, input_schema, output_schema, changelog, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, skill_id, version, content, input_schema, output_schema, changelog, created_by, created_at
`

type VersionCreateParams struct {
	SkillID      uuid.UUID  `json:"skill_id"`
	Version      int32      `json:"version"`
	Content      *string    `json:"content"`
	InputSchema  []byte     `json:"input_schema"`
	OutputSchema []byte     `json:"output_schema"`
	Changelog    *string    `json:"changelog"`
	CreatedBy    *uuid.UUID `json:"created_by"`
}

func (q *Queries) VersionCreate(ctx context.Context, arg VersionCreateParams) (SkillVersion, error) {
	row := q.db.QueryRow(ctx, versionCreate,
		arg.SkillID,
		arg.Version,
		arg.Content,
		arg.InputSchema,
		arg.OutputSchema,
		arg.Changelog,
		arg.CreatedBy,
	)
	var i SkillVersion
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.Version,
		&i.Content,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Changelog,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const versionGetBySkillAndVersion = `-- name: VersionGetBySkillAndVersion :one
SELECT id, skill_id, version, content, input_schema, output_schema, changelog, created_by, created_at
FROM skill_versions WHERE skill_id = $1 AND version = $2
`

type VersionGetBySkillAndVersionParams struct {
	SkillID uuid.UUID `json:"skill_id"`
	Version int32     `json:"version"`
}

func (q *Queries) VersionGetBySkillAndVersion(ctx context.Context, arg VersionGetBySkillAndVersionParams) (SkillVersion, error) {
	row := q.db.QueryRow(ctx, versionGetBySkillAndVersion, arg.SkillID, arg.Version)
	var i SkillVersion
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.Version,
		&i.Content,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Changelog,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const versionGetPinned = `-- name: VersionGetPinned :one
SELECT pinned_version FROM skills WHERE id = $1
`

func (q *Queries) VersionGetPinned(ctx context.Context, id uuid.UUID) (*int32, error) {
	row := q.db.QueryRow(ctx, versionGetPinned, id)
	var pinned_version *int32
	err := row.Scan(&pinned_version)
	return pinned_version, err
}

const versionListBySkill = `-- name: VersionListBySkill :many
SELECT id, skill_id, version, content, input_schema, output_schema, changelog, created_by, created_at
FROM skill_versions WHERE skill_id = $1 ORDER BY version DESC
`

func (q *Queries) VersionListBySkill(ctx context.Context, skillID uuid.UUID) ([]SkillVersion, error) {
	rows, err := q.db.Query(ctx, versionListBySkill, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillVersion
	for rows.Next() {
		var i SkillVersion
		if err := rows.Scan(
			&i.ID,
			&i.SkillID,
			&i.Version,
			&i.Content,
			&i.InputSchema,
			&i.OutputSchema,
			&i.Changelog,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const versionMaxVersion = `-- name: VersionMaxVersion :one
SELECT COALESCE(MAX(version), 0) + 1 FROM skill_versions WHERE skill_id = $1
`

// skill: versioning.go
func (q *Queries) VersionMaxVersion(ctx context.Context, skillID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, versionMaxVersion, skillID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const versionPin = `-- name: VersionPin :exec
UPDATE skills SET pinned_version = $1 WHERE id = $2
`

type VersionPinParams struct {
	Version *int32    `json:"version"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) VersionPin(ctx context.Context, arg VersionPinParams) error {
	_, err := q.db.Exec(ctx, versionPin, arg.Version, arg.ID)
	return err
}

const versionUnpin = `-- name: VersionUnpin :exec
UPDATE skills SET pinned_version = NULL WHERE id = $1
`

func (q *Queries) VersionUnpin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, versionUnpin, id)
	return err
}
