// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package taskdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IssueTask struct {
	ID          uuid.UUID          `json:"id"`
	IssueID     uuid.UUID          `json:"issue_id"`
	Section     string             `json:"section"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Position    int32              `json:"position"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CompletedBy *string            `json:"completed_by"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	ProjectID   uuid.UUID          `json:"project_id"`
}

type TddSabotageRecord struct {
	ID              uuid.UUID `json:"id"`
	TaskID          uuid.UUID `json:"task_id"`
	Action          string    `json:"action"`
	ExpectedFailure *string   `json:"expected_failure"`
	ActualResult    *string   `json:"actual_result"`
	Restored        bool      `json:"restored"`
	PerformedAt     time.Time `json:"performed_at"`
}

type TddVerificationResult struct {
	ID         uuid.UUID `json:"id"`
	TaskID     uuid.UUID `json:"task_id"`
	Result     string    `json:"result"`
	Evidence   *string   `json:"evidence"`
	Notes      *string   `json:"notes"`
	VerifiedAt time.Time `json:"verified_at"`
	VerifiedBy *string   `json:"verified_by"`
}
