// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package projectlinkdb

import (
	"context"

	"github.com/google/uuid"
)

const getRules = `-- name: GetRules :one
SELECT rules FROM projects
WHERE id = $1::uuid AND deleted_at IS NULL
`

func (q *Queries) GetRules(ctx context.Context, projectID uuid.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, getRules, projectID)
	var rules []string
	err := row.Scan(&rules)
	return rules, err
}

const linkByGitRemote = `-- name: LinkByGitRemote :one
SELECT id::text, slug
FROM projects
WHERE deleted_at IS NULL
  AND repository_url = ANY($1::text[])
ORDER BY array_position($1::text[], repository_url)
LIMIT 1
`

type LinkByGitRemoteRow struct {
	ID   string `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) LinkByGitRemote(ctx context.Context, candidates []string) (LinkByGitRemoteRow, error) {
	row := q.db.QueryRow(ctx, linkByGitRemote, candidates)
	var i LinkByGitRemoteRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const setRules = `-- name: SetRules :exec
UPDATE projects
SET rules = $1, updated_at = NOW()
WHERE id = $2::uuid AND deleted_at IS NULL
`

type SetRulesParams struct {
	Rules     []string  `json:"rules"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) SetRules(ctx context.Context, arg SetRulesParams) error {
	_, err := q.db.Exec(ctx, setRules, arg.Rules, arg.ProjectID)
	return err
}

const updateBranch = `-- name: UpdateBranch :exec
UPDATE projects
SET current_branch = $1, updated_at = NOW()
WHERE id = $2::uuid AND deleted_at IS NULL
`

type UpdateBranchParams struct {
	Branch    *string   `json:"branch"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) error {
	_, err := q.db.Exec(ctx, updateBranch, arg.Branch, arg.ProjectID)
	return err
}
